bill = {
  bill_id: "536460000016104001",
  purchaseorder_ids: [],
  vendor_id: "536460000010962001",
  vendor_name: "Cleverscope Ltd",
  source: "Client",
  source_of_supply: "",
  source_of_supply_formatted: "",
  destination_of_supply: "HR",
  destination_of_supply_formatted: "Haryana",
  gst_no: "",
  reference_invoice_type: "",
  contact_category: "overseas",
  gst_treatment: "overseas",
  gst_treatment_formatted: "Overseas",
  tax_treatment: "overseas",
  tax_treatment_formatted: "Overseas",
  gst_return_details: {
    status_formatted: "",
    return_period: "",
    status: "",
    return_period_formatted: "",
  },
  invoice_conversion_type: "invoice",
  unused_credits_payable_amount: 2066938.0,
  unused_credits_payable_amount_formatted: "₹20,66,938.00",
  status: "paid",
  status_formatted: "Paid",
  color_code: "",
  current_sub_status_id: "",
  current_sub_status: "paid",
  current_sub_status_formatted: "Paid",
  sub_statuses: [],
  bill_number: "6635",
  date: "2021-04-01",
  date_formatted: "01/04/2021",
  is_pre_gst: false,
  due_date: "2021-04-01",
  due_date_formatted: "01/04/2021",
  discount_setting: "flat",
  is_tds_amount_in_percent: true,
  tds_percent_formatted: "0.00%",
  tds_percent: "0.00",
  tds_amount_formatted: "₹0.00",
  tds_amount: 0.0,
  tax_account_id: "",
  payment_terms: 0,
  payment_terms_label: "100 % Advance ",
  payment_expected_date: "",
  payment_expected_date_formatted: "",
  reference_number: "K2020-673",
  recurring_bill_id: "",
  due_by_days: 753,
  due_in_days: "",
  currency_id: "536460000000000064",
  currency_code: "INR",
  currency_symbol: "₹",
  currency_name_formatted: "INR- Indian Rupee",
  documents: [],
  price_precision: 2,
  exchange_rate: 1.0,
  custom_fields: [],
  custom_field_hash: {},
  is_viewed_by_client: false,
  client_viewed_time: "",
  client_viewed_time_formatted: "",
  is_tds_applied: false,
  is_item_level_tax_calc: false,
  is_inclusive_tax: false,
  tax_rounding: "entity_level",
  filed_in_vat_return_id: "",
  filed_in_vat_return_name: "",
  filed_in_vat_return_type: "",
  is_reverse_charge_applied: false,
  is_uber_bill: false,
  is_tally_bill: false,
  mark_as_received_status: "received",
  is_standalone_bill: true,
  track_discount_in_account: true,
  line_items: [
    {
      purchaseorder_item_id: "",
      receive_item_id: "",
      line_item_id: "536460000016104003",
      item_id: "536460000008725962",
      itc_eligibility: "eligible",
      gst_treatment_code: "",
      image_document_id: "",
      sku: "OAUCS320AE12B1",
      name: "Cleverscope CS320AE-12",
      is_combo_product: false,
      warehouse_id: "536460000000014524",
      warehouse_name: "Main Store",
      account_id: "536460000000000626",
      account_name: "Inventory Asset",
      description: "",
      bcy_rate: 93343.72,
      bcy_rate_formatted: "₹93,343.72",
      rate: 93343.72,
      rate_formatted: "₹93,343.72",
      pricebook_id: "",
      header_id: "",
      header_name: "",
      tags: [],
      quantity: 1.0,
      discount: 0.0,
      discounts: [],
      package_details: {
        length: "",
        width: "",
        height: "",
        weight: "",
        weight_unit: "kg",
        dimension_unit: "cm",
      },
      markup_percent: 0.0,
      markup_percent_formatted: "0.00%",
      tax_id: "",
      tax_exemption_id: "",
      tax_exemption_code: "",
      tax_name: "",
      tax_type: "tax",
      tax_percentage: 0,
      line_item_taxes: [],
      item_total: 93343.72,
      item_total_formatted: "₹93,343.72",
      item_total_inclusive_of_tax: 93343.72,
      item_total_inclusive_of_tax_formatted: "₹93,343.72",
      item_order: 1,
      unit: "Nos",
      product_type: "goods",
      item_type: "inventory",
      item_type_formatted: "Inventory Items",
      has_product_type_mismatch: false,
      hsn_or_sac: "90302000",
      reverse_charge_tax_id: "",
      image_name: "",
      image_type: "",
      is_billable: false,
      is_landedcost: false,
      customer_id: "",
      customer_name: "",
      project_id: "",
      project_name: "",
      invoice_id: "",
      invoice_number: "",
      item_custom_fields: [],
      track_serial_for_receive: false,
      track_batch_for_receive: false,
      serial_numbers: [],
      batches: [],
      purchase_request_items: [],
    },
    {
      purchaseorder_item_id: "",
      receive_item_id: "",
      line_item_id: "536460000016104005",
      item_id: "536460000008731147",
      itc_eligibility: "eligible",
      gst_treatment_code: "",
      image_document_id: "",
      sku: "AGPROBCS1002B1",
      name: "Anolog Probe CS1002",
      is_combo_product: false,
      warehouse_id: "536460000000014524",
      warehouse_name: "Main Store",
      account_id: "536460000000000626",
      account_name: "Inventory Asset",
      description: "",
      bcy_rate: 3403.49,
      bcy_rate_formatted: "₹3,403.49",
      rate: 3403.49,
      rate_formatted: "₹3,403.49",
      pricebook_id: "",
      header_id: "",
      header_name: "",
      tags: [],
      quantity: 2.0,
      discount: 0.0,
      discounts: [],
      package_details: {
        length: "",
        width: "",
        height: "",
        weight: "",
        weight_unit: "kg",
        dimension_unit: "cm",
      },
      markup_percent: 0.0,
      markup_percent_formatted: "0.00%",
      tax_id: "",
      tax_exemption_id: "",
      tax_exemption_code: "",
      tax_name: "",
      tax_type: "tax",
      tax_percentage: 0,
      line_item_taxes: [],
      item_total: 6806.98,
      item_total_formatted: "₹6,806.98",
      item_total_inclusive_of_tax: 6806.98,
      item_total_inclusive_of_tax_formatted: "₹6,806.98",
      item_order: 2,
      unit: "Nos",
      product_type: "goods",
      item_type: "inventory",
      item_type_formatted: "Inventory Items",
      has_product_type_mismatch: false,
      hsn_or_sac: "90302000",
      reverse_charge_tax_id: "",
      image_name: "",
      image_type: "",
      is_billable: false,
      is_landedcost: false,
      customer_id: "",
      customer_name: "",
      project_id: "",
      project_name: "",
      invoice_id: "",
      invoice_number: "",
      item_custom_fields: [],
      track_serial_for_receive: false,
      track_batch_for_receive: false,
      serial_numbers: [],
      batches: [],
      purchase_request_items: [],
    },
  ],
  submitted_date: "2022-03-30",
  submitted_date_formatted: "30/03/2022",
  submitted_by: "Girish Kumar (girish@kvtek.in)",
  submitted_by_name: "Girish Kumar",
  submitted_by_email: "girish@kvtek.in",
  submitted_by_photo_url:
    "https://contacts.zoho.in/file?t=user&ID=60008794037&fs=thumb",
  submitter_id: "536460000000024001",
  approver_id: "536460000000024001",
  adjustment: 0.0,
  adjustment_formatted: "₹0.00",
  adjustment_description: "Adjustment",
  discount_amount_formatted: "₹0.00",
  discount_amount: 0.0,
  discount: 0.0,
  discount_applied_on_amount_formatted: "₹0.00",
  discount_applied_on_amount: 0.0,
  is_discount_before_tax: true,
  discount_account_id: "",
  discount_account_name: "",
  discount_type: "entity_level",
  sub_total: 100150.7,
  sub_total_formatted: "₹1,00,150.70",
  sub_total_inclusive_of_tax: 100150.7,
  sub_total_inclusive_of_tax_formatted: "₹1,00,150.70",
  tax_total: 0.0,
  tax_total_formatted: "₹0.00",
  total: 100150.7,
  total_formatted: "₹1,00,150.70",
  payment_made: 99280.0,
  payment_made_formatted: "₹99,280.00",
  vendor_credits_applied: 870.7,
  vendor_credits_applied_formatted: "₹870.70",
  is_line_item_invoiced: false,
  purchaseorders: [],
  taxes: [],
  tax_override: false,
  balance: 0.0,
  balance_formatted: "₹0.00",
  billing_address: {
    address: "101B Mt Eden Rd,",
    street2: "Mt EdenAuckland",
    city: "Auckland",
    state: "",
    zip: "1024",
    country: "New Zealand",
    fax: "",
    phone: "",
    attention: "",
  },
  is_portal_enabled: false,
  payments: [
    {
      payment_id: "536460000019778901",
      bill_id: "536460000016104001",
      bill_payment_id: "536460000019778995",
      payment_mode: "Bank Transfer",
      payment_number: "3056",
      description: "",
      date: "2021-03-31",
      date_formatted: "31/03/2021",
      reference_number: "",
      exchange_rate: 1.0,
      amount: 99280.0,
      amount_formatted: "₹99,280.00",
      paid_through_account_id: "536460000000000459",
      paid_through_account_name: "Cash-in-Hand",
      is_single_bill_payment: 0,
      is_paid_via_print_check: false,
      check_details: {
        check_number: "",
        check_status: "",
        check_status_formatted: "",
      },
      is_ach_payment: false,
      ach_payment_status: "",
      ach_payment_status_formatted: "",
      gateway: "",
      gateway_formatted: "",
      ach_gw_transaction_id: "",
      filed_in_vat_return_id: "",
      filed_in_vat_return_name: "",
      filed_in_vat_return_type: "",
    },
  ],
  vendor_credits: [
    {
      vendor_credit_id: "536460000019778917",
      vendor_credit_bill_id: "536460000019778985",
      vendor_credit_number: "S&E",
      date: "2021-04-19",
      date_formatted: "19/04/2021",
      amount: 870.7,
      amount_formatted: "₹870.70",
    },
  ],
  journal_credits: [],
  comments: [
    {
      comment_id: "536460000019778997",
      bill_id: "536460000016104001",
      description: "Payment of ₹99,280.00 made",
      commented_by_id: "536460000000024001",
      commented_by: "Girish Kumar",
      comment_type: "system",
      date: "2023-03-01",
      date_formatted: "01/03/2023 12:00 PM",
      date_description: "53 days ago",
      time: "12:00 PM",
      operation_type: "Added",
      transaction_id: "536460000019778995",
      transaction_type: "bill_payment",
    },
    {
      comment_id: "536460000019778987",
      bill_id: "536460000016104001",
      description: "Credit of ₹870.70 applied from S&E",
      commented_by_id: "536460000000024001",
      commented_by: "Girish Kumar",
      comment_type: "system",
      date: "2023-03-01",
      date_formatted: "01/03/2023 11:59 AM",
      date_description: "53 days ago",
      time: "11:59 AM",
      operation_type: "Added",
      transaction_id: "536460000019778985",
      transaction_type: "vendor_credit_bill",
    },
    {
      comment_id: "536460000019778975",
      bill_id: "536460000016104001",
      description:
        "Bill updated. Amount changed from ₹1,00,150.71 to ₹1,00,150.70",
      commented_by_id: "536460000000024001",
      commented_by: "Girish Kumar",
      comment_type: "system",
      date: "2023-03-01",
      date_formatted: "01/03/2023 11:59 AM",
      date_description: "53 days ago",
      time: "11:59 AM",
      operation_type: "Updated",
      transaction_id: "",
      transaction_type: "bill",
    },
    {
      comment_id: "536460000016811727",
      bill_id: "536460000016104001",
      description: "Bill approved",
      commented_by_id: "536460000000024001",
      commented_by: "Girish Kumar",
      comment_type: "system",
      date: "2022-03-30",
      date_formatted: "30/03/2022 08:06 PM",
      date_description: "about a year ago",
      time: "8:06 PM",
      operation_type: "Updated",
      transaction_id: "",
      transaction_type: "bill",
    },
    {
      comment_id: "536460000016811721",
      bill_id: "536460000016104001",
      description: "Bill submitted for approval",
      commented_by_id: "536460000000024001",
      commented_by: "Girish Kumar",
      comment_type: "system",
      date: "2022-03-30",
      date_formatted: "30/03/2022 08:06 PM",
      date_description: "about a year ago",
      time: "8:06 PM",
      operation_type: "Updated",
      transaction_id: "",
      transaction_type: "bill",
    },
    {
      comment_id: "536460000016811713",
      bill_id: "536460000016104001",
      description:
        "Bill updated. Amount changed from ₹1,01,298.75 to ₹1,00,150.71",
      commented_by_id: "536460000000024001",
      commented_by: "Girish Kumar",
      comment_type: "system",
      date: "2022-03-30",
      date_formatted: "30/03/2022 08:06 PM",
      date_description: "about a year ago",
      time: "8:06 PM",
      operation_type: "Updated",
      transaction_id: "",
      transaction_type: "bill",
    },
    {
      comment_id: "536460000016104007",
      bill_id: "536460000016104001",
      description: "Bill created for ₹1,01,298.75",
      commented_by_id: "536460000000087007",
      commented_by: "Store",
      comment_type: "system",
      date: "2021-11-30",
      date_formatted: "30/11/2021 09:54 AM",
      date_description: "about a year ago",
      time: "9:54 AM",
      operation_type: "Added",
      transaction_id: "",
      transaction_type: "bill",
    },
  ],
  created_time: "2021-11-30T09:54:10+0530",
  created_by_id: "536460000000087007",
  last_modified_id: "536460000000024001",
  last_modified_time: "2023-03-01T12:00:10+0530",
  warn_create_vendor_credits: true,
  reference_id: "",
  notes: "",
  terms: "",
  attachment_name: "",
  html_string:
    '<!--The below style_start tag has to be present as it is used to substring the style content from the body html-->\n\n<!--style_start-->\n<style type="text/css" media="all">\n     \n\n  @font-face {\n    font-family: \'WebFont-Ubuntu\';\n    src: local(Ubuntu), url(https://fonts.gstatic.com/s/ubuntu/v10/4iCs6KVjbNBYlgoKcg72nU6AF7xm.woff2);\n  }\n\n  .pcs-template {\n  \tfont-family: Ubuntu, \'WebFont-Ubuntu\';\n    font-size: 9pt;\n    color: #333333;\n      background:  #ffffff ;\n  }\n\n  .pcs-header-content {\n    font-size: 9pt;\n\tcolor: #333333;\n\tbackground-color: #ffffff;\n  }\n  .pcs-template-body {\n  \tpadding: 0 0.400000in 0 0.550000in;\n  }\n  .pcs-template-footer {\n  \theight: 0.700000in;\n\tfont-size: 6pt;\n\tcolor: #aaaaaa;\n\tpadding: 0 0.400000in 0 0.550000in;\n\tbackground-color: #ffffff;\n  }\n  .pcs-footer-content {\n  word-wrap: break-word;\n  color: #aaaaaa;\n      border-top: 1px solid #adadad;\n  }\n\n  .pcs-label {\n    color: #333333;\n  }\n  .pcs-entity-title {\n    font-size: 28pt;\n    color: #000000;\n  }\n  .pcs-orgname {\n    font-size: 10pt;\n    color: #333333;\n  }\n  .pcs-customer-name {\n    font-size: 9pt;\n    color: #333333;\n  }\n  .pcs-eori-number {\n    color: #333;\n    margin: 0;\n    padding-top: 10px;\n  }\n .pcs-itemtable-header {\n    font-size: 9pt;\n    color: #ffffff;\n    background-color: #3c3d3a;\n  }\n  .pcs-itemtable-breakword {\n    word-wrap: break-word;\n  }\n  .pcs-taxtable-header {\n    font-size: 9pt;\n    color: #ffffff;\n    background-color: #3c3d3a;\n  }\n  .breakrow-inside {\n    page-break-inside: avoid;\n  }\n  .breakrow-after {\n    page-break-after:auto;\n  }\n  .pcs-item-row {\n    font-size: 9pt;\n    border-bottom: 1px solid #adadad;\n    background-color: #ffffff;\n    color: #000000;\n  }\n  .pcs-img-fit-aspectratio {\n    object-fit: contain;\n    object-position: top;\n  }\n  .pcs-img-border {\n    border: 1px solid #f5f4f3;\n  }\n  .pcs-item-sku, .pcs-item-hsn, .pcs-item-coupon, .pcs-item-serialnumber, .pcs-item-unitcode {\n    margin-top: 2px;\n  \tfont-size: 10px;\n  \tcolor: #444444;\n  }\n  .pcs-item-desc {\n      color: #333333;\n      font-size: 8pt;\n   }\n  .pcs-balance {\n    background-color: #f5f4f3;\n    font-size: 9pt;\n    color: #000000;\n  }\n  .pcs-savings {\n  font-size: 0pt;\n  color: ;\n  background-color: ;\n  }\n  .pcs-totals {\n    font-size: 9pt;\n    color: #000000;\n    background-color: #ffffff;\n  }\n  .pcs-notes {\n    font-size: 8pt;\n  }\n  .pcs-terms {\n    font-size: 8pt;\n  }\n  .pcs-header-first {\n\tbackground-color: #ffffff;\n\tfont-size: 9pt;\n\tcolor: #333333;\n      height: auto;\n\t}\n\n .pcs-status {\n \tcolor: ;\n\tfont-size: 15pt;\n\tborder: 3px solid ;\n\tpadding: 3px 8px;\n }\n .billto-section {\n     padding-top: 0mm;\n     padding-left: 0mm;\n   }\n   .shipto-section {\n     padding-top: 0mm;\n     padding-left: 0mm;\n   }\n\n @page :first {\n \t@top-center {\n\t\tcontent: element(header);\n\t}\n    margin-top: 0.700000in;\n  }\n\n  .pcs-template-header {\n\tpadding: 0 0.400000in 0 0.550000in;\n    height: 0.700000in;\n  }\n\n  .pcs-template-fill-emptydiv {\n    display: table-cell;\n    content: " ";\n    width: 100%;\n  }\n\n\n/* Additional styles for RTL compat */\n\n/* Helper Classes */\n\n.inline {\n  display: inline-block;\n}\n.v-top {\n  vertical-align: top;\n}\n.text-align-right {\n  text-align: right;\n}\n.rtl .text-align-right {\n  text-align: left;\n}\n.text-align-left {\n  text-align: left;\n}\n.rtl .text-align-left {\n  text-align: right;\n}\n.float-section-right {\n  float: right;\n}\n.rtl .float-section-right{\n  float: left;\n}\n.float-section-left {\n  float: left;\n}\n.rtl .float-section-left{\n  float: right;\n}\n\n/* Helper Classes End */\n\n.item-details-inline {\n  display: inline-block;\n  margin: 0 10px;\n  vertical-align: top;\n  max-width: 70%;\n}\n\n.total-in-words-container {\n  width: 100%;\n  margin-top: 10px;\n}\n.total-in-words-label {\n  vertical-align: top;\n  padding: 0 10px;\n}\n.total-in-words-value {\n  width: 170px;\n}\n.total-section-label {\n  padding: 5px 10px 5px 0;\n  vertical-align: middle;\n}\n.total-section-value {\n  width: 120px;\n  vertical-align: middle;\n  padding: 10px 10px 10px 5px;\n}\n.rtl .total-section-value {\n  padding: 10px 5px 10px 10px;\n}\n\n.tax-summary-description {\n  color: #727272;\n  font-size: 8pt;\n}\n\n.bharatqr-bg {\n  background-color: #f4f3f8;\n}\n\n/* Overrides/Patches for RTL compat */\n  .rtl th {\n    text-align: inherit; /* Specifically setting th as inherit for supporting RTL */\n  }\n/* Overrides/Patches End */\n\n  /* Signature styles */\n  .sign-border {\n    width: 200px;\n    border-bottom: 1px solid #000;\n  }\n  .sign-label {\n    display: table-cell;\n    font-size: 10pt;\n    padding-right: 5px;\n  }\n  /* Signature styles End */\n\n/* Subject field styles */\n.subject-block {\n    margin-top: 20px;\n}\n.subject-block-value {\n    word-wrap: break-word;\n    white-space: pre-wrap;\n    line-height: 14pt;\n    margin-top:5px;\n}\n/* Subject field styles End*/\n\n.pcs-sub-label {\n  color: #666;\n  font-size: 10px;\n}\n.pcs-hsnsummary-compact {\n  padding: 0;\n  margin-top: 3px;\n}\n.pcs-hsnsummary-label-compact {\n  margin-bottom: 3px;\n  font-weight:600;\n  padding-left: 3px;\n  font-size: 9pt;\n}\n.pcs-hsnsummary-header-compact {\n  text-align:right;\n  padding: 5px 7px 2px 7px;\n  word-wrap: break-word;\n  width: 17%;\n  height: 32px;\n  border-right: 1px solid #9E9E9E;\n  font-size: 8pt;\n  font-weight: 600;\n}\n.pcs-hsnsummary-body-compact, .pcs-hsnsummary-total-compact {\n  text-align:right;\n  word-wrap: break-word;\n  font-size: 7pt;\n  padding: 4px 10px;\n}\n.pcs-hsnsummary-total-compact {\n  border-top: 1px solid #adadad;\n}\n.pcs-ukvat-summary {\n  margin-top:50px;\n  clear: both;\n  width: 100%;\n}\n.pcs-ukvat-summary-header {\n  padding:5px 10px 5px 5px;\n}\n.pcs-ukvat-summary-header:first-child {\n  padding-left: 10px;\n}\n.pcs-ukvat-summary-label {\n  font-size: 10pt;\n}\n.pcs-ukvat-summary-table {\n  margin-top: 10px;\n  width: 100%;\n  table-layout: fixed;\n}\n.pcs-ukvat-summary-body, .pcs-ukvat-summary-total {\n  padding: 10px 10px 5px 10px;\n}\n.pcs-ukvat-summary-body:first-child {\n  padding-bottom: 10px;\n  padding-right: 0;\n}\n.pcs-payment-block {\n  margin-top: 20px;\n}\n.pcs-payment-block-inner {\n  margin-top: 10px;\n}\n\n.pcs-entity-label-section {\n  padding:5px 10px 5px 0px;\n  font-size: 10pt;\n }\n\n.pcs-colon {\n  width: 3%;\n}\n\n\n     .bills-header-section {\n        float: left;\n        width: 35%;\n      }\n      .rtl .bills-header-section {\n        float: right;\n      }\n      .bills-title-section {\n         float: right;\n         width: 35%;\n       }\n       .rtl .bills-title-section {\n         float: left;\n       }\n     .lineitem-header {\n       padding: 5px 10px 5px 5px;\n       word-wrap: break-word;\n       width: 11%;\n     }\n     .rtl .lineitem-header {\n       padding: 5px 5px 5px 10px;\n     }\n     .lineitem-column {\n       padding: 10px 10px 5px 10px;\n       word-wrap: break-word;\n       vertical-align: top;\n     }\n     .total-number-section {\n       float: left;\n       width: 45%;\n       padding: 3px 10px 3px 3px;\n       font-size: 9pt;\n     }\n     .rtl .total-number-section {\n       float: right;\n     }\n     .total-section {\n       float: right;\n       width: 50%;\n     }\n     .rtl .total-section {\n       float: left;\n     }\n     .total-section-label {\n       padding: 5px 10px 5px 0;\n       vertical-align: middle;\n     }\n     .total-section-value {\n       width: 120px;\n       padding: 10px 10px 10px 5px;\n       vertical-align: middle;\n     }\n     .rtl .total-section-value {\n       padding: 10px 5px 10px 10px;\n     }\n</style>\n\n<!--style_end-->\n\n<div class="pcs-template ">\n\t  <div id="header" class="pcs-template-header pcs-header-content" >\n    \n\n    \n    <div class="pcs-template-fill-emptydiv"></div>\n\n  </div>\n\n\t<div class="pcs-template-body">\n\t\t<div style="display:table;width:100%;">\n         <div class="text-align-left bills-header-section">\n             <div>\n                    <img id="logo_content" style="width:74px;height:72px;" src="https://inventory.zoho.in/ZFInvoiceLogo.zbfs?logo_id=85f9b86c9358f692665d4d07b8857d0d" />\n            </div>\n            <span class="pcs-orgname"><b>KVTEK Power Systems Pvt. Ltd.</b></span><br />\n            <span class="pcs-label">\n            <span id="tmp_org_address" style="white-space: pre-wrap;">Company ID : U74220DL2005PTC135994&#10;284-286 &amp; 290&#10;Sector-8, IMT Manesar&#10;Gurgaon Haryana 122050&#10;India&#10;GSTIN 06AABCE4590P1Z7&#10;PAN AABCE4590P</span>\n            </span>\n         </div>\n         <div class="text-align-right bills-title-section">\n            <span class="pcs-entity-title">Bill</span><br />\n            <span class="pcs-label" style="font-size: 10pt;" id="tmp_entity_number"><b>Bill# 6635</b></span>\n            <div style="clear:both;margin-top:20px;">\n                <span style="font-size:8pt;"><b>Balance Due</b></span><br />\n                <span style="font-size:12pt;"><b>₹0.00</b></span>\n            </div>\n         </div>\n     </div>\n\n     <table style="width:100%;margin-top:30px;table-layout:fixed;">\n         <tr>\n         <td style="width:60%;vertical-align:bottom;word-wrap: break-word;">\n<div><label class="pcs-label" id="tmp_billing_address_label" style="font-size: 10pt;">Bill From</label>\n            <br />\n            <span id="tmp_billing_address" style="white-space: pre-wrap;"><strong><span id="zb-pdf-customer-detail" class="pcs-customer-name">Cleverscope Ltd</span></strong>\n101B Mt Eden Rd,&#10;Mt EdenAuckland\nAuckland\n1024 \nNew Zealand</span>\n            </div>          </td>\n         <td style="vertical-align:bottom;width: 40%;" align="right">\n             <table cellpadding="0" cellspacing="0" border="0" style="float:right;width: 100%;table-layout: fixed;word-wrap: break-word;">\n                 <tbody>\n                    <tr>\n                         <td class="text-align-right" style="padding:5px 10px 5px 0px;font-size: 10pt;">\n                            <span  class="pcs-label">Order Number :</span>\n                      </td>\n                      <td class="text-align-right">\n                          <span id="tmp_ref_number">K2020-673</span>\n                      </td>\n                    </tr>\n                     <tr>\n                         <td class="text-align-right" style="padding:5px 10px 5px 0px;font-size:10pt;">\n                            <span  class="pcs-label">Bill Date :</span>\n                        </td>\n                        <td class="text-align-right">\n                            <span id="tmp_entity_date">01/04/2021</span>\n                        </td>\n                    </tr>\n                    <tr>\n                         <td class="text-align-right" style="padding:5px 10px 5px 0px;font-size: 10pt;">\n                            <span class="pcs-label">DueDate :</span>\n                        </td>\n                        <td class="text-align-right">\n                            <span id="tmp_due_date">01/04/2021</span>\n                        </td>\n                    </tr>\n                    <tr>\n                         <td class="text-align-right" style="padding:5px 10px 5px 0px;font-size: 10pt;">\n                            <span class="pcs-label">Terms :</span>\n                        </td>\n                        <td class="text-align-right">\n                            <span id="tmp_due_date">100 % Advance </span>\n                        </td>\n                    </tr>\n                 </tbody>\n              </table>\n         </td>\n         </tr>\n     </table>\n  <table cellpadding="0" cellspacing="0" border="0" class="pcs-itemtable" style="width:100%;margin-top:20px;table-layout:fixed;">\n    <thead>\n        <tr style="height:32px;">\n              <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 0px 5px 5px;width: 5%;text-align: center;">\n      #\n    </td>\n    <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 10px 5px 20px;width: ;text-align: left;">\n      Item &amp; Description\n    </td>\n    <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 10px 5px 5px;width: 15%;text-align: right;">\n      HSN/SAC\n    </td>\n    <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 10px 5px 5px;width: 11%;text-align: right;">\n      Qty\n    </td>\n    <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 10px 5px 5px;width: 11%;text-align: right;">\n      Rate\n    </td>\n    <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 10px 5px 5px;width: 15%;text-align: right;">\n      Amount\n    </td>\n\n        </tr>\n     </thead>\n     <tbody class="itemBody">\n            <tr class="breakrow-inside breakrow-after">\n            <td class="pcs-item-row" style="padding: 10px 0 10px 5px;text-align: center;word-wrap: break-word;" valign="top" rowspan="1">\n              1\n            </td>\n            <td class="pcs-item-row" style="padding: 10px 0px 10px 20px;" valign="top" rowspan="1">\n\t\t\t\t\t\t \t<div >\n\t\t\t\t\t\t\t<div >\n               <span id="tmp_item_name" style="word-wrap: break-word;">Cleverscope CS320AE-12</span><br />\n               \n               <span id="tmp_item_description" class="pcs-item-desc" style="white-space: pre-wrap;word-wrap: break-word;"></span>\n               \n\t\t\t\t\t\t\t </div>\n\t\t\t\t\t\t\t</div>\n            </td>\n                             <td class="pcs-item-row lineitem-column text-align-right" rowspan="1">\n                                 <span id="tmp_item_qty">90302000</span>\n                             </td>\n\n\n\n\n\n\n\n\n                <td class="pcs-item-row lineitem-column text-align-right" rowspan="1">\n                  <span id="tmp_item_qty">1.00</span>\n                  <div class="pcs-item-desc">Nos</div>\n                </td>\n            <td class="pcs-item-row lineitem-column text-align-right" rowspan="1">\n              <span id="tmp_item_rate">93,343.72</span>\n            </td>\n            <td class="pcs-item-row lineitem-column text-align-right" rowspan="1">\n                <span id="tmp_item_amount">93,343.72</span>\n              </td>\n          </tr>\n            <tr class="breakrow-inside breakrow-after">\n            <td class="pcs-item-row" style="padding: 10px 0 10px 5px;text-align: center;word-wrap: break-word;" valign="top" rowspan="1">\n              2\n            </td>\n            <td class="pcs-item-row" style="padding: 10px 0px 10px 20px;" valign="top" rowspan="1">\n\t\t\t\t\t\t \t<div >\n\t\t\t\t\t\t\t<div >\n               <span id="tmp_item_name" style="word-wrap: break-word;">Anolog Probe CS1002</span><br />\n               \n               <span id="tmp_item_description" class="pcs-item-desc" style="white-space: pre-wrap;word-wrap: break-word;"></span>\n               \n\t\t\t\t\t\t\t </div>\n\t\t\t\t\t\t\t</div>\n            </td>\n                             <td class="pcs-item-row lineitem-column text-align-right" rowspan="1">\n                                 <span id="tmp_item_qty">90302000</span>\n                             </td>\n\n\n\n\n\n\n\n\n                <td class="pcs-item-row lineitem-column text-align-right" rowspan="1">\n                  <span id="tmp_item_qty">2.00</span>\n                  <div class="pcs-item-desc">Nos</div>\n                </td>\n            <td class="pcs-item-row lineitem-column text-align-right" rowspan="1">\n              <span id="tmp_item_rate">3,403.49</span>\n            </td>\n            <td class="pcs-item-row lineitem-column text-align-right" rowspan="1">\n                <span id="tmp_item_amount">6,806.98</span>\n              </td>\n          </tr>\n      \n    </tbody>\n    </table>\n   <div style="width: 100%;margin-top: 1px;">\n    <div class="total-number-section">\n      <div style="white-space: pre-wrap;"></div>\n    </div>\n    <div class="total-section">\n      <table width="100%" border="0"  cellspacing="0" class="pcs-totals">\n        <tbody>\n            <tr>\n                <td class="total-section-label text-align-right">Sub Total</td>\n                <td class="total-section-value text-align-right" id="tmp_subtotal">1,00,150.70</td>\n            </tr>\n\n\n          <tr >\n            <td class="total-section-label text-align-right"><b>Total</b></td>\n            <td class="total-section-value text-align-right" id="tmp_total"><b>₹1,00,150.70</b></td>               </tr>\n\n\n          <tr style="height:10px;">\n            <td class="total-section-label text-align-right">\n                Payments Made\n            </td>\n            <td style="color: red;" class="total-section-value text-align-right">(-) 99,280.00</td>\n          </tr>\n          <tr style="height:10px;">\n            <td class="total-section-label text-align-right">\n                Credits Applied\n            </td>\n            <td style="color: red;" class="total-section-value text-align-right">(-) 870.70</td>\n          </tr>\n\n          <tr class="pcs-balance" style="height:40px;">\n            <td style="padding:5px 10px 5px 0;" valign="middle" class="text-align-right"><b>Balance Due</b></td>\n            <td class="total-section-value text-align-right" id="tmp_balance_due"><b>₹0.00</b></td>\n          </tr>\n        </tbody>\n      </table>\n    </div>\n    <div style="clear: both;"></div>\n  </div>\n\n  \n\n        <div style="margin-top:30px;">\n          <label class="pcs-label" style="display: table-cell;font-size: 10pt;padding-right: 5px;">Authorized Signature</label>\n            <div style="display: table-cell;">\n                <div style="display: inline-block;width: 200px;border-bottom: 1px solid #000;"></div>\n                <div></div>\n            </div>\n        </div>\n    \n\t</div>\n\t  <div class="pcs-template-footer">\n    <div >\n      \n    </div>  \n  </div>\n\n</div>\n',
  open_purchaseorders_count: 0,
  un_billed_items: { un_billed_items_group: [], has_unbilled_items: false },
  template_id: "536460000000000245",
  template_name: "Standard Template",
  page_width: "8.27in",
  page_height: "11.69in",
  orientation: "portrait",
  template_type: "standard",
  template_type_formatted: "Standard",
  invoices: [],
  is_approval_required: false,
  can_create_bill_of_entry: true,
  allocated_landed_costs: [],
  unallocated_landed_costs: [],
  entity_type: "bill",
  credit_notes: [],
  reference_bill_id: "",
  can_send_in_mail: false,
  approvers_list: [
    {
      order: 1,
      approver_user_id: "536460000000024001",
      approver_name: "Girish Kumar",
      email: "girish@kvtek.in",
      has_approved: true,
      approval_status: "approved",
      approval_status_formatted: "approved",
      is_next_approver: false,
      submitted_date: "",
      submitted_date_formatted: "",
      approved_date: "2022-03-30",
      approved_date_formatted: "30/03/2022",
      photo_url: "https://contacts.zoho.in/file?t=user&ID=60008794037&fs=thumb",
      user_status: "active",
      user_status_formatted: "Active",
      is_final_approver: false,
      available_apps: ["Zoho Books", "Zoho Inventory"],
      zuid: "60008794037",
    },
  ],
};
