composite_item = {
  composite_item_id: "536460000018642288",
  name: "1.2nF 250kV Base frame HV Filter with Paint",
  unit: "Nos",
  category_id: "536460000001457057",
  page_layout_id: "",
  offline_created_date_with_time: "",
  offline_created_date_with_time_formatted: "",
  show_in_storefront: false,
  brand: "",
  manufacturer: "",
  url: "c2c0fa01c8",
  product_description: "",
  product_tags: [],
  product_short_description: "",
  category_name: "Work in Progress",
  hsn_or_sac: "",
  item_tax_preferences: [
    {
      tax_specification: "inter",
      tax_type: 0,
      tax_name: "IGST18",
      tax_percentage: 18.0,
      tax_id: "536460000000021131",
    },
    {
      tax_specification: "intra",
      tax_type: 2,
      tax_name: "GST18",
      tax_percentage: 18.0,
      tax_id: "536460000000021143",
    },
  ],
  documents: [],
  description: "",
  tax_id: "",
  tax_name: "",
  tax_name_formatted: "",
  tax_percentage: 0,
  tax_type: "",
  is_taxable: true,
  tax_exemption_id: "",
  tax_exemption_code: "",
  product_type: "goods",
  product_type_formatted: "Goods",
  taxability_type: "none",
  purchase_account_id: "536460000000000567",
  purchase_account_name: "Cost of Goods Sold",
  account_id: "536460000000000486",
  account_name: "Sales",
  inventory_account_id: "536460000000014533",
  inventory_account_name: "Work In Progress",
  tags: [],
  status: "active",
  status_formatted: "Active",
  source: "user",
  source_formatted: "User",
  is_combo_product: true,
  is_boxing_exist: false,
  item_type: "inventory",
  item_type_formatted: "Inventory Items",
  rate: 8449.36,
  rate_formatted: "₹8,449.36",
  label_rate: 0.0,
  label_rate_formatted: "₹0.00",
  pricebook_rate: 8449.36,
  pricebook_discount: "",
  purchase_rate: 8449.36,
  purchase_rate_formatted: "₹8,449.36",
  sales_rate: 8449.36,
  sales_rate_formatted: "₹8,449.36",
  reorder_level: "",
  is_returnable: true,
  initial_stock: 0.0,
  initial_stock_formatted: "0.00",
  initial_stock_rate: 0.0,
  total_initial_stock: 0.0,
  total_initial_stock_formatted: "0.00",
  vendor_id: "",
  vendor_name: "",
  stock_on_hand: 0.0,
  stock_on_hand_formatted: "0.00",
  asset_value: "",
  asset_value_formatted: "",
  available_stock: 0.0,
  available_stock_formatted: "0.00",
  actual_available_stock: 0.0,
  actual_available_stock_formatted: "0.00",
  committed_stock: 0.0,
  committed_stock_formatted: "0.00",
  actual_committed_stock: 0.0,
  actual_committed_stock_formatted: "0.00",
  available_for_sale_stock: 0.0,
  available_for_sale_stock_formatted: "0.00",
  actual_available_for_sale_stock: 0.0,
  actual_available_for_sale_stock_formatted: "0.00",
  track_serial_number: false,
  track_batch_number: false,
  sku: "",
  upc: "",
  upc_formatted: "",
  ean: "",
  ean_formatted: "",
  isbn: "",
  part_number: "",
  image_document_id: "",
  image_name: "",
  purchase_description: "",
  custom_fields: [],
  custom_field_hash: {},
  seo_description: "",
  seo_keyword: "",
  seo_title: "",
  specifications: [],
  specificationset_id: "",
  specificationset_name: "",
  last_modified_time: "2022-11-16T17:30:10+0530",
  package_details: {
    length: "",
    width: "",
    height: "",
    weight: "",
    weight_unit: "kg",
    dimension_unit: "cm",
  },
  mapped_items: [
    {
      mapped_item_id: "536460000018642293",
      item_id: "536460000018616850",
      item_order: 0,
      name: "1.2nF 250kV Base frame HV Filter without Paint",
      rate: 8015.61,
      rate_formatted: "₹8,015.61",
      purchase_rate: 8015.61,
      purchase_rate_formatted: "₹8,015.61",
      is_combo_product: true,
      sku: "",
      status: 1,
      image_name: "",
      image_document_id: "",
      purchase_description: "",
      image_type: "",
      pricebook_rate: 8015.61,
      pricebook_discount: "",
      price_brackets: [],
      product_type: "goods",
      product_type_formatted: "Goods",
      unit: "Nos",
      description: "",
      quantity: 1.0,
      stock_on_hand: 0.0,
      stock_on_hand_formatted: "0.00",
      available_stock: 0.0,
      available_stock_formatted: "0.00",
      actual_available_stock: 0.0,
      actual_available_stock_formatted: "0.00",
      track_serial_number: false,
      track_batch_number: false,
      purchase_account_id: "536460000000000567",
      inventory_account_id: "536460000000014533",
    },
    {
      mapped_item_id: "536460000018642295",
      item_id: "536460000016270134",
      item_order: 1,
      name: "PU Blue Paint RAL 5013",
      rate: 380.0,
      rate_formatted: "₹380.00",
      purchase_rate: 380.0,
      purchase_rate_formatted: "₹380.00",
      is_combo_product: false,
      sku: "PUPTXRAL5013P1",
      status: 1,
      image_name: "",
      image_document_id: "",
      purchase_description: "",
      image_type: "",
      pricebook_rate: 380.0,
      pricebook_discount: "",
      price_brackets: [],
      product_type: "goods",
      product_type_formatted: "Goods",
      unit: "Ltr",
      description: "",
      quantity: 0.6,
      stock_on_hand: 0.0,
      stock_on_hand_formatted: "0.00",
      available_stock: 0.0,
      available_stock_formatted: "0.00",
      actual_available_stock: 0.0,
      actual_available_stock_formatted: "0.00",
      track_serial_number: false,
      track_batch_number: false,
      purchase_account_id: "536460000008719734",
      inventory_account_id: "536460000000000626",
    },
    {
      mapped_item_id: "536460000018642297",
      item_id: "536460000017284162",
      item_order: 2,
      name: "Epoxy Primer Red oxide Shalimar",
      rate: 245.0,
      rate_formatted: "₹245.00",
      purchase_rate: 245.0,
      purchase_rate_formatted: "₹245.00",
      is_combo_product: false,
      sku: "PPREPSAHXXXXXXP1",
      status: 1,
      image_name: "",
      image_document_id: "",
      purchase_description: "",
      image_type: "",
      pricebook_rate: 245.0,
      pricebook_discount: "",
      price_brackets: [],
      product_type: "goods",
      product_type_formatted: "Goods",
      unit: "Ltr",
      description: "",
      quantity: 0.6,
      stock_on_hand: 0.0,
      stock_on_hand_formatted: "0.00",
      available_stock: 0.0,
      available_stock_formatted: "0.00",
      actual_available_stock: 0.0,
      actual_available_stock_formatted: "0.00",
      track_serial_number: false,
      track_batch_number: false,
      purchase_account_id: "536460000000000567",
      inventory_account_id: "536460000000000626",
    },
    {
      mapped_item_id: "536460000018642299",
      item_id: "536460000015075536",
      item_order: 3,
      name: 'Hi Tack Masking Tape (24x20) 1"',
      rate: 35.0,
      rate_formatted: "₹35.00",
      purchase_rate: 35.0,
      purchase_rate_formatted: "₹35.00",
      is_combo_product: false,
      sku: "HTMSKT3M2430PM",
      status: 1,
      image_name: "",
      image_document_id: "",
      purchase_description: "",
      image_type: "",
      pricebook_rate: 35.0,
      pricebook_discount: "",
      price_brackets: [],
      product_type: "goods",
      product_type_formatted: "Goods",
      unit: "Roll",
      description: "",
      quantity: 0.01,
      stock_on_hand: 108.0,
      stock_on_hand_formatted: "108.00",
      available_stock: 108.0,
      available_stock_formatted: "108.00",
      actual_available_stock: 108.0,
      actual_available_stock_formatted: "108.00",
      track_serial_number: false,
      track_batch_number: false,
      purchase_account_id: "536460000008719734",
      inventory_account_id: "536460000000000626",
    },
    {
      mapped_item_id: "536460000018642301",
      item_id: "536460000014301273",
      item_order: 4,
      name: "S.T Thinner",
      rate: 50.0,
      rate_formatted: "₹50.00",
      purchase_rate: 50.0,
      purchase_rate_formatted: "₹50.00",
      is_combo_product: false,
      sku: "PTHNSTXXXXXXP1",
      status: 1,
      image_name: "",
      image_document_id: "",
      purchase_description: "",
      image_type: "",
      pricebook_rate: 50.0,
      pricebook_discount: "",
      price_brackets: [],
      product_type: "goods",
      product_type_formatted: "Goods",
      unit: "Ltr",
      description: "",
      quantity: 0.01,
      stock_on_hand: 200.0,
      stock_on_hand_formatted: "200.00",
      available_stock: 200.0,
      available_stock_formatted: "200.00",
      actual_available_stock: 200.0,
      actual_available_stock_formatted: "200.00",
      track_serial_number: false,
      track_batch_number: false,
      purchase_account_id: "536460000008719734",
      inventory_account_id: "536460000000000626",
    },
    {
      mapped_item_id: "536460000018642303",
      item_id: "536460000016035348",
      item_order: 5,
      name: "DHOTI OLD",
      rate: 5.0,
      rate_formatted: "₹5.00",
      purchase_rate: 5.0,
      purchase_rate_formatted: "₹5.00",
      is_combo_product: false,
      sku: "DHTOLDXXXXXXZZ",
      status: 1,
      image_name: "",
      image_document_id: "",
      purchase_description: "",
      image_type: "",
      pricebook_rate: 5.0,
      pricebook_discount: "",
      price_brackets: [],
      product_type: "goods",
      product_type_formatted: "Goods",
      unit: "Nos",
      description: "",
      quantity: 3.0,
      stock_on_hand: 150.0,
      stock_on_hand_formatted: "150.00",
      available_stock: 150.0,
      available_stock_formatted: "150.00",
      actual_available_stock: 150.0,
      actual_available_stock_formatted: "150.00",
      track_serial_number: false,
      track_batch_number: false,
      purchase_account_id: "536460000000000567",
      inventory_account_id: "536460000000000626",
    },
    {
      mapped_item_id: "536460000018642305",
      item_id: "536460000016035377",
      item_order: 6,
      name: "DHOTI WHITE",
      rate: 8.5,
      rate_formatted: "₹8.50",
      purchase_rate: 8.5,
      purchase_rate_formatted: "₹8.50",
      is_combo_product: false,
      sku: "DHTWTHXXXXXXZZ",
      status: 1,
      image_name: "",
      image_document_id: "",
      purchase_description: "",
      image_type: "",
      pricebook_rate: 8.5,
      pricebook_discount: "",
      price_brackets: [],
      product_type: "goods",
      product_type_formatted: "Goods",
      unit: "Nos",
      description: "",
      quantity: 1.0,
      stock_on_hand: 372.0,
      stock_on_hand_formatted: "372.00",
      available_stock: 372.0,
      available_stock_formatted: "372.00",
      actual_available_stock: 372.0,
      actual_available_stock_formatted: "372.00",
      track_serial_number: false,
      track_batch_number: false,
      purchase_account_id: "536460000000000567",
      inventory_account_id: "536460000000000626",
    },
    {
      mapped_item_id: "536460000018642307",
      item_id: "536460000013086527",
      item_order: 7,
      name: "Emery Paper 100 No",
      rate: 17.2,
      rate_formatted: "₹17.20",
      purchase_rate: 17.2,
      purchase_rate_formatted: "₹17.20",
      is_combo_product: false,
      sku: "EPSCRG3M0100SP",
      status: 1,
      image_name: "",
      image_document_id: "",
      purchase_description: "",
      image_type: "",
      pricebook_rate: 17.2,
      pricebook_discount: "",
      price_brackets: [],
      product_type: "goods",
      product_type_formatted: "Goods",
      unit: "Nos",
      description: "",
      quantity: 2.0,
      stock_on_hand: 200.0,
      stock_on_hand_formatted: "200.00",
      available_stock: 200.0,
      available_stock_formatted: "200.00",
      actual_available_stock: 200.0,
      actual_available_stock_formatted: "200.00",
      track_serial_number: false,
      track_batch_number: false,
      purchase_account_id: "536460000008719734",
      inventory_account_id: "536460000000000626",
    },
  ],
  sales_channels: [],
  composite_component_items: [
    {
      mapped_item_id: "536460000018642293",
      item_id: "536460000018616850",
      item_order: 0,
      name: "1.2nF 250kV Base frame HV Filter without Paint",
      rate: 8015.61,
      rate_formatted: "₹8,015.61",
      purchase_rate: 8015.61,
      purchase_rate_formatted: "₹8,015.61",
      sku: "",
      status: 1,
      image_name: "",
      image_document_id: "",
      purchase_description: "",
      image_type: "",
      unit: "Nos",
      product_type: "goods",
      is_combo_product: true,
      description: "",
      quantity: 1.0,
      stock_on_hand: 0.0,
      stock_on_hand_formatted: "0.00",
      available_stock: 0.0,
      available_stock_formatted: "0.00",
      actual_available_stock: 0.0,
      actual_available_stock_formatted: "0.00",
      purchase_account_id: "536460000000000567",
      inventory_account_id: "536460000000014533",
    },
    {
      mapped_item_id: "536460000018642295",
      item_id: "536460000016270134",
      item_order: 1,
      name: "PU Blue Paint RAL 5013",
      rate: 380.0,
      rate_formatted: "₹380.00",
      purchase_rate: 380.0,
      purchase_rate_formatted: "₹380.00",
      sku: "PUPTXRAL5013P1",
      status: 1,
      image_name: "",
      image_document_id: "",
      purchase_description: "",
      image_type: "",
      unit: "Ltr",
      product_type: "goods",
      is_combo_product: false,
      description: "",
      quantity: 0.6,
      stock_on_hand: 0.0,
      stock_on_hand_formatted: "0.00",
      available_stock: 0.0,
      available_stock_formatted: "0.00",
      actual_available_stock: 0.0,
      actual_available_stock_formatted: "0.00",
      purchase_account_id: "536460000008719734",
      inventory_account_id: "536460000000000626",
    },
    {
      mapped_item_id: "536460000018642297",
      item_id: "536460000017284162",
      item_order: 2,
      name: "Epoxy Primer Red oxide Shalimar",
      rate: 245.0,
      rate_formatted: "₹245.00",
      purchase_rate: 245.0,
      purchase_rate_formatted: "₹245.00",
      sku: "PPREPSAHXXXXXXP1",
      status: 1,
      image_name: "",
      image_document_id: "",
      purchase_description: "",
      image_type: "",
      unit: "Ltr",
      product_type: "goods",
      is_combo_product: false,
      description: "",
      quantity: 0.6,
      stock_on_hand: 0.0,
      stock_on_hand_formatted: "0.00",
      available_stock: 0.0,
      available_stock_formatted: "0.00",
      actual_available_stock: 0.0,
      actual_available_stock_formatted: "0.00",
      purchase_account_id: "536460000000000567",
      inventory_account_id: "536460000000000626",
    },
    {
      mapped_item_id: "536460000018642299",
      item_id: "536460000015075536",
      item_order: 3,
      name: 'Hi Tack Masking Tape (24x20) 1"',
      rate: 35.0,
      rate_formatted: "₹35.00",
      purchase_rate: 35.0,
      purchase_rate_formatted: "₹35.00",
      sku: "HTMSKT3M2430PM",
      status: 1,
      image_name: "",
      image_document_id: "",
      purchase_description: "",
      image_type: "",
      unit: "Roll",
      product_type: "goods",
      is_combo_product: false,
      description: "",
      quantity: 0.01,
      stock_on_hand: 108.0,
      stock_on_hand_formatted: "108.00",
      available_stock: 108.0,
      available_stock_formatted: "108.00",
      actual_available_stock: 108.0,
      actual_available_stock_formatted: "108.00",
      purchase_account_id: "536460000008719734",
      inventory_account_id: "536460000000000626",
    },
    {
      mapped_item_id: "536460000018642301",
      item_id: "536460000014301273",
      item_order: 4,
      name: "S.T Thinner",
      rate: 50.0,
      rate_formatted: "₹50.00",
      purchase_rate: 50.0,
      purchase_rate_formatted: "₹50.00",
      sku: "PTHNSTXXXXXXP1",
      status: 1,
      image_name: "",
      image_document_id: "",
      purchase_description: "",
      image_type: "",
      unit: "Ltr",
      product_type: "goods",
      is_combo_product: false,
      description: "",
      quantity: 0.01,
      stock_on_hand: 200.0,
      stock_on_hand_formatted: "200.00",
      available_stock: 200.0,
      available_stock_formatted: "200.00",
      actual_available_stock: 200.0,
      actual_available_stock_formatted: "200.00",
      purchase_account_id: "536460000008719734",
      inventory_account_id: "536460000000000626",
    },
    {
      mapped_item_id: "536460000018642303",
      item_id: "536460000016035348",
      item_order: 5,
      name: "DHOTI OLD",
      rate: 5.0,
      rate_formatted: "₹5.00",
      purchase_rate: 5.0,
      purchase_rate_formatted: "₹5.00",
      sku: "DHTOLDXXXXXXZZ",
      status: 1,
      image_name: "",
      image_document_id: "",
      purchase_description: "",
      image_type: "",
      unit: "Nos",
      product_type: "goods",
      is_combo_product: false,
      description: "",
      quantity: 3.0,
      stock_on_hand: 150.0,
      stock_on_hand_formatted: "150.00",
      available_stock: 150.0,
      available_stock_formatted: "150.00",
      actual_available_stock: 150.0,
      actual_available_stock_formatted: "150.00",
      purchase_account_id: "536460000000000567",
      inventory_account_id: "536460000000000626",
    },
    {
      mapped_item_id: "536460000018642305",
      item_id: "536460000016035377",
      item_order: 6,
      name: "DHOTI WHITE",
      rate: 8.5,
      rate_formatted: "₹8.50",
      purchase_rate: 8.5,
      purchase_rate_formatted: "₹8.50",
      sku: "DHTWTHXXXXXXZZ",
      status: 1,
      image_name: "",
      image_document_id: "",
      purchase_description: "",
      image_type: "",
      unit: "Nos",
      product_type: "goods",
      is_combo_product: false,
      description: "",
      quantity: 1.0,
      stock_on_hand: 372.0,
      stock_on_hand_formatted: "372.00",
      available_stock: 372.0,
      available_stock_formatted: "372.00",
      actual_available_stock: 372.0,
      actual_available_stock_formatted: "372.00",
      purchase_account_id: "536460000000000567",
      inventory_account_id: "536460000000000626",
    },
    {
      mapped_item_id: "536460000018642307",
      item_id: "536460000013086527",
      item_order: 7,
      name: "Emery Paper 100 No",
      rate: 17.2,
      rate_formatted: "₹17.20",
      purchase_rate: 17.2,
      purchase_rate_formatted: "₹17.20",
      sku: "EPSCRG3M0100SP",
      status: 1,
      image_name: "",
      image_document_id: "",
      purchase_description: "",
      image_type: "",
      unit: "Nos",
      product_type: "goods",
      is_combo_product: false,
      description: "",
      quantity: 2.0,
      stock_on_hand: 200.0,
      stock_on_hand_formatted: "200.00",
      available_stock: 200.0,
      available_stock_formatted: "200.00",
      actual_available_stock: 200.0,
      actual_available_stock_formatted: "200.00",
      purchase_account_id: "536460000008719734",
      inventory_account_id: "536460000000000626",
    },
  ],
  composite_service_items: [],
  warehouses: [
    {
      warehouse_id: "536460000000014524",
      warehouse_name: "Main Store",
      is_primary: true,
      status: "active",
      status_formatted: "Active",
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
    },
    {
      warehouse_id: "536460000000014553",
      warehouse_name: "Mechanical",
      is_primary: false,
      status: "active",
      status_formatted: "Active",
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
    },
    {
      warehouse_id: "536460000000014557",
      warehouse_name: "Finished Goods Store",
      is_primary: false,
      status: "active",
      status_formatted: "Active",
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
    },
    {
      warehouse_id: "536460000001457059",
      warehouse_name: "IHV",
      is_primary: false,
      status: "active",
      status_formatted: "Active",
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
    },
    {
      warehouse_id: "536460000015944005",
      warehouse_name: "PCB",
      is_primary: false,
      status: "active",
      status_formatted: "Active",
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
    },
    {
      warehouse_id: "536460000015951001",
      warehouse_name: "TRM",
      is_primary: false,
      status: "active",
      status_formatted: "Active",
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
    },
    {
      warehouse_id: "536460000015957997",
      warehouse_name: "Paint",
      is_primary: false,
      status: "active",
      status_formatted: "Active",
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
    },
    {
      warehouse_id: "536460000015964993",
      warehouse_name: "TTD",
      is_primary: false,
      status: "active",
      status_formatted: "Active",
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
    },
    {
      warehouse_id: "536460000015971989",
      warehouse_name: "PHV",
      is_primary: false,
      status: "active",
      status_formatted: "Active",
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
    },
    {
      warehouse_id: "536460000015978985",
      warehouse_name: "Packing & Dipatch",
      is_primary: false,
      status: "active",
      status_formatted: "Active",
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
    },
  ],
  preferred_vendors: [],
  comments: [
    {
      comment_id: "536460000018643102",
      description: "updated by",
      commented_by_id: "536460000016028568",
      commented_by: "Mechanical Department",
      comment_type: "system",
      date: "2022-11-15",
      date_formatted: "15/11/2022 04:56 PM",
      date_description: "159 days ago",
      time: "4:56 PM",
      operation_type: "Updated",
    },
    {
      comment_id: "536460000018643098",
      description: "updated by",
      commented_by_id: "536460000016028568",
      commented_by: "Mechanical Department",
      comment_type: "system",
      date: "2022-11-15",
      date_formatted: "15/11/2022 04:56 PM",
      date_description: "159 days ago",
      time: "4:56 PM",
      operation_type: "Updated",
    },
    {
      comment_id: "536460000018642311",
      description: "created by",
      commented_by_id: "536460000016028568",
      commented_by: "Mechanical Department",
      comment_type: "system",
      date: "2022-11-15",
      date_formatted: "15/11/2022 04:45 PM",
      date_description: "159 days ago",
      time: "4:45 PM",
      operation_type: "Added",
    },
  ],
};
