contact = {
  contact_id: "536460000000031670",
  contact_name: "3M INDIA LIMITED",
  company_name: "3M INDIA LIMITED",
  first_name: "",
  last_name: "",
  designation: "",
  department: "",
  website: "",
  is_bcy_only_contact: true,
  is_credit_limit_migration_completed: false,
  language_code: "en",
  language_code_formatted: "English",
  contact_salutation: "",
  email: "",
  phone: "",
  mobile: "",
  portal_status: "disabled",
  is_client_review_asked: false,
  has_transaction: true,
  contact_type: "customer",
  customer_sub_type: "business",
  customer_sub_type_formatted: "Business",
  owner_id: "",
  owner_name: "",
  source: "csv",
  source_formatted: "CSV",
  documents: [],
  twitter: "",
  facebook: "",
  is_crm_customer: true,
  is_linked_with_zohocrm: true,
  is_gapps_customer: false,
  primary_contact_id: "",
  zcrm_account_id: "203249000000241052",
  zcrm_contact_id: "",
  crm_owner_id: "203249000000172001",
  payment_terms: 0,
  payment_terms_label: "Due on Receipt",
  credit_limit_exceeded_amount: 0.0,
  credit_limit_exceeded_amount_formatted: "₹0.00",
  currency_id: "536460000000000064",
  currency_code: "INR",
  currency_symbol: "₹",
  price_precision: 2,
  exchange_rate: 1.0,
  can_show_customer_ob: false,
  can_show_customer_ob_formatted: false,
  can_show_vendor_ob: false,
  can_show_vendor_ob_formatted: false,
  opening_balance_amount: 1767000.0,
  opening_balance_amount_formatted: "₹17,67,000.00",
  opening_balance_amount_bcy: 1767000.0,
  opening_balance_amount_bcy_formatted: "₹17,67,000.00",
  outstanding_ob_receivable_amount: 1767000.0,
  outstanding_ob_receivable_amount_formatted: "₹17,67,000.00",
  outstanding_ob_payable_amount: 0.0,
  outstanding_ob_payable_amount_formatted: "₹0.00",
  outstanding_receivable_amount: 1767000.0,
  outstanding_receivable_amount_formatted: "₹17,67,000.00",
  outstanding_receivable_amount_bcy: 1767000.0,
  outstanding_receivable_amount_bcy_formatted: "₹17,67,000.00",
  outstanding_payable_amount: 0.0,
  outstanding_payable_amount_formatted: "₹0.00",
  outstanding_payable_amount_bcy: 0.0,
  outstanding_payable_amount_bcy_formatted: "₹0.00",
  unused_credits_receivable_amount: 0.0,
  unused_credits_receivable_amount_formatted: "₹0.00",
  unused_credits_receivable_amount_bcy: 0.0,
  unused_credits_receivable_amount_bcy_formatted: "₹0.00",
  unused_credits_payable_amount: 0.0,
  unused_credits_payable_amount_formatted: "₹0.00",
  unused_credits_payable_amount_bcy: 0.0,
  unused_credits_payable_amount_bcy_formatted: "₹0.00",
  unused_retainer_payments: 0.0,
  unused_retainer_payments_formatted: "₹0.00",
  status: "active",
  payment_reminder_enabled: true,
  is_sms_enabled: true,
  is_portal_enabled: false,
  is_consent_agreed: false,
  consent_date: "",
  is_client_review_settings_enabled: false,
  custom_fields: [],
  custom_field_hash: {},
  is_taxable: true,
  tax_id: "536460000000021131",
  tds_tax_id: "",
  tax_name: "IGST18",
  tax_name_formatted: "IGST18 [18%]",
  tax_percentage: 18.0,
  country_code: "",
  country_code_formatted: "",
  place_of_contact: "KA",
  place_of_contact_formatted: "Karnataka",
  gst_no: "29AAACB5724H1ZQ",
  pan_no: "AAACB5724H",
  trader_name: "",
  legal_name: "",
  vat_reg_no: "",
  tax_treatment: "business_gst",
  tax_treatment_formatted: "Registered Business - Regular",
  tax_reg_no: "",
  contact_category: "business_gst",
  contact_category_formatted: "Registered Business - Regular",
  gst_treatment: "business_gst",
  gst_treatment_formatted: "Registered Business - Regular",
  is_linked_with_contact: false,
  sales_channel: "direct_sales",
  ach_supported: false,
  portal_receipt_count: 0,
  opening_balances: [
    {
      opening_balance_amount: 1767000.0,
      opening_balance_amount_formatted: "₹17,67,000.00",
      opening_balance_amount_bcy: 1767000.0,
      opening_balance_amount_bcy_formatted: "₹17,67,000.00",
      exchange_rate: 1.0,
    },
  ],
  parent_customer: { customer_id: "", customer_name: "", email: "" },
  is_child_present: false,
  has_parent: false,
  allow_parent_for_payment_and_view: false,
  tax_info_list: [
    {
      tax_info_id: "536460000000031672",
      tax_registration_no: "29AAACB5724H1ZQ",
      place_of_supply: "KA",
      place_of_supply_formatted: "Karnataka",
      is_primary: true,
      trader_name: "",
      legal_name: "",
    },
  ],
  billing_address: {
    address_id: "536460000000031674",
    attention: "",
    address: "",
    street2: "",
    city: "",
    state_code: "",
    state: "KARNATAKA",
    zip: "",
    country: "INDIA",
    country_code: "IN",
    phone: "",
    phone_formatted: "",
    fax: "",
  },
  shipping_address: {
    address_id: "536460000000031677",
    attention: "",
    address: "",
    street2: "",
    city: "",
    state_code: "",
    state: "",
    zip: "",
    country: "",
    country_code: "",
    phone: "",
    phone_formatted: "",
    fax: "",
    latitude: "",
    longitude: "",
    is_shipping_address_verified: false,
    is_verifiable: false,
    is_valid: false,
  },
  contact_persons: [],
  comments: [
    {
      comment_id: "536460000000671743",
      description: "Contact updated with Zoho CRM details",
      commented_by_id: "",
      commented_by: "Zoho Inventory",
      date: "2021-06-03",
      date_formatted: "03/06/2021 02:21 PM",
      date_with_time: "2021-06-03T14:21:49+0530",
      date_description: "about a year ago",
      time: "2:21 PM",
      transaction_id: "",
      transaction_type: "",
      is_entity_deleted: false,
      operation_type: "updated",
      sentiment: "none",
    },
    {
      comment_id: "536460000000313115",
      description: "Contact updated with Zoho CRM details",
      commented_by_id: "",
      commented_by: "Zoho Inventory",
      date: "2021-06-01",
      date_formatted: "01/06/2021 04:38 PM",
      date_with_time: "2021-06-01T16:38:40+0530",
      date_description: "about a year ago",
      time: "4:38 PM",
      transaction_id: "",
      transaction_type: "",
      is_entity_deleted: false,
      operation_type: "updated",
      sentiment: "none",
    },
    {
      comment_id: "536460000000234633",
      description: "Contact updated with Zoho CRM details",
      commented_by_id: "",
      commented_by: "Zoho Inventory",
      date: "2021-06-01",
      date_formatted: "01/06/2021 12:35 PM",
      date_with_time: "2021-06-01T12:35:09+0530",
      date_description: "about a year ago",
      time: "12:35 PM",
      transaction_id: "",
      transaction_type: "",
      is_entity_deleted: false,
      operation_type: "updated",
      sentiment: "none",
    },
    {
      comment_id: "536460000000234487",
      description: "Contact updated with Zoho CRM details",
      commented_by_id: "",
      commented_by: "Zoho Inventory",
      date: "2021-06-01",
      date_formatted: "01/06/2021 12:29 PM",
      date_with_time: "2021-06-01T12:29:16+0530",
      date_description: "about a year ago",
      time: "12:29 PM",
      transaction_id: "",
      transaction_type: "",
      is_entity_deleted: false,
      operation_type: "updated",
      sentiment: "none",
    },
    {
      comment_id: "536460000000208187",
      description: "Contact updated with Zoho CRM details",
      commented_by_id: "",
      commented_by: "Zoho Inventory",
      date: "2021-05-26",
      date_formatted: "26/05/2021 11:28 AM",
      date_with_time: "2021-05-26T11:28:27+0530",
      date_description: "about a year ago",
      time: "11:28 AM",
      transaction_id: "",
      transaction_type: "",
      is_entity_deleted: false,
      operation_type: "updated",
      sentiment: "none",
    },
    {
      comment_id: "536460000000206429",
      description: "Contact updated with Zoho CRM details",
      commented_by_id: "",
      commented_by: "Zoho Inventory",
      date: "2021-05-25",
      date_formatted: "25/05/2021 06:08 PM",
      date_with_time: "2021-05-25T18:08:00+0530",
      date_description: "about a year ago",
      time: "6:08 PM",
      transaction_id: "",
      transaction_type: "",
      is_entity_deleted: false,
      operation_type: "updated",
      sentiment: "none",
    },
    {
      comment_id: "536460000000065118",
      description: "Contact updated with Zoho CRM details",
      commented_by_id: "",
      commented_by: "Zoho Inventory",
      date: "2021-05-07",
      date_formatted: "07/05/2021 05:29 PM",
      date_with_time: "2021-05-07T17:29:52+0530",
      date_description: "about a year ago",
      time: "5:29 PM",
      transaction_id: "",
      transaction_type: "",
      is_entity_deleted: false,
      operation_type: "updated",
      sentiment: "none",
    },
    {
      comment_id: "536460000000049170",
      description: "Contact updated with Zoho CRM details",
      commented_by_id: "",
      commented_by: "Zoho Inventory",
      date: "2021-04-27",
      date_formatted: "27/04/2021 10:22 PM",
      date_with_time: "2021-04-27T22:22:57+0530",
      date_description: "about a year ago",
      time: "10:22 PM",
      transaction_id: "",
      transaction_type: "",
      is_entity_deleted: false,
      operation_type: "updated",
      sentiment: "none",
    },
    {
      comment_id: "536460000000045190",
      description: "Contact pushed to Zoho CRM",
      commented_by_id: "",
      commented_by: "Zoho Inventory",
      date: "2021-04-27",
      date_formatted: "27/04/2021 08:18 PM",
      date_with_time: "2021-04-27T20:18:28+0530",
      date_description: "about a year ago",
      time: "8:18 PM",
      transaction_id: "",
      transaction_type: "",
      is_entity_deleted: false,
      operation_type: "updated",
      sentiment: "none",
    },
    {
      comment_id: "536460000000032030",
      description: "Contact updated",
      commented_by_id: "536460000000017005",
      commented_by: "Accounts",
      date: "2021-04-13",
      date_formatted: "13/04/2021 03:30 PM",
      date_with_time: "2021-04-13T15:30:18+0530",
      date_description: "2 years ago",
      time: "3:30 PM",
      transaction_id: "",
      transaction_type: "",
      is_entity_deleted: false,
      operation_type: "updated",
      sentiment: "none",
    },
    {
      comment_id: "536460000000031686",
      description:
        "Contact created with GST Treatment 'Registered Business - Regular' & GSTIN '29AAACB5724H1ZQ'. State updated to KA.",
      commented_by_id: "536460000000017005",
      commented_by: "Accounts",
      date: "2021-04-13",
      date_formatted: "13/04/2021 03:29 PM",
      date_with_time: "2021-04-13T15:29:42+0530",
      date_description: "2 years ago",
      time: "3:29 PM",
      transaction_id: "",
      transaction_type: "",
      is_entity_deleted: false,
      operation_type: "added",
      sentiment: "none",
    },
  ],
  addresses: [],
  pricebook_id: "",
  pricebook_name: "",
  default_templates: {
    invoice_template_id: "",
    invoice_template_name: "",
    bill_template_id: "",
    bill_template_name: "",
    estimate_template_id: "",
    estimate_template_name: "",
    creditnote_template_id: "",
    creditnote_template_name: "",
    purchaseorder_template_id: "",
    purchaseorder_template_name: "",
    salesorder_template_id: "",
    salesorder_template_name: "",
    retainerinvoice_template_id: "",
    retainerinvoice_template_name: "",
    paymentthankyou_template_id: "",
    paymentthankyou_template_name: "",
    retainerinvoice_paymentthankyou_template_id: "",
    retainerinvoice_paymentthankyou_template_name: "",
    invoice_email_template_id: "",
    invoice_email_template_name: "",
    estimate_email_template_id: "",
    estimate_email_template_name: "",
    creditnote_email_template_id: "",
    creditnote_email_template_name: "",
    purchaseorder_email_template_id: "",
    purchaseorder_email_template_name: "",
    salesorder_email_template_id: "",
    salesorder_email_template_name: "",
    retainerinvoice_email_template_id: "",
    retainerinvoice_email_template_name: "",
    paymentthankyou_email_template_id: "",
    paymentthankyou_email_template_name: "",
    payment_remittance_email_template_id: "",
    payment_remittance_email_template_name: "",
    retainerinvoice_paymentthankyou_email_template_id: "",
    retainerinvoice_paymentthankyou_email_template_name: "",
  },
  associated_with_square: false,
  can_add_card: false,
  can_add_bank_account: false,
  cards: [],
  checks: [],
  bank_accounts: [],
  vpa_list: [],
  notes: "",
  created_time: "2021-04-13T15:29:42+0530",
  created_date: "13/04/2021",
  created_date_formatted: "13/04/2021",
  created_by_name: "Accounts",
  last_modified_time: "2021-06-03T14:21:49+0530",
  tags: [],
  zohopeople_client_id: "",
  customer_currency_summaries: [
    {
      currency_id: "536460000000000064",
      currency_code: "INR",
      currency_symbol: "₹",
      price_precision: 2,
      is_base_currency: true,
      currency_name_formatted: "INR- Indian Rupee",
      outstanding_receivable_amount: 1767000.0,
      outstanding_receivable_amount_formatted: "₹17,67,000.00",
      unused_credits_receivable_amount: 0.0,
      unused_credits_receivable_amount_formatted: "₹0.00",
    },
  ],
};
