inventory_adjustment = {
  inventory_adjustment_id: "536460000020308019",
  date: "2023-04-06",
  date_formatted: "06/04/2023",
  adjustment_account_id: "536460000000000567",
  adjustment_account_name: "Cost of Goods Sold",
  reason: "Inventory Revaluation",
  reason_id: "536460000000014018",
  description: "",
  status: "adjusted",
  status_formatted: "Adjusted",
  reference_number: "",
  documents: [],
  adjustment_type: "quantity",
  adjustment_type_formatted: "Quantity",
  line_items: [
    {
      line_item_id: "536460000020308021",
      item_id: "536460000016366346",
      item_order: 1,
      name: "Monolitic Pilot Light230VAC, Red-Illuminated, ? 22 mm, XB7EV04MPN",
      sku: "PLMSE230RD22P1",
      description: "",
      is_combo_product: false,
      adjustment_account_id: "536460000000000567",
      adjustment_account_name: "Cost of Goods Sold",
      asset_account_id: "536460000000000626",
      asset_account_name: "Inventory Asset",
      quantity_adjusted: -4.0,
      quantity_adjusted_formatted: -4.0,
      unit: "Nos",
      image_name: "",
      image_document_id: "",
      serial_numbers: [],
      batches: [],
      warehouse_id: "536460000000014524",
      warehouse_name: "Main Store",
      tags: [],
    },
    {
      line_item_id: "536460000020308023",
      item_id: "536460000011809992",
      item_order: 2,
      name: "Round Pilot Light230VAC,Green-Illuminated,? 22 mm,XB7EV03MPN",
      sku: "PLRSE230GD22P1",
      description: "",
      is_combo_product: false,
      adjustment_account_id: "536460000000000567",
      adjustment_account_name: "Cost of Goods Sold",
      asset_account_id: "536460000000000626",
      asset_account_name: "Inventory Asset",
      quantity_adjusted: -4.0,
      quantity_adjusted_formatted: -4.0,
      unit: "Nos",
      image_name: "",
      image_document_id: "",
      serial_numbers: [],
      batches: [],
      warehouse_id: "536460000000014524",
      warehouse_name: "Main Store",
      tags: [],
    },
  ],
  comments: [
    {
      comment_id: "536460000020308045",
      description: "Inventory Adjustment approved.",
      commented_by_id: "536460000000087007",
      commented_by: "Store",
      comment_type: "system",
      date: "2023-04-06",
      date_formatted: "06/04/2023 09:21 AM",
      date_description: "18 days ago",
      time: "9:21 AM",
      operation_type: "Updated",
    },
    {
      comment_id: "536460000020308041",
      description: "Inventory Adjustment submitted for approval.",
      commented_by_id: "536460000000087007",
      commented_by: "Store",
      comment_type: "system",
      date: "2023-04-06",
      date_formatted: "06/04/2023 09:21 AM",
      date_description: "18 days ago",
      time: "9:21 AM",
      operation_type: "Updated",
    },
    {
      comment_id: "536460000020308035",
      description: "Inventory Adjustment created.",
      commented_by_id: "536460000000087007",
      commented_by: "Store",
      comment_type: "system",
      date: "2023-04-06",
      date_formatted: "06/04/2023 09:21 AM",
      date_description: "18 days ago",
      time: "9:21 AM",
      operation_type: "Added",
    },
  ],
  total: 0.0,
  total_formatted: "₹0.00",
  warehouse_id: "536460000000014524",
  warehouse_name: "Main Store",
  created_time: "2023-04-06T09:21:00+0530",
  created_time_formatted: "06/04/2023 09:21 AM",
  last_modified_time: "2023-04-06T09:21:01+0530",
  last_modified_time_formatted: "06/04/2023 09:21 AM",
  created_by_id: "536460000000087007",
  last_modified_by_id: "536460000000087007",
  created_by_name: "Store",
  custom_fields: [],
  custom_field_hash: {},
  html_string:
    '<!--The below style_start tag has to be present as it is used to substring the style content from the body html-->\n\n<!--style_start-->\n<style type="text/css" media="all">\n \t\n\n  @font-face {\n    font-family: \'WebFont-\';\n    src: local(), url();\n  }\n\n  .pcs-template {\n  \tfont-family: Open Sans, \'WebFont-\';\n    font-size: 9pt;\n    color: #333333;\n      background:  #ffffff ;\n  }\n\n  .pcs-header-content {\n    font-size: 9pt;\n\tcolor: #333333;\n\tbackground-color: #ffffff;\n  }\n  .pcs-template-body {\n  \tpadding: 0 0.400000in 0 0.550000in;\n  }\n  .pcs-template-footer {\n  \theight: 0.700000in;\n\tfont-size: 6pt;\n\tcolor: #aaaaaa;\n\tpadding: 0 0.400000in 0 0.550000in;\n\tbackground-color: #ffffff;\n  }\n  .pcs-footer-content {\n  word-wrap: break-word;\n  color: #aaaaaa;\n      border-top: 1px solid #adadad;\n  }\n\n  .pcs-label {\n    color: #333333;\n  }\n  .pcs-entity-title {\n    font-size: 28pt;\n    color: #000000;\n  }\n  .pcs-orgname {\n    font-size: 10pt;\n    color: #333333;\n  }\n  .pcs-customer-name {\n    font-size: 9pt;\n    color: #333333;\n  }\n  .pcs-eori-number {\n    color: #333;\n    margin: 0;\n    padding-top: 10px;\n  }\n .pcs-itemtable-header {\n    font-size: 9pt;\n    color: #ffffff;\n    background-color: #3c3d3a;\n  }\n  .pcs-itemtable-breakword {\n    word-wrap: break-word;\n  }\n  .pcs-taxtable-header {\n    font-size: 9pt;\n    color: #ffffff;\n    background-color: #3c3d3a;\n  }\n  .breakrow-inside {\n    page-break-inside: avoid;\n  }\n  .breakrow-after {\n    page-break-after:auto;\n  }\n  .pcs-item-row {\n    font-size: 9pt;\n    border-bottom: 1px solid #adadad;\n    background-color: #ffffff;\n    color: #000000;\n  }\n  .pcs-img-fit-aspectratio {\n    object-fit: contain;\n    object-position: top;\n  }\n  .pcs-img-border {\n    border: 1px solid #f5f4f3;\n  }\n  .pcs-item-sku, .pcs-item-hsn, .pcs-item-coupon, .pcs-item-serialnumber, .pcs-item-unitcode {\n    margin-top: 2px;\n  \tfont-size: 10px;\n  \tcolor: #444444;\n  }\n  .pcs-item-desc {\n      color: #727272;\n      font-size: 9pt;\n   }\n  .pcs-balance {\n    background-color: #f5f4f3;\n    font-size: 9pt;\n    color: #000000;\n  }\n  .pcs-savings {\n  font-size: 0pt;\n  color: ;\n  background-color: ;\n  }\n  .pcs-totals {\n    font-size: 9pt;\n    color: #000000;\n    background-color: #ffffff;\n  }\n  .pcs-notes {\n    font-size: 8pt;\n  }\n  .pcs-terms {\n    font-size: 8pt;\n  }\n  .pcs-header-first {\n\tbackground-color: #ffffff;\n\tfont-size: 9pt;\n\tcolor: #333333;\n      height: auto;\n\t}\n\n .pcs-status {\n \tcolor: ;\n\tfont-size: 15pt;\n\tborder: 3px solid ;\n\tpadding: 3px 8px;\n }\n .billto-section {\n     padding-top: mm;\n     padding-left: mm;\n   }\n   .shipto-section {\n     padding-top: mm;\n     padding-left: mm;\n   }\n\n @page :first {\n \t@top-center {\n\t\tcontent: element(header);\n\t}\n    margin-top: 0.700000in;\n  }\n\n  .pcs-template-header {\n\tpadding: 0 0.400000in 0 0.550000in;\n    height: 0.700000in;\n  }\n\n  .pcs-template-fill-emptydiv {\n    display: table-cell;\n    content: " ";\n    width: 100%;\n  }\n\n\n/* Additional styles for RTL compat */\n\n/* Helper Classes */\n\n.inline {\n  display: inline-block;\n}\n.v-top {\n  vertical-align: top;\n}\n.text-align-right {\n  text-align: right;\n}\n.rtl .text-align-right {\n  text-align: left;\n}\n.text-align-left {\n  text-align: left;\n}\n.rtl .text-align-left {\n  text-align: right;\n}\n.float-section-right {\n  float: right;\n}\n.rtl .float-section-right{\n  float: left;\n}\n.float-section-left {\n  float: left;\n}\n.rtl .float-section-left{\n  float: right;\n}\n\n/* Helper Classes End */\n\n.item-details-inline {\n  display: inline-block;\n  margin: 0 10px;\n  vertical-align: top;\n  max-width: 70%;\n}\n\n.total-in-words-container {\n  width: 100%;\n  margin-top: 10px;\n}\n.total-in-words-label {\n  vertical-align: top;\n  padding: 0 10px;\n}\n.total-in-words-value {\n  width: 170px;\n}\n.total-section-label {\n  padding: 5px 10px 5px 0;\n  vertical-align: middle;\n}\n.total-section-value {\n  width: 120px;\n  vertical-align: middle;\n  padding: 10px 10px 10px 5px;\n}\n.rtl .total-section-value {\n  padding: 10px 5px 10px 10px;\n}\n\n.tax-summary-description {\n  color: #727272;\n  font-size: 8pt;\n}\n\n.bharatqr-bg {\n  background-color: #f4f3f8;\n}\n\n/* Overrides/Patches for RTL compat */\n  .rtl th {\n    text-align: inherit; /* Specifically setting th as inherit for supporting RTL */\n  }\n/* Overrides/Patches End */\n\n\n/* Subject field styles */\n.subject-block {\n    margin-top: 20px;\n}\n.subject-block-value {\n    word-wrap: break-word;\n    white-space: pre-wrap;\n    line-height: 14pt;\n    margin-top:5px;\n}\n/* Subject field styles End*/\n\n.pcs-sub-label {\n  color: #666;\n  font-size: 10px;\n}\n.pcs-hsnsummary-compact {\n  padding: 0;\n  margin-top: 3px;\n}\n.pcs-hsnsummary-label-compact {\n  margin-bottom: 3px;\n  font-weight:600;\n  padding-left: 3px;\n  font-size: 9pt;\n}\n.pcs-hsnsummary-header-compact {\n  text-align:right;\n  padding: 5px 7px 2px 7px;\n  word-wrap: break-word;\n  width: 17%;\n  height: 32px;\n  border-right: 1px solid #9E9E9E;\n  font-size: 8pt;\n  font-weight: 600;\n}\n.pcs-hsnsummary-body-compact, .pcs-hsnsummary-total-compact {\n  text-align:right;\n  word-wrap: break-word;\n  font-size: 7pt;\n  padding: 4px 10px;\n}\n.pcs-hsnsummary-total-compact {\n  border-top: 1px solid #adadad;\n}\n.pcs-ukvat-summary {\n  margin-top:50px;\n  clear: both;\n  width: 100%;\n}\n.pcs-ukvat-summary-header {\n  padding:5px 10px 5px 5px;\n}\n.pcs-ukvat-summary-header:first-child {\n  padding-left: 10px;\n}\n.pcs-ukvat-summary-label {\n  font-size: 10pt;\n}\n.pcs-ukvat-summary-table {\n  margin-top: 10px;\n  width: 100%;\n  table-layout: fixed;\n}\n.pcs-ukvat-summary-body, .pcs-ukvat-summary-total {\n  padding: 10px 10px 5px 10px;\n}\n.pcs-ukvat-summary-body:first-child {\n  padding-bottom: 10px;\n  padding-right: 0;\n}\n.pcs-payment-block {\n  margin-top: 20px;\n}\n.pcs-payment-block-inner {\n  margin-top: 10px;\n}\n\n.pcs-entity-label-section {\n  padding:5px 10px 5px 0px;\n  font-size: 10pt;\n }\n\n.pcs-colon {\n  width: 3%;\n}\n\n\n    \n\n\n.pcs-w-100 {\n  width: 100%;\n}\n\n\n\n\n\n\n\n.pcs-d-table-cell {\n  display: table-cell;\n}\n\n\n\n\n\n.pcs-talign-center {\n  text-align: center;\n}\n.pcs-wordwrap-bw {\n  word-wrap: break-word;\n}\n.pcs-whitespace-pw {\n  white-space: pre-wrap;\n}\n.pcs-fw-600 {\n  font-weight: 600;\n}\n.pcs-text-uppercase {\n  text-transform: uppercase;\n}\n\n\n\n\n\n.pcs-table-fixed {\n  table-layout:fixed;\n}\n\n\n\n\n\n.pcs-valign-middle {\n  vertical-align: middle;\n}\n\n\n\n.pcs-clearfix {\n  clear: both;\n}\n \t.pcs-lineitem-column {\n        padding: 10px 10px 5px 10px;\n        word-wrap: break-word;\n         vertical-align: top;\n      }\n  .pcs-details-label {\n    text-align: right;\n    padding: 3px 10px 3px 0px;\n  }\n  .pcs-lineitem-row {\n    padding: 10px 10px 5px 10px;\n    word-wrap: break-word;\n  }\n  .pcs-details-value {\n    font-weight: 600;\n  }\n\n  .pcs-notes {\n    margin-top: 5px;\n    word-wrap: break-word;\n    white-space: pre-wrap;\n  }\n</style>\n\n        <!--style_end-->\n\n<div class="pcs-template">\n  <div id="header" class="pcs-template-header pcs-header-content" >\n    \n\n    \n    <div class="pcs-template-fill-emptydiv"></div>\n\n  </div>\n\n<div class="pcs-template-body ">\n    <table style="width:100%;table-layout:fixed;">\n        <tbody>\n        <tr>\n            <td style="vertical-align: top; width:50%;" class="text-align-right">\n                <span class="pcs-entity-title">INVENTORY ADJUSTMENT</span><br />\n            </td>\n        </tr>\n        </tbody>\n    </table>\n\n\n    <table style="width:100%;table-layout:fixed;">\n        <tbody>\n        <tr>\n            <td style="width:35%;vertical-align:top;word-wrap: break-word;">\n                <div style="margin-bottom: 20px;">\n                    <b></b><br/>\n<span class="pcs-label">\n                                        \t\t\t\n                                        \t\t\t</span>                </div>\n            </td>\n            <td style="vertical-align:top;width: 35%;">\n                <table cellpadding="0" cellspacing="0" border="0" style="width: 100%;text-align: right;table-layout: fixed;word-wrap: break-word;">\n                    <tbody>\n                    <tr>\n                        <td class="pcs-details-label pcs-label">\n                            Date\n                        </td>\n                        <td class="pcs-details-value">\n                            06/04/2023\n                        </td>\n                    </tr>\n                    <tr>\n                        <td class="pcs-details-label pcs-label">\n                            Reason\n                        </td>\n                        <td class="pcs-details-value">\n                            Inventory Revaluation\n                        </td>\n                    </tr>\n                    <tr>\n                        <td class="pcs-details-label pcs-label">\n                            Account\n                        </td>\n                        <td class="pcs-details-value">\n                            Cost of Goods Sold\n                        </td>\n                    </tr>\n                    <tr>\n                        <td class="pcs-details-label pcs-label">\n                            Adjustment Type\n                        </td>\n                        <td class="pcs-details-value">\n                            Quantity\n                        </td>\n                    </tr>\n                    <tr>\n                        <td class="pcs-details-label pcs-label">\n                            Created By\n                        </td>\n                        <td class="pcs-details-value">\n                            Store\n                        </td>\n                    </tr>\n\n                    </tbody>\n                </table>\n            </td>\n        </tr>\n        </tbody>\n    </table>\n    <table cellpadding="0" cellspacing="0" border="0" class="pcs-itemtable" style="width:100%;margin-top:20px;table-layout:fixed;">\n    <thead>\n    <tr>\n            <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 0px 5px 5px;width: 5%;text-align: center;">\n      #\n    </td>\n    <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 10px 5px 20px;width: ;text-align: left;">\n      Item &amp; Description\n    </td>\n    <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 10px 5px 5px;width: 17%;text-align: right;">\n      Quantity Adjusted\n    </td>\n    <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 10px 5px 5px;width: 15%;text-align: right;">\n      Cost Price\n    </td>\n\n    </tr>\n    </thead>\n    <tbody class="itemBody">\n    <tr class="breakrow-inside breakrow-after">\n    <td class="pcs-item-row" style="padding: 10px 0 10px 5px;text-align: center;word-wrap: break-word;" valign="top" rowspan="1">\n        1\n    </td>\n    <td class="pcs-item-row" style="padding: 10px 0px 10px 30px;" valign="top" rowspan="1">\n    <div >\n    <div >\n    <span id="tmp_item_name" style="word-wrap: break-word;">Monolitic Pilot Light230VAC, Red-Illuminated, ? 22 mm, XB7EV04MPN</span><br />\n    \n    \n</div>\n</div>\n        </td>\n<td class="pcs-item-row pcs-lineitem-row" style="text-align:right;" valign="top" rowspan="1">\n<span id="tmp_item_qty">-4.00</span>\n<div class="pcs-item-desc">Nos</div>\n</td>\n<td class="pcs-item-row pcs-lineitem-row" style="text-align:right;" valign="top" rowspan="1">\n<span id="tmp_item_qty"></span>\n</td>\n        </tr>\n    <tr class="breakrow-inside breakrow-after">\n    <td class="pcs-item-row" style="padding: 10px 0 10px 5px;text-align: center;word-wrap: break-word;" valign="top" rowspan="1">\n        2\n    </td>\n    <td class="pcs-item-row" style="padding: 10px 0px 10px 30px;" valign="top" rowspan="1">\n    <div >\n    <div >\n    <span id="tmp_item_name" style="word-wrap: break-word;">Round Pilot Light230VAC,Green-Illuminated,? 22 mm,XB7EV03MPN</span><br />\n    \n    \n</div>\n</div>\n        </td>\n<td class="pcs-item-row pcs-lineitem-row" style="text-align:right;" valign="top" rowspan="1">\n<span id="tmp_item_qty">-4.00</span>\n<div class="pcs-item-desc">Nos</div>\n</td>\n<td class="pcs-item-row pcs-lineitem-row" style="text-align:right;" valign="top" rowspan="1">\n<span id="tmp_item_qty"></span>\n</td>\n        </tr>\n        </tbody>\n        </table>\n        </div>\n          <div class="pcs-template-footer">\n    <div >\n      \n    </div>  \n  </div>\n\n        </div>',
};
