payment = {
  payment_id: "536460000019866207",
  payment_number: "128",
  payment_link_id: "",
  created_time: "2023-03-10T17:35:40+0530",
  updated_time: "2023-03-10T17:35:40+0530",
  payment_number_prefix: "",
  payment_number_suffix: "128",
  documents: [],
  customer_id: "536460000003280147",
  customer_name: "Virginia Transformer Corporation",
  is_child_present: false,
  is_portal_enabled: false,
  payment_mode: "Bank Transfer",
  card_type: "",
  card_type_formatted: "",
  date: "2023-03-09",
  date_formatted: "09/03/2023",
  offline_created_date_with_time: "",
  offline_created_date_with_time_formatted: "",
  is_pre_gst: false,
  account_id: "536460000016222659",
  account_name: "Bank of Baroda OCC A/c 25620500001781",
  account_type: "bank",
  account_type_formatted: "Bank",
  customer_advance_account_id: "536460000000015133",
  customer_advance_account_name: "Advance From Customers",
  currency_id: "536460000000000064",
  currency_symbol: "₹",
  currency_code: "INR",
  exchange_rate: 1.0,
  exchange_rate_formatted: "₹1.00",
  amount: 8069938.0,
  amount_formatted: "₹80,69,938.00",
  unused_amount: 8069938.0,
  unused_amount_formatted: "₹80,69,938.00",
  bank_charges: 0.0,
  bank_charges_formatted: "₹0.00",
  tax_account_id: "",
  is_client_review_settings_enabled: false,
  place_of_supply: "",
  gst_return_details: {
    status_formatted: "",
    return_period: "",
    status: "",
    return_period_formatted: "",
  },
  gst_treatment: "",
  tax_treatment: "",
  gst_no: "",
  tax_account_name: "",
  tax_amount_withheld: 0.0,
  tax_amount_withheld_formatted: "₹0.00",
  discount_amount: 0.0,
  discount_amount_formatted: "₹0.00",
  description:
    "being 60% balance payment received against supply of Intermediate 3 Phase Step-up Transformer- HVT 69-1750-3T",
  product_description: "",
  reference_number: "",
  online_transaction_id: "",
  payment_gateway: "",
  payment_gateway_formatted: "",
  settlement_status: "",
  settlement_status_formatted: "",
  tax_id: "",
  tax_name: "",
  tax_percentage: "",
  tax_type: "",
  is_advance_payment: false,
  tds_type: "",
  tds_tax_id: "",
  invoices: [],
  payment_refunds: [],
  comments: [
    {
      comment_id: "536460000019866217",
      description: "Payment of ₹80,69,938.00 received",
      commented_by_id: "536460000000024001",
      commented_by: "Girish Kumar",
      date: "2023-03-10",
      date_formatted: "10/03/2023 05:35 PM",
      date_description: "44 days ago",
      time: "5:35 PM",
      operation_type: "Added",
    },
  ],
  last_four_digits: "",
  html_string:
    '\n<!--style_start-->\n<style type="text/css" media="all">\n \n\n  @font-face {\n    font-family: \'WebFont-Ubuntu\';\n    src: local(Ubuntu), url(https://fonts.gstatic.com/s/ubuntu/v10/4iCs6KVjbNBYlgoKcg72nU6AF7xm.woff2);\n  }\n\n  .pcs-template {\n  \tfont-family: Ubuntu, \'WebFont-Ubuntu\';\n    font-size: 11pt;\n    color: #333333;\n      background:  #ffffff ;\n  }\n\n  .pcs-header-content {\n    font-size: 8pt;\n\tcolor: #333333;\n\tbackground-color: #ffffff;\n  }\n  .pcs-template-body {\n  \tpadding: 0 0.400000in 0 0.550000in;\n  }\n  .pcs-template-footer {\n  \theight: 0.700000in;\n\tfont-size: 6pt;\n\tcolor: #aaaaaa;\n\tpadding: 0 0.400000in 0 0.550000in;\n\tbackground-color: #ffffff;\n  }\n  .pcs-footer-content {\n  word-wrap: break-word;\n  color: #aaaaaa;\n      border-top: 1px solid #ece7e7;\n  }\n\n  .pcs-label {\n    color: #777777;\n  }\n  .pcs-entity-title {\n    font-size: 13pt;\n    color: #333333;\n  }\n  .pcs-orgname {\n    font-size: 15pt;\n    color: #333333;\n  }\n  .pcs-customer-name {\n    font-size: 12pt;\n    color: #333333;\n  }\n  .pcs-eori-number {\n    color: #333;\n    margin: 0;\n    padding-top: 10px;\n  }\n .pcs-itemtable-header {\n    font-size: 11pt;\n    color: #333333;\n    background-color: #eff0f1;\n  }\n  .pcs-itemtable-breakword {\n    word-wrap: break-word;\n  }\n  .pcs-taxtable-header {\n    font-size: 11pt;\n    color: #333333;\n    background-color: #eff0f1;\n  }\n  .breakrow-inside {\n    page-break-inside: avoid;\n  }\n  .breakrow-after {\n    page-break-after:auto;\n  }\n  .pcs-item-row {\n    font-size: 11pt;\n    border-bottom: 1px solid #ece7e7;\n    background-color: #ffffff;\n    color: #333333;\n  }\n  .pcs-img-fit-aspectratio {\n    object-fit: contain;\n    object-position: top;\n  }\n  .pcs-img-border {\n    border: 1px solid #f5f4f3;\n  }\n  .pcs-item-sku, .pcs-item-hsn, .pcs-item-coupon, .pcs-item-serialnumber, .pcs-item-unitcode {\n    margin-top: 2px;\n  \tfont-size: 10px;\n  \tcolor: #444444;\n  }\n  .pcs-item-desc {\n      color: #8e8e8e;\n      font-size: 11pt;\n   }\n  .pcs-balance {\n    background-color: #ffffff;\n    font-size: 9pt;\n    color: #333333;\n  }\n  .pcs-savings {\n  font-size: 0pt;\n  color: ;\n  background-color: ;\n  }\n  .pcs-totals {\n    font-size: 16pt;\n    color: #ffffff;\n    background-color: #78ae54;\n  }\n  .pcs-notes {\n    font-size: 9pt;\n  }\n  .pcs-terms {\n    font-size: 9pt;\n  }\n  .pcs-header-first {\n\tbackground-color: #ffffff;\n\tfont-size: 8pt;\n\tcolor: #333333;\n      height: auto;\n\t}\n\n .pcs-status {\n \tcolor: ;\n\tfont-size: 15pt;\n\tborder: 3px solid ;\n\tpadding: 3px 8px;\n }\n .billto-section {\n     padding-top: 0mm;\n     padding-left: 0mm;\n   }\n   .shipto-section {\n     padding-top: 0mm;\n     padding-left: 0mm;\n   }\n\n @page :first {\n \t@top-center {\n\t\tcontent: element(header);\n\t}\n    margin-top: 0.700000in;\n  }\n\n  .pcs-template-header {\n\tpadding: 0 0.400000in 0 0.550000in;\n    height: 0.700000in;\n  }\n\n  .pcs-template-fill-emptydiv {\n    display: table-cell;\n    content: " ";\n    width: 100%;\n  }\n\n\n/* Additional styles for RTL compat */\n\n/* Helper Classes */\n\n.inline {\n  display: inline-block;\n}\n.v-top {\n  vertical-align: top;\n}\n.text-align-right {\n  text-align: right;\n}\n.rtl .text-align-right {\n  text-align: left;\n}\n.text-align-left {\n  text-align: left;\n}\n.rtl .text-align-left {\n  text-align: right;\n}\n.float-section-right {\n  float: right;\n}\n.rtl .float-section-right{\n  float: left;\n}\n.float-section-left {\n  float: left;\n}\n.rtl .float-section-left{\n  float: right;\n}\n\n/* Helper Classes End */\n\n.item-details-inline {\n  display: inline-block;\n  margin: 0 10px;\n  vertical-align: top;\n  max-width: 70%;\n}\n\n.total-in-words-container {\n  width: 100%;\n  margin-top: 10px;\n}\n.total-in-words-label {\n  vertical-align: top;\n  padding: 0 10px;\n}\n.total-in-words-value {\n  width: 170px;\n}\n.total-section-label {\n  padding: 5px 10px 5px 0;\n  vertical-align: middle;\n}\n.total-section-value {\n  width: 120px;\n  vertical-align: middle;\n  padding: 10px 10px 10px 5px;\n}\n.rtl .total-section-value {\n  padding: 10px 5px 10px 10px;\n}\n\n.tax-summary-description {\n  color: #727272;\n  font-size: 8pt;\n}\n\n.bharatqr-bg {\n  background-color: #f4f3f8;\n}\n\n/* Overrides/Patches for RTL compat */\n  .rtl th {\n    text-align: inherit; /* Specifically setting th as inherit for supporting RTL */\n  }\n/* Overrides/Patches End */\n\n  /* Signature styles */\n  .sign-border {\n    width: 200px;\n    border-bottom: 1px solid #000;\n  }\n  .sign-label {\n    display: table-cell;\n    font-size: 10pt;\n    padding-right: 5px;\n  }\n  /* Signature styles End */\n\n/* Subject field styles */\n.subject-block {\n    margin-top: 20px;\n}\n.subject-block-value {\n    word-wrap: break-word;\n    white-space: pre-wrap;\n    line-height: 14pt;\n    margin-top:5px;\n}\n/* Subject field styles End*/\n\n.pcs-sub-label {\n  color: #666;\n  font-size: 10px;\n}\n.pcs-hsnsummary-compact {\n  padding: 0;\n  margin-top: 3px;\n}\n.pcs-hsnsummary-label-compact {\n  margin-bottom: 3px;\n  font-weight:600;\n  padding-left: 3px;\n  font-size: 9pt;\n}\n.pcs-hsnsummary-header-compact {\n  text-align:right;\n  padding: 5px 7px 2px 7px;\n  word-wrap: break-word;\n  width: 17%;\n  height: 32px;\n  border-right: 1px solid #9E9E9E;\n  font-size: 8pt;\n  font-weight: 600;\n}\n.pcs-hsnsummary-body-compact, .pcs-hsnsummary-total-compact {\n  text-align:right;\n  word-wrap: break-word;\n  font-size: 7pt;\n  padding: 4px 10px;\n}\n.pcs-hsnsummary-total-compact {\n  border-top: 1px solid #ece7e7;\n}\n.pcs-ukvat-summary {\n  margin-top:50px;\n  clear: both;\n  width: 100%;\n}\n.pcs-ukvat-summary-header {\n  padding:5px 10px 5px 5px;\n}\n.pcs-ukvat-summary-header:first-child {\n  padding-left: 10px;\n}\n.pcs-ukvat-summary-label {\n  font-size: 10pt;\n}\n.pcs-ukvat-summary-table {\n  margin-top: 10px;\n  width: 100%;\n  table-layout: fixed;\n}\n.pcs-ukvat-summary-body, .pcs-ukvat-summary-total {\n  padding: 10px 10px 5px 10px;\n}\n.pcs-ukvat-summary-body:first-child {\n  padding-bottom: 10px;\n  padding-right: 0;\n}\n.pcs-payment-block {\n  margin-top: 20px;\n}\n.pcs-payment-block-inner {\n  margin-top: 10px;\n}\n\n.pcs-entity-label-section {\n  padding:5px 10px 5px 0px;\n  font-size: 10pt;\n }\n\n.pcs-colon {\n  width: 3%;\n}\n\n\n \n\n\n.pcs-w-100 {\n  width: 100%;\n}\n\n\n\n\n\n\n\n.pcs-d-table-cell {\n  display: table-cell;\n}\n\n\n\n\n\n.pcs-talign-center {\n  text-align: center;\n}\n.pcs-wordwrap-bw {\n  word-wrap: break-word;\n}\n.pcs-whitespace-pw {\n  white-space: pre-wrap;\n}\n.pcs-fw-600 {\n  font-weight: 600;\n}\n.pcs-text-uppercase {\n  text-transform: uppercase;\n}\n\n\n\n\n\n.pcs-table-fixed {\n  table-layout:fixed;\n}\n\n\n\n\n\n.pcs-valign-middle {\n  vertical-align: middle;\n}\n\n\n\n.pcs-clearfix {\n  clear: both;\n}\n    .pcs-total {\n      font-size: 16pt;\n      color: #ffffff;\n    }\n    .pcs-payment-details-header {\n      color: #333333;\n      font-size: 15pt;\n    }\n    td .inner-container{\n      border-left: 1px solid #ededed;\n      padding-left: 20px;\n    }\n    .add-info td{\n      width:24%;\n      padding:20px 0;\n      border-bottom:1px solid #ededed\n    }\n    .add-info td:last-child{\n      width:auto;\n    }\n    .inner-container .pcs-label{\n      font-weight:bold;\n      font-size: 13px;\n    }\n    .add-info td:first-child .inner-container{\n      border-left: none;\n    }\n\n</style>\n\n<!--style_end-->\n\n<div class="pcs-template" style="font-size:11pt; font-family: Ubuntu;">\n\n    <div id="header" class="pcs-template-header pcs-header-content" >\n    \n\n    \n    <div class="pcs-template-fill-emptydiv"></div>\n\n  </div>\n\n\n  <div class="pcs-template-body">\n\n    <div style="padding-bottom:35px;border-bottom:1px solid #eee;width:100%;">\n      <table>\n        <tbody>\n          <tr>\n            <td>\n                <img id="logo_content" style="width:74.00px;height:72.00px;" src="https://inventory.zoho.in/ZFInvoiceLogo.zbfs?logo_id=85f9b86c9358f692665d4d07b8857d0d" />\n            </td>\n            <td style="vertical-align:top;padding-left:30px">\n                <p><span class="pcs-orgname"><b>KVTEK Power Systems Pvt. Ltd.</b><br /></span></p>\n                <span id="tmp_org_address" style="white-space: pre-wrap;color:#999;">Company ID : U74220DL2005PTC135994&#10;284-286 &amp; 290&#10;Sector-8, IMT Manesar&#10;Gurgaon Haryana 122050&#10;India&#10;GSTIN 06AABCE4590P1Z7&#10;PAN AABCE4590P</span>\n            </td>\n          </tr>\n        </tbody>\n      </table>\n    </div>\n\n    <div style="padding:35px 0 50px;text-align:center">\n      <span class="pcs-entity-title" style="border-bottom:1px solid #eee;">PAYMENT RECEIPT</span>\n    </div>\n\n    <div style="width: 70%;float: left;">\n\n      <div style="width: 100%;padding: 11px 0;">\n        <div class="pcs-label" style="width:35%;float:left;">Payment Date</div>\n        <div style="width:65%;border-bottom:1px solid #eee;float:right;"><b>09/03/2023</b></div>\n        <div style="clear:both;"></div>\n        </div>\n\n        <div style="width: 100%;padding: 10px 0;">\n        <div class="pcs-label" style="width:35%;float:left;">Reference Number</div>\n        <div style="width:65%;border-bottom:1px solid #eee;float:right;min-height:22px"><b></b></div>\n        <div style="clear:both;"></div>\n      </div>\n\n        <div style="width: 100%;padding: 11px 0;">\n          <div class="pcs-label" style="width:35%;float:left;">Payment Mode</div>\n          <div style="width:65%;border-bottom:1px solid #eee;float:right;"><b>Bank Transfer</b></div>\n          <div style="clear:both;"></div>\n        </div>\n\n\n\n        <div style="width: 100%;padding: 11px 0;">\n        <div class="pcs-label" style="width:35%;float:left;">Amount Received In Words</div>\n        <div style="width:65%;border-bottom:1px solid #eee;float:right;"><b>Indian Rupee Eighty Lakh Sixty-Nine Thousand Nine Hundred Thirty-Eight  Only</b></div>\n        <div style="clear:both;"></div>\n        </div>\n\n\n    </div>\n\n    <div style="text-align:center;color:#ffffff;float:right;background:#78ae54;width: 25%; padding: 34px 5px;">\n      <span> Amount Received</span><br />\n      <span class="pcs-total">\n       ₹80,69,938.00\n      </span>\n      </div><div style="clear:both;">\n    </div>\n\n\n    <div style="margin-top:50px">\n      <table style="width:100%">\n        <tbody>\n          <tr>\n            <td>\n               <div><p style="font-weight:600" id="tmp_billing_address_label" class="pcs-label">Bill To</p>\n                 <span id="tmp_billing_address" style="white-space: pre-wrap;"><strong><span id="zb-pdf-customer-detail" class="pcs-customer-name">Virginia Transformer Corporation</span></strong>\n220 Glade View Drive,\nRoanoke, VA\n24012 \nUSA</span>\n              </div>\n            </td>\n            <td style="text-align: right;vertical-align:top">\n                <p class="pcs-label">Authorized Signature</p>\n                  <p><div style="float:right;width: 200px;border-bottom: 1px solid #ededed;margin-top: 50px;"></div></p>\n            </td>\n          </tr>\n        </tbody>\n      </table>\n    </div>\n   <div style="margin: 100px -0.400000in 0 -0.550000in;border-top:1px solid #ededed;"></div>\n   <div style="page-break-inside: avoid;">\n    <div class="add-info">\n      <table style="width:100%">\n        <tbody>\n          <tr>\n            <td>\n              <div class="inner-container">\n               <p class="pcs-label">Over payment</p>\n               <div>\n                ₹80,69,938.00\n               </div>\n              </div>\n            </td>\n          </tr>\n        </tbody>\n      </table>\n   </div>\n  </div>\n\n    \n    \n    \n    </div>\n      <div class="pcs-template-footer">\n    <div >\n      \n    </div>  \n  </div>\n\n  </div>\n',
  template_id: "536460000000000247",
  template_name: "Elite Template",
  page_width: "8.27in",
  page_height: "11.69in",
  orientation: "portrait",
  template_type: "elite",
  template_type_formatted: "Elite",
  attachment_name: "",
  can_send_in_mail: true,
  can_send_payment_sms: true,
  is_payment_details_required: true,
  custom_fields: [],
  custom_field_hash: {},
  imported_transactions: [],
};
