item = {
  item_id: "536460000007476086",
  name: '"Instrument Case 3U ( 335 x 245 x 135mm ) New (ARW942Q-QAVA56929)"',
  sku: "EP84T3653UMMW7",
  brand: "Schneider Electric President Systems Ltd.",
  manufacturer: "",
  category_id: "536460000007473524",
  category_name: "Enclosoure Boxes",
  hsn_or_sac: "85381010",
  image_name: "",
  image_type: "",
  status: "active",
  status_formatted: "Active",
  source: "user",
  source_formatted: "User",
  is_linked_with_zohocrm: false,
  zcrm_product_id: "",
  crm_owner_id: "",
  unit: "Nos",
  unit_id: "536460000000153208",
  quantity_decimal_place: "",
  description: "",
  item_tax_preferences: [
    {
      tax_specification: "inter",
      tax_type: 0,
      tax_name: "IGST18",
      tax_percentage: 18.0,
      tax_id: "536460000000021131",
    },
    {
      tax_specification: "intra",
      tax_type: 2,
      tax_name: "GST18",
      tax_percentage: 18.0,
      tax_id: "536460000000021143",
    },
  ],
  rate: 3540.0,
  rate_formatted: "₹3,540.00",
  account_id: "536460000000000486",
  account_name: "Sales",
  tax_id: "",
  tax_name: "",
  tax_name_formatted: "",
  tax_percentage: 0,
  tax_type: "",
  is_default_tax_applied: false,
  is_taxable: true,
  tax_exemption_id: "",
  tax_exemption_code: "",
  taxability_type: "none",
  associated_template_id: "",
  documents: [],
  purchase_description: "",
  product_description: "",
  product_short_description: "",
  pricebook_rate: 3540.0,
  pricebook_discount: "",
  sales_rate: 3540.0,
  sales_rate_formatted: "₹3,540.00",
  purchase_rate: 3540.0,
  purchase_rate_formatted: "₹3,540.00",
  purchase_account_id: "536460000000013068",
  purchase_account_name: "Materials",
  inventory_account_id: "536460000000000626",
  inventory_account_name: "Inventory Asset",
  created_time: "2021-09-02T11:16:21+0530",
  offline_created_date_with_time: "",
  offline_created_date_with_time_formatted: "",
  last_modified_time: "2023-04-05T16:30:07+0530",
  tags: [],
  item_type: "inventory",
  item_type_formatted: "Inventory Items",
  product_type: "goods",
  product_type_formatted: "Goods",
  is_returnable: false,
  reorder_level: "",
  minimum_order_quantity: "",
  maximum_order_quantity: "",
  initial_stock: 2.0,
  initial_stock_formatted: "2.00",
  initial_stock_rate: 3540.0,
  initial_stock_rate_formatted: "3,540.00",
  total_initial_stock: 2.0,
  total_initial_stock_formatted: "2.00",
  vendor_id: "",
  vendor_name: "",
  stock_on_hand: 9.0,
  stock_on_hand_formatted: "9.00",
  asset_value: "",
  asset_value_formatted: "",
  available_stock: 9.0,
  available_stock_formatted: "9.00",
  actual_available_stock: 9.0,
  actual_available_stock_formatted: "9.00",
  committed_stock: 0.0,
  committed_stock_formatted: "0.00",
  actual_committed_stock: 0.0,
  actual_committed_stock_formatted: "0.00",
  available_for_sale_stock: 9.0,
  available_for_sale_stock_formatted: "9.00",
  actual_available_for_sale_stock: 9.0,
  actual_available_for_sale_stock_formatted: "9.00",
  custom_fields: [],
  custom_field_hash: {},
  image_document_id: "",
  track_serial_number: false,
  track_batch_number: false,
  upc: "",
  upc_formatted: "",
  ean: "",
  ean_formatted: "",
  isbn: "",
  part_number: "",
  is_combo_product: false,
  sales_channels: [],
  warehouses: [
    {
      warehouse_id: "536460000000014524",
      warehouse_name: "Main Store",
      status: "active",
      status_formatted: "Active",
      is_primary: true,
      warehouse_stock_on_hand: 3.0,
      warehouse_stock_on_hand_formatted: "3.00",
      initial_stock: 2.0,
      initial_stock_formatted: "2.00",
      initial_stock_rate: 3540.0,
      initial_stock_rate_formatted: "₹3,540.00",
      warehouse_available_stock: 3.0,
      warehouse_available_stock_formatted: "3.00",
      warehouse_actual_available_stock: 3.0,
      warehouse_actual_available_stock_formatted: "3.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 3.0,
      warehouse_available_for_sale_stock_formatted: "3.00",
      warehouse_actual_available_for_sale_stock: 3.0,
      warehouse_actual_available_for_sale_stock_formatted: "3.00",
      serial_numbers: [],
      batches: [],
      is_fba_warehouse: false,
      sales_channels: [],
    },
    {
      warehouse_id: "536460000000014553",
      warehouse_name: "Mechanical",
      status: "active",
      status_formatted: "Active",
      is_primary: false,
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
      is_fba_warehouse: false,
      sales_channels: [],
    },
    {
      warehouse_id: "536460000000014557",
      warehouse_name: "Finished Goods Store",
      status: "active",
      status_formatted: "Active",
      is_primary: false,
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
      is_fba_warehouse: false,
      sales_channels: [],
    },
    {
      warehouse_id: "536460000001457059",
      warehouse_name: "IHV",
      status: "active",
      status_formatted: "Active",
      is_primary: false,
      warehouse_stock_on_hand: 6.0,
      warehouse_stock_on_hand_formatted: "6.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 6.0,
      warehouse_available_stock_formatted: "6.00",
      warehouse_actual_available_stock: 6.0,
      warehouse_actual_available_stock_formatted: "6.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 6.0,
      warehouse_available_for_sale_stock_formatted: "6.00",
      warehouse_actual_available_for_sale_stock: 6.0,
      warehouse_actual_available_for_sale_stock_formatted: "6.00",
      serial_numbers: [],
      batches: [],
      is_fba_warehouse: false,
      sales_channels: [],
    },
    {
      warehouse_id: "536460000015944005",
      warehouse_name: "PCB",
      status: "active",
      status_formatted: "Active",
      is_primary: false,
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
      is_fba_warehouse: false,
      sales_channels: [],
    },
    {
      warehouse_id: "536460000015951001",
      warehouse_name: "TRM",
      status: "active",
      status_formatted: "Active",
      is_primary: false,
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
      is_fba_warehouse: false,
      sales_channels: [],
    },
    {
      warehouse_id: "536460000015957997",
      warehouse_name: "Paint",
      status: "active",
      status_formatted: "Active",
      is_primary: false,
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
      is_fba_warehouse: false,
      sales_channels: [],
    },
    {
      warehouse_id: "536460000015964993",
      warehouse_name: "TTD",
      status: "active",
      status_formatted: "Active",
      is_primary: false,
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
      is_fba_warehouse: false,
      sales_channels: [],
    },
    {
      warehouse_id: "536460000015971989",
      warehouse_name: "PHV",
      status: "active",
      status_formatted: "Active",
      is_primary: false,
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
      is_fba_warehouse: false,
      sales_channels: [],
    },
    {
      warehouse_id: "536460000015978985",
      warehouse_name: "Packing & Dipatch",
      status: "active",
      status_formatted: "Active",
      is_primary: false,
      warehouse_stock_on_hand: 0.0,
      warehouse_stock_on_hand_formatted: "0.00",
      initial_stock: 0.0,
      initial_stock_formatted: "0.00",
      initial_stock_rate: 0.0,
      initial_stock_rate_formatted: "₹0.00",
      warehouse_available_stock: 0.0,
      warehouse_available_stock_formatted: "0.00",
      warehouse_actual_available_stock: 0.0,
      warehouse_actual_available_stock_formatted: "0.00",
      warehouse_committed_stock: 0.0,
      warehouse_committed_stock_formatted: "0.00",
      warehouse_actual_committed_stock: 0.0,
      warehouse_actual_committed_stock_formatted: "0.00",
      warehouse_available_for_sale_stock: 0.0,
      warehouse_available_for_sale_stock_formatted: "0.00",
      warehouse_actual_available_for_sale_stock: 0.0,
      warehouse_actual_available_for_sale_stock_formatted: "0.00",
      serial_numbers: [],
      batches: [],
      is_fba_warehouse: false,
      sales_channels: [],
    },
  ],
  preferred_vendors: [],
  comments: [
    {
      comment_id: "536460000007476093",
      description: "created by",
      commented_by_id: "536460000000024001",
      commented_by: "Girish Kumar",
      comment_type: "system",
      date: "2021-09-02",
      date_formatted: "02/09/2021 11:16 AM",
      date_with_time: "2021-09-02T11:16:21+0530",
      date_description: "about a year ago",
      time: "11:16 AM",
      operation_type: "Added",
    },
  ],
  package_details: {
    length: "",
    width: "",
    height: "",
    weight: "",
    weight_unit: "kg",
    dimension_unit: "cm",
  },
};
