active_org = {
  code: 0,
  message: "success",
  data: [
    {
      company_name: "KVTEK Power Systems Pvt. Ltd.",
      organization_id: "60008720898",
      plan_name: "STANDARD",
      plan_period: "1 year",
      user_status: 1,
      is_org_active: true,
      is_logo_uploaded: true,
      is_zbclient: false,
      redirect_url: "",
      org_action: "goto",
      mode: "live",
      is_zpayroll_grid: false,
    },
  ],
};

orgs = {
  code: 0,
  message: "success",
  organization: {
    organization_id: "60008720898",
    name: "KVTEK Power Systems Pvt. Ltd.",
    is_logo_uploaded: true,
    is_seal_uploaded: false,
    logo_url:"https://inventory.zoho.in/api/v1/settings/templates/invoicelogo/2-85f9b86c9358f6926eea576ae8c0100a4c09ee5c070c27cff42fe4604e709e870785804fd728499d0a78aefc0d336bb1",
    store_logo_url: "",
    is_default_org: false,
    user_role: "Admin",
    role_id: "536460000000000807",
    account_created_date: "2021-04-03",
    account_created_date_formatted: "03/04/2021",
    time_zone: "Asia/Calcutta",
    time_zone_formatted: "(GMT 5:30) India Standard Time (Asia/Calcutta)",
    language_code: "en",
    language_code_formatted: "English",
    date_format: "dd/MM/yyyy",
    field_separator: "/",
    fiscal_year_start_month: "april",
    fiscal_year_start_month_formatted: "April",
    primary_domain_name: "outlook.com",
    is_public_domain: true,
    can_show_authentication_warning: false,
    fiscal_year_start_date: 1,
    tax_group_enabled: true,
    user_status: "active",
    user_status_formatted: "Active",
    contact_name: "it.kvtek",
    industry_type: "Engineering",
    industry_type_formatted: "Engineering",
    industry_size: "",
    previous_invoicing_option: "",
    company_id_label: "Company ID :",
    custom_field_type: 2,
    is_trial_period_extended: true,
    is_quick_setup_completed: false,
    is_sez: false,
    is_designated_zone: false,
    store_url: "",
    company_id_value: "U74220DL2005PTC135994",
    tax_id_label: "Tax ID :",
    tax_id_value: "",
    currency_id: "536460000000000064",
    currency_code: "INR",
    currency_symbol: "₹",
    currency_format: "#,##,##0.00",
    price_precision: 2,
    status: "1",
    address: {
      street_address1: "284-286 & 290",
      street_address2: "Sector-8, IMT Manesar",
      city: "Gurgaon",
      state: "Haryana",
      state_code: "HR",
      country: "India",
      country_formatted: "India",
      country_code: "IN",
      zip: "122050",
      latitude: "",
      longitude: "",
    },
    tax_settings: {
      is_tax_registered: true,
      tax_reg_no: "06AABCE4590P1Z7",
    },
    is_registered_for_gst: true,
    is_union_territory: false,
    is_composition_scheme_enabled: false,
    org_address: "",
    remit_to_address: "",
    phone: "0124-4971300",
    fax: "",
    website: "www.kvtek.in",
    version: "india",
    weight_unit: "kg",
    dimension_unit: "cm",
    is_old_email_flow: false,
    business_type: "",
    email: "it.kvtek@outlook.com",
    unverified_emails_count: 1,
    tax_basis: "accrual",
    custom_fields: [
      {
        index: 1,
        label: "PAN",
        value: " AABCE4590P",
      },
      {
        index: 2,
        label: "",
        value: "",
      },
      {
        index: 3,
        label: "",
        value: "",
      },
      {
        index: 4,
        label: "",
        value: "",
      },
      {
        index: 5,
        label: "",
        value: "",
      },
    ],
    custom_field_hash: {
      cf_1_unformatted: " AABCE4590P",
      cf_2_unformatted: "",
      cf_3_unformatted: "",
      cf_4_unformatted: "",
      cf_5_unformatted: "",
    },
    is_org_active: true,
    is_transaction_available: true,
    is_transaction_available_for_timezone: true,
    show_org_address_as_one_field: false,
    is_new_customer_custom_fields: true,
    is_portal_enabled: true,
    org_joined_app_list: ["books", "inventory", "payroll"],
    portal_name: "kvtekpower",
    business_start_date: "2021-04-01",
    business_start_date_formatted: "01/04/2021",
    inventory_start_date: "2021-04-01",
    inventory_start_date_formatted: "01/04/2021",
    is_project_enabled: true,
    is_retainerinvoice_enabled: true,
    theme: "cobaltblue",
    mode: "live",
    payments_url:
      "https://store.zoho.in/html/store/index.html#subscription?serviceId=250000&customId=95f1f37457b84aa694e286fc92b4afb1&dc=india",
  },
};
