vendorpayment = {
  payment_id: "536460000020276759",
  vendor_id: "536460000003319823",
  vendor_name: "Netlab Solutions (India) Pvt Ltd (Delhi)",
  transfer_type: "",
  payment_mode: "Bank Transfer",
  payment_number: "3257",
  payment_number_prefix: "",
  payment_number_suffix: "3257",
  purpose_code: "",
  custom_fields: [],
  custom_field_hash: {},
  description: "Being Payment ag Bill vide neft ref no: 148216926",
  documents: [],
  date: "2023-04-01",
  date_formatted: "01/04/2023",
  reference_number: "",
  exchange_rate: 1.0,
  exchange_rate_formatted: "₹1.00",
  tds_tax_id: "",
  indirect_tds_tax_id: "",
  indirect_tds_amount: 0.0,
  indirect_tds_amount_formatted: "₹0.00",
  is_tds_amount_in_percent: false,
  tax_account_id: "",
  tax_account_name: "",
  tax_amount_withheld: 0.0,
  tax_amount_withheld_formatted: "₹0.00",
  amount: 6254.0,
  amount_formatted: "₹6,254.00",
  total_payment_amount: 6254.0,
  total_payment_amount_formatted: "₹6,254.00",
  balance: 0.0,
  balance_formatted: "₹0.00",
  currency_id: "536460000000000064",
  currency_code: "INR",
  currency_symbol: "₹",
  created_time: "2023-04-03T15:36:40+0530",
  last_modified_time: "2023-04-03T15:36:40+0530",
  credit_account_id: "",
  paid_through_account_id: "536460000001461267",
  paid_through_account_name: "BANK OF INDIA CC 670430110000033",
  paid_through_account_type: "bank",
  paid_through_account_type_formatted: "Bank",
  offset_account_id: "536460000000000471",
  offset_account_name: "Accounts Payable",
  is_pre_gst: false,
  source_of_supply: "DL",
  source_of_supply_formatted: "Delhi",
  destination_of_supply: "HR",
  destination_of_supply_formatted: "Haryana",
  gst_treatment: "business_gst",
  tax_treatment: "business_gst",
  gst_return_details: {
    status_formatted: "",
    return_period: "",
    status: "",
    return_period_formatted: "",
  },
  gst_no: "07AACCN9115E1ZN",
  reverse_charge_tax_id: "",
  is_advance_payment: false,
  product_description: "",
  is_reverse_charge_applied: false,
  is_ach_payment: false,
  ach_payment_status: "",
  ach_payment_status_formatted: "",
  billing_address: {
    address: "",
    street2: "",
    city: "",
    state: "",
    zip: "",
    country: "",
    fax: "",
    phone: "",
    attention: "",
  },
  bills: [
    {
      bill_number: "TI/07/2223/16121",
      price_precision: 2,
      bill_payment_id: "536460000020276761",
      bill_id: "536460000019733361",
      is_opening_balance: false,
      total: 6254.0,
      total_formatted: "₹6,254.00",
      balance: 0.0,
      balance_formatted: "₹0.00",
      amount_applied: 6254.0,
      amount_applied_formatted: "₹6,254.00",
      tax_amount_withheld: 0.0,
      tax_amount_withheld_formatted: "₹0.00",
      date: "2023-02-21",
      date_formatted: "21/02/2023",
      due_date: "2023-03-03",
      due_date_formatted: "03/03/2023",
      indirect_tds_tax_id: "",
      indirect_tds_amount: 0.0,
      indirect_tds_amount_formatted: "₹0.00",
    },
  ],
  vendorpayment_refunds: [],
  comments: [
    {
      comment_id: "536460000020276769",
      description:
        "Payment of amount ₹6,254.00 made and applied for TI/07/2223/16121",
      commented_by_id: "536460000000109005",
      commented_by: "N. Nayak",
      date: "2023-04-03",
      date_formatted: "03/04/2023 03:36 PM",
      date_description: "20 days ago",
      time: "3:36 PM",
      operation_type: "Added",
    },
  ],
  html_string:
    '\n<!--style_start-->\n<style type="text/css" media="all">\n \n\n  @font-face {\n    font-family: \'WebFont-Ubuntu\';\n    src: local(Ubuntu), url(https://fonts.gstatic.com/s/ubuntu/v10/4iCs6KVjbNBYlgoKcg72nU6AF7xm.woff2);\n  }\n\n  .pcs-template {\n  \tfont-family: Ubuntu, \'WebFont-Ubuntu\';\n    font-size: 11pt;\n    color: #333333;\n      background:  #ffffff ;\n  }\n\n  .pcs-header-content {\n    font-size: 8pt;\n\tcolor: #333333;\n\tbackground-color: #ffffff;\n  }\n  .pcs-template-body {\n  \tpadding: 0 0.40in 0 0.55in;\n  }\n  .pcs-template-footer {\n  \theight: 0.70in;\n\tfont-size: 6pt;\n\tcolor: #aaaaaa;\n\tpadding: 0 0.40in 0 0.55in;\n\tbackground-color: #ffffff;\n  }\n  .pcs-footer-content {\n  word-wrap: break-word;\n  color: #aaaaaa;\n      border-top: 1px solid #ece7e7;\n  }\n\n  .pcs-label {\n    color: #777777;\n  }\n  .pcs-entity-title {\n    font-size: 13pt;\n    color: #333333;\n  }\n  .pcs-orgname {\n    font-size: 15pt;\n    color: #333333;\n  }\n  .pcs-customer-name {\n    font-size: 12pt;\n    color: #333333;\n  }\n  .pcs-eori-number {\n    color: #333;\n    margin: 0;\n    padding-top: 10px;\n  }\n .pcs-itemtable-header {\n    font-size: 11pt;\n    color: #333333;\n    background-color: #eff0f1;\n  }\n  .pcs-itemtable-breakword {\n    word-wrap: break-word;\n  }\n  .pcs-taxtable-header {\n    font-size: 11pt;\n    color: #333333;\n    background-color: #eff0f1;\n  }\n  .breakrow-inside {\n    page-break-inside: avoid;\n  }\n  .breakrow-after {\n    page-break-after:auto;\n  }\n  .pcs-item-row {\n    font-size: 11pt;\n    border-bottom: 1px solid #ece7e7;\n    background-color: #ffffff;\n    color: #333333;\n  }\n  .pcs-img-fit-aspectratio {\n    object-fit: contain;\n    object-position: top;\n  }\n  .pcs-img-border {\n    border: 1px solid #f5f4f3;\n  }\n  .pcs-item-sku, .pcs-item-hsn, .pcs-item-coupon, .pcs-item-serialnumber, .pcs-item-unitcode {\n    margin-top: 2px;\n  \tfont-size: 10px;\n  \tcolor: #444444;\n  }\n  .pcs-item-desc {\n      color: #8e8e8e;\n      font-size: 8pt;\n   }\n  .pcs-balance {\n    background-color: #ffffff;\n    font-size: 9pt;\n    color: #333333;\n  }\n  .pcs-savings {\n  font-size: 0pt;\n  color: ;\n  background-color: ;\n  }\n  .pcs-totals {\n    font-size: 16pt;\n    color: #ffffff;\n    background-color: #78ae54;\n  }\n  .pcs-notes {\n    font-size: 9pt;\n  }\n  .pcs-terms {\n    font-size: 9pt;\n  }\n  .pcs-header-first {\n\tbackground-color: #ffffff;\n\tfont-size: 8pt;\n\tcolor: #333333;\n      height: auto;\n\t}\n\n .pcs-status {\n \tcolor: ;\n\tfont-size: 15pt;\n\tborder: 3px solid ;\n\tpadding: 3px 8px;\n }\n .billto-section {\n     padding-top: mm;\n     padding-left: mm;\n   }\n   .shipto-section {\n     padding-top: mm;\n     padding-left: mm;\n   }\n\n @page :first {\n \t@top-center {\n\t\tcontent: element(header);\n\t}\n    margin-top: 0.70in;\n  }\n\n  .pcs-template-header {\n\tpadding: 0 0.40in 0 0.55in;\n    height: 0.70in;\n  }\n\n  .pcs-template-fill-emptydiv {\n    display: table-cell;\n    content: " ";\n    width: 100%;\n  }\n\n\n/* Additional styles for RTL compat */\n\n/* Helper Classes */\n\n.inline {\n  display: inline-block;\n}\n.v-top {\n  vertical-align: top;\n}\n.text-align-right {\n  text-align: right;\n}\n.rtl .text-align-right {\n  text-align: left;\n}\n.text-align-left {\n  text-align: left;\n}\n.rtl .text-align-left {\n  text-align: right;\n}\n.float-section-right {\n  float: right;\n}\n.rtl .float-section-right{\n  float: left;\n}\n.float-section-left {\n  float: left;\n}\n.rtl .float-section-left{\n  float: right;\n}\n\n/* Helper Classes End */\n\n.item-details-inline {\n  display: inline-block;\n  margin: 0 10px;\n  vertical-align: top;\n  max-width: 70%;\n}\n\n.total-in-words-container {\n  width: 100%;\n  margin-top: 10px;\n}\n.total-in-words-label {\n  vertical-align: top;\n  padding: 0 10px;\n}\n.total-in-words-value {\n  width: 170px;\n}\n.total-section-label {\n  padding: 5px 10px 5px 0;\n  vertical-align: middle;\n}\n.total-section-value {\n  width: 120px;\n  vertical-align: middle;\n  padding: 10px 10px 10px 5px;\n}\n.rtl .total-section-value {\n  padding: 10px 5px 10px 10px;\n}\n\n.tax-summary-description {\n  color: #727272;\n  font-size: 8pt;\n}\n\n.bharatqr-bg {\n  background-color: #f4f3f8;\n}\n\n/* Overrides/Patches for RTL compat */\n  .rtl th {\n    text-align: inherit; /* Specifically setting th as inherit for supporting RTL */\n  }\n/* Overrides/Patches End */\n\n\n/* Subject field styles */\n.subject-block {\n    margin-top: 20px;\n}\n.subject-block-value {\n    word-wrap: break-word;\n    white-space: pre-wrap;\n    line-height: 14pt;\n    margin-top:5px;\n}\n/* Subject field styles End*/\n\n.pcs-sub-label {\n  color: #666;\n  font-size: 10px;\n}\n.pcs-hsnsummary-compact {\n  padding: 0;\n  margin-top: 3px;\n}\n.pcs-hsnsummary-label-compact {\n  margin-bottom: 3px;\n  font-weight:600;\n  padding-left: 3px;\n  font-size: 9pt;\n}\n.pcs-hsnsummary-header-compact {\n  text-align:right;\n  padding: 5px 7px 2px 7px;\n  word-wrap: break-word;\n  width: 17%;\n  height: 32px;\n  border-right: 1px solid #9E9E9E;\n  font-size: 8pt;\n  font-weight: 600;\n}\n.pcs-hsnsummary-body-compact, .pcs-hsnsummary-total-compact {\n  text-align:right;\n  word-wrap: break-word;\n  font-size: 7pt;\n  padding: 4px 10px;\n}\n.pcs-hsnsummary-total-compact {\n  border-top: 1px solid #ece7e7;\n}\n.pcs-ukvat-summary {\n  margin-top:50px;\n  clear: both;\n  width: 100%;\n}\n.pcs-ukvat-summary-header {\n  padding:5px 10px 5px 5px;\n}\n.pcs-ukvat-summary-header:first-child {\n  padding-left: 10px;\n}\n.pcs-ukvat-summary-label {\n  font-size: 10pt;\n}\n.pcs-ukvat-summary-table {\n  margin-top: 10px;\n  width: 100%;\n  table-layout: fixed;\n}\n.pcs-ukvat-summary-body, .pcs-ukvat-summary-total {\n  padding: 10px 10px 5px 10px;\n}\n.pcs-ukvat-summary-body:first-child {\n  padding-bottom: 10px;\n  padding-right: 0;\n}\n.pcs-payment-block {\n  margin-top: 20px;\n}\n.pcs-payment-block-inner {\n  margin-top: 10px;\n}\n\n.pcs-entity-label-section {\n  padding:5px 10px 5px 0px;\n  font-size: 10pt;\n }\n\n.pcs-colon {\n  width: 3%;\n}\n\n\n    .pcs-total {\n      font-size: 16pt;\n      color: #ffffff;\n    }\n    .pcs-payment-details-header {\n      color: #333333;\n      font-size: 15pt;\n    }\n    td .inner-container{\n      border-left: 1px solid #ededed;\n      padding-left: 20px;\n    }\n    .add-info td{\n      width:24%;\n      padding:20px 0;\n      border-bottom:1px solid #ededed\n    }\n    .add-info td:last-child{\n      width:auto;\n    }\n    .inner-container .pcs-label{\n      font-weight:bold;\n      font-size: 13px;\n    }\n    .add-info td:first-child .inner-container{\n      border-left: none;\n    }\n\n</style>\n\n<!--style_end-->\n\n<div class="pcs-template" style="font-size:11pt; font-family: Ubuntu;">\n\n      <div id="header" class="pcs-template-header pcs-header-content" >\n    \n\n    \n    <div class="pcs-template-fill-emptydiv"></div>\n\n  </div>\n\n\n    <div class="pcs-template-body">\n\n        <div style="padding-bottom:35px;border-bottom:1px solid #eee;width:100%;">\n            <table>\n                <tbody>\n                <tr>\n                        <td>\n                            <img id="logo_content" style="width:74.0px;height:72.0px;" src="https://inventory.zoho.in/ZFInvoiceLogo.zbfs?logo_id=85f9b86c9358f692665d4d07b8857d0d" />\n                        </td>\n                    <td style="vertical-align:top;padding-left:30px">\n                            <p><span class="pcs-orgname"><b>KVTEK Power Systems Pvt. Ltd.</b><br /></span></p>\n                            <span id="tmp_org_address" style="white-space: pre-wrap;color:#999;">Company ID : U74220DL2005PTC135994&#10;284-286 &amp; 290&#10;Sector-8, IMT Manesar&#10;Gurgaon Haryana 122050&#10;India&#10;GSTIN 06AABCE4590P1Z7&#10;PAN AABCE4590P</span>\n                    </td>\n                </tr>\n                </tbody>\n            </table>\n        </div>\n\n        <div style="padding:35px 0 50px;text-align:center">\n            <span class="pcs-entity-title" style="border-bottom:1px solid #eee;">PAYMENTS MADE</span>\n        </div>\n\n        <div style="width: 70%;float: left;">\n                <div style="width: 100%;padding: 11px 0;">\n                    <div class="pcs-label" style="width:35%;float:left;">Payment#</div>\n                    <div style="width:65%;border-bottom:1px solid #eee;float:right;"><b>3257</b></div>\n                    <div style="clear:both;"></div>\n                </div>\n\n                <div style="width: 100%;padding: 11px 0;">\n                    <div class="pcs-label" style="width:35%;float:left;">Payment Date</div>\n                    <div style="width:65%;border-bottom:1px solid #eee;float:right;"><b>01/04/2023</b></div>\n                    <div style="clear:both;"></div>\n                </div>\n\n                <div style="width: 100%;padding: 10px 0;">\n                    <div class="pcs-label" style="width:35%;float:left;">Reference Number</div>\n                    <div style="width:65%;border-bottom:1px solid #eee;float:right;min-height:22px"><b></b></div>\n                    <div style="clear:both;"></div>\n                </div>\n\n\n                <div style="width: 100%;padding: 11px 0;">\n                    <div class="pcs-label" style="width:35%;float:left;">Paid To</div>\n                    <div style="width:65%;border-bottom:1px solid #eee;float:right;" id="zb-pdf-customer-detail"><b>Netlab Solutions (India) Pvt Ltd (Delhi)</b></div>\n                    <div style="clear:both;"></div>\n                </div>\n\n                <div style="width: 100%;padding: 11px 0;">\n                    <div class="pcs-label" style="width:35%;float:left;">Place Of Supply</div>\n                    <div style="width:65%;border-bottom:1px solid #eee;float:right;"><b>Haryana (06)</b></div>\n                    <div style="clear:both;"></div>\n                </div>\n\n                <div style="width: 100%;padding: 11px 0;">\n                    <div class="pcs-label" style="width:35%;float:left;">Payment Mode</div>\n                    <div style="width:65%;border-bottom:1px solid #eee;float:right;"><b>Bank Transfer</b></div>\n                    <div style="clear:both;"></div>\n                </div>\n\n                <div style="width: 100%;padding: 11px 0;">\n                    <div class="pcs-label" style="width:35%;float:left;">Paid Through</div>\n                    <div style="width:65%;border-bottom:1px solid #eee;float:right;" id="zb-paid-through-account-container"><b>BANK OF INDIA CC 670430110000033</b></div>\n                    <div style="clear:both;"></div>\n                </div>\n\n\n\n                <div style="width: 100%;padding: 11px 0;">\n                    <div class="pcs-label" style="width:35%;float:left;">Amount Paid In Words</div>\n                    <div style="width:65%;border-bottom:1px solid #eee;float:right;"><b>Indian Rupee Six Thousand Two Hundred Fifty-Four  Only</b></div>\n                    <div style="clear:both;"></div>\n                </div>\n\n\n        </div>\n\n        <div style="text-align:center;color:#ffffff;float:right;background:#78ae54;width: 25%; padding: 34px 5px;">\n            <span> Amount Paid</span><br />\n            <span class="pcs-total">\n       ₹6,254.00\n      </span>\n        </div><div style="clear:both;">\n    </div>\n\n\n        <div style="margin-top:50px">\n            <table style="width:100%">\n                <tbody>\n                <tr>\n                    <td>\n                            <div><p style="font-weight:600" id="tmp_billing_address_label" class="pcs-label">Paid To</p>\n                                <span id="tmp_billing_address" style="white-space: pre-wrap;"><strong><span id="zb-pdf-customer-detail" class="pcs-customer-name">Netlab Solutions (India) Pvt Ltd (Delhi)</span></strong>\n202, Eros Apartments 56&#10;Nehru Place\nNew Delhi\n110019 Delhi\nIndia\nGSTIN 07AACCN9115E1ZN</span>\n                            </div>\n\n                    </td>\n                    <td style="text-align: right;vertical-align:top">\n                    </td>\n                </tr>\n                </tbody>\n            </table>\n        </div>\n\n        <div style="margin: 50px -0.40in 0 -0.55in;border-top:1px solid #ededed;"></div>\n        <div style="page-break-inside: avoid;">\n            <div class="add-info">\n                <table style="width:100%">\n                    <tbody>\n                    <tr>\n\n                    </tr>\n                    </tbody>\n                </table>\n            </div>\n        </div>\n\n\n                <div style="margin-top:30px;page-break-inside: avoid;">\n                        <h4 style="margin-bottom:18px;" class="pcs-payment-details-header">Payment for</h4>\n\n                    <table cellpadding="0" cellspacing="0" border="0" class="pcs-itemtable"  style="width:100%;table-layout:fixed;">\n                        <thead>\n                        <tr style="height:40px;">\n\n                                <td  class="pcs-itemtable-header" style="padding:5px 10px 5px 10px;word-wrap: break-word;">\n                                    Bill Number\n                                </td>\n\n                                <td class="pcs-itemtable-header" style="padding:5px 10px 5px 5px;word-wrap: break-word;">\n                                    Bill Date\n                                </td>\n\n                                <td  class="pcs-itemtable-header" style="padding:5px 10px 5px 5px;word-wrap: break-word;" align="right">\n                                    Bill Amount\n                                </td>\n\n\n\n                                <td class="pcs-itemtable-header" style="padding:5px 10px 5px 5px;word-wrap: break-word;" align="right">\n                                    Payment Amount\n                                </td>\n\n                        </tr>\n                        </thead>\n                        <tbody>\n                            <tr style="border-top:1px solid #ededed">\n\n                                    <td class="pcs-item-row" style="padding: 10px 0px 10px 10px;word-wrap: break-word;" valign="top">\n                                        <span id="536460000019733361">TI/07/2223/16121</span>\n                                    </td>\n\n                                    <td class="pcs-item-row" style="padding: 10px 10px 5px 10px;word-wrap: break-word;" valign="top">\n                                        21/02/2023\n                                    </td>\n\n                                    <td class="pcs-item-row" style="padding: 10px 10px 5px 10px;text-align:right;word-wrap: break-word;" valign="top">\n                                        ₹6,254.00\n                                    </td>\n\n\n\n                                    <td class="pcs-item-row" style="text-align:right;padding: 10px 10px 10px 5px;word-wrap: break-word;" valign="top">\n                                        ₹6,254.00\n                                    </td>\n                            </tr>\n                        </tbody>\n                    </table>\n                </div>\n\n\n        \n    </div>\n      <div class="pcs-template-footer">\n    <div >\n      \n    </div>  \n  </div>\n\n</div>\n',
  imported_transactions: [],
};
