purchaseorder = {
  purchaseorder_id: "536460000020353330",
  documents: [],
  crm_owner_id: "",
  crm_custom_reference_id: "",
  tax_treatment: "business_gst",
  tax_treatment_formatted: "Registered Business - Regular",
  gst_no: "06AHQPY5442F1ZV",
  contact_category: "business_gst",
  gst_treatment: "business_gst",
  gst_treatment_formatted: "Registered Business - Regular",
  purchaseorder_number: "K2023-089",
  date: "2023-04-21",
  date_formatted: "21/04/2023",
  currency_formatter: {
    decimal_separator: ".",
    number_separator: ",",
    secondary_grouping_size: 2,
  },
  client_viewed_time: "",
  client_viewed_time_formatted: "",
  is_viewed_by_client: false,
  is_pre_gst: false,
  expected_delivery_date: "",
  expected_delivery_date_formatted: "",
  reference_number: "Tools for CNC Machine",
  status: "issued",
  status_formatted: "Issued",
  order_status: "issued",
  order_status_formatted: "Issued",
  is_received: false,
  received_status: "",
  received_status_formatted: "",
  billed_status: "",
  billed_status_formatted: "",
  color_code: "",
  current_sub_status_id: "",
  current_sub_status: "issued",
  current_sub_status_formatted: "Issued",
  sub_statuses: [],
  source_of_supply: "HR",
  source_of_supply_formatted: "Haryana",
  destination_of_supply: "HR",
  destination_of_supply_formatted: "Haryana",
  vendor_id: "536460000018842900",
  vendor_name: "Karam Techno Solutions",
  is_portal_enabled: false,
  contact_persons: ["536460000018842902"],
  currency_id: "536460000000000064",
  currency_code: "INR",
  currency_symbol: "₹",
  exchange_rate: 1.0,
  delivery_date: "2023-04-26",
  delivery_date_formatted: "26/04/2023",
  is_emailed: true,
  is_drop_shipment: false,
  show_convert_to_bill: true,
  is_inclusive_tax: false,
  tax_rounding: "entity_level",
  is_reverse_charge_applied: false,
  is_adv_tracking_in_receive: false,
  salesorder_id: "",
  is_backorder: false,
  is_po_marked_as_received: false,
  total_quantity: 10.0,
  total_quantity_formatted: "10.00",
  line_items: [
    {
      item_id: "536460000018842635",
      line_item_id: "536460000020353332",
      salesorder_item_id: "",
      image_document_id: "",
      sku: "CNCGCML4002CG0",
      warehouse_id: "536460000000014524",
      warehouse_name: "Main Store",
      account_id: "536460000000000626",
      account_name: "Inventory Asset",
      name: "CNC Grooing Insert GCML4002-CG-05-AC530U",
      description: "OK",
      item_order: 1,
      bcy_rate: 1303.0,
      bcy_rate_formatted: "₹1,303.00",
      pricebook_id: "",
      header_id: "",
      header_name: "",
      rate: 1303.0,
      rate_formatted: "₹1,303.00",
      quantity: 10.0,
      package_details: {
        length: "",
        width: "",
        height: "",
        weight: "",
        weight_unit: "kg",
        dimension_unit: "cm",
      },
      discount: 0.0,
      discounts: [],
      quantity_received: 0.0,
      quantity_marked_as_received: 0.0,
      quantity_intransit: 0.0,
      quantity_cancelled: 0.0,
      quantity_billed: 0.0,
      unit: "Nos",
      item_total: 13030.0,
      item_total_formatted: "₹13,030.00",
      item_total_inclusive_of_tax: 15375.4,
      item_total_inclusive_of_tax_formatted: "₹15,375.40",
      tax_exemption_id: "",
      tax_exemption_code: "",
      gst_treatment_code: "",
      tax_id: "536460000000021143",
      tax_name: "GST18",
      tax_type: "tax_group",
      tax_percentage: 18,
      product_type: "goods",
      item_type: "inventory",
      item_type_formatted: "Inventory Items",
      line_item_taxes: [
        {
          tax_id: "536460000000021135",
          tax_name: "SGST9 (9%)",
          tax_amount: 1172.7,
          tax_amount_formatted: "₹1,172.70",
        },
        {
          tax_id: "536460000000021139",
          tax_name: "CGST9 (9%)",
          tax_amount: 1172.7,
          tax_amount_formatted: "₹1,172.70",
        },
      ],
      hsn_or_sac: "",
      reverse_charge_tax_id: "",
      tags: [],
      item_custom_fields: [],
      project_id: "",
      image_name: "",
      image_type: "",
      track_serial_for_receive: false,
      track_batch_for_receive: false,
      track_serial_number: false,
      track_batch_number: false,
      purchase_request_items: [],
      is_combo_product: false,
    },
  ],
  has_qty_cancelled: false,
  adjustment: 0.0,
  adjustment_formatted: "₹0.00",
  adjustment_description: "Adjustment",
  discount_amount_formatted: "₹0.00",
  discount_amount: 0.0,
  discount: 0.0,
  discount_applied_on_amount_formatted: "₹0.00",
  discount_applied_on_amount: 0.0,
  is_discount_before_tax: true,
  discount_account_id: "",
  discount_type: "entity_level",
  sub_total: 13030.0,
  sub_total_formatted: "₹13,030.00",
  sub_total_inclusive_of_tax: 15375.4,
  sub_total_inclusive_of_tax_formatted: "₹15,375.40",
  tax_total: 2345.4,
  tax_total_formatted: "₹2,345.40",
  total: 15375.4,
  total_formatted: "₹15,375.40",
  taxes: [
    {
      tax_id: "536460000000021135",
      tax_name: "SGST9 (9%)",
      tax_amount: 1172.7,
      tax_amount_formatted: "₹1,172.70",
    },
    {
      tax_id: "536460000000021139",
      tax_name: "CGST9 (9%)",
      tax_amount: 1172.7,
      tax_amount_formatted: "₹1,172.70",
    },
  ],
  tax_override: false,
  price_precision: 2,
  comments: [
    {
      comment_id: "536460000020353360",
      purchaseorder_id: "536460000020353330",
      description: "Purchase Order emailed to karambirnikkum@gmail.com",
      commented_by_id: "536460000001419001",
      commented_by: "Sandeep Dua",
      comment_type: "system",
      date: "2023-04-21",
      date_formatted: "21/04/2023 06:01 PM",
      date_description: "2 days ago",
      time: "6:01 PM",
      operation_type: "Updated",
      transaction_id: "",
      transaction_type: "email",
    },
    {
      comment_id: "536460000020353352",
      purchaseorder_id: "536460000020353330",
      description: "Purchase order approved",
      commented_by_id: "536460000001419001",
      commented_by: "Sandeep Dua",
      comment_type: "system",
      date: "2023-04-21",
      date_formatted: "21/04/2023 06:01 PM",
      date_description: "2 days ago",
      time: "6:01 PM",
      operation_type: "Updated",
      transaction_id: "",
      transaction_type: "purchaseorder",
    },
    {
      comment_id: "536460000020353346",
      purchaseorder_id: "536460000020353330",
      description: "Purchase order submitted for approval",
      commented_by_id: "536460000001419001",
      commented_by: "Sandeep Dua",
      comment_type: "system",
      date: "2023-04-21",
      date_formatted: "21/04/2023 06:01 PM",
      date_description: "2 days ago",
      time: "6:01 PM",
      operation_type: "Updated",
      transaction_id: "",
      transaction_type: "purchaseorder",
    },
    {
      comment_id: "536460000020353336",
      purchaseorder_id: "536460000020353330",
      description: "Purchase Order created for ₹15,375.40",
      commented_by_id: "536460000001419001",
      commented_by: "Sandeep Dua",
      comment_type: "system",
      date: "2023-04-21",
      date_formatted: "21/04/2023 06:01 PM",
      date_description: "2 days ago",
      time: "6:01 PM",
      operation_type: "Added",
      transaction_id: "",
      transaction_type: "purchaseorder",
    },
  ],
  submitted_date: "2023-04-21",
  submitted_date_formatted: "21/04/2023",
  submitted_by: "Sandeep Dua (s.dua@kvtek.in)",
  submitted_by_name: "Sandeep Dua",
  submitted_by_email: "s.dua@kvtek.in",
  submitted_by_photo_url:
    "https://contacts.zoho.in/file?t=user&ID=60009715295&fs=thumb",
  submitter_id: "536460000001419001",
  approver_id: "536460000001419001",
  approvers_list: [
    {
      order: 1,
      approver_user_id: "536460000001419001",
      approver_name: "Sandeep Dua",
      email: "s.dua@kvtek.in",
      has_approved: true,
      approval_status: "approved",
      approval_status_formatted: "approved",
      is_next_approver: false,
      submitted_date: "",
      submitted_date_formatted: "",
      approved_date: "2023-04-21",
      approved_date_formatted: "21/04/2023",
      photo_url: "https://contacts.zoho.in/file?t=user&ID=60009715295&fs=thumb",
      user_status: "active",
      user_status_formatted: "Active",
      is_final_approver: false,
      available_apps: ["Zoho Inventory"],
      zuid: "60009715295",
    },
  ],
  billing_address_id: "536460000018842905",
  billing_address: {
    address: "Plot No. 28, Turkiyawas Road , Rewari HR 123401",
    street2: "",
    city: "",
    state: "",
    zip: "",
    country: "",
    fax: "",
    phone: "",
    attention: "",
  },
  notes: "",
  terms:
    "1. Prices: Ex Work \n2. Freight. : Extra\n3. Payment Terms: 100% after acceptance of material \n4. Delivery Schedule: 26.04.2023\n5. Warranty: 12 months from the date of dispatch.\n6. LD: Liquidated Damages shall be applicable @ 0.5% per week delay in delivery \n    until actual delivery up to maximum of 5.0% of the total order value.\n7.  Inspection/Testing: a. Inspection of Raw material to be done at vendor site.\nb. Inspection Required prior to dispatch/ Sample to be tested \n    after receiving Material.\t\n8. Documentation:  Commercial Invoice, Packing List, Material Test Report.\n9. Jurisdiction:\t Any arbitration or settlement of conflict will be within the jurisdiction \n                                 of the court of New Delhi only.\n10. Insurance: Extra",
  payment_terms: 30,
  payment_terms_label: "100 % after acceptance of materials",
  ship_via: "Courier",
  ship_via_id: "536460000017151225",
  attention: "Main Store",
  delivery_org_address_id: "536460000000014524",
  delivery_customer_id: "",
  delivery_customer_address_id: "",
  delivery_address: {
    zip: "122050",
    country: "India",
    address: "284 - 286, Sector 8",
    is_verifiable: true,
    is_primary: true,
    address2: "",
    city: "Gurgaon",
    address1: "284 - 286, Sector 8",
    is_warehouse: true,
    is_verified: false,
    organization_address_id: "536460000000014524",
    phone: "",
    is_valid: false,
    state: "Haryana",
    email: "it.kvtek@outlook.com",
  },
  custom_fields: [],
  custom_field_hash: {},
  attachment_name: "",
  can_send_in_mail: false,
  template_id: "536460000000000237",
  template_name: "KVTEK PO",
  page_width: "8.27in",
  page_height: "11.69in",
  orientation: "portrait",
  template_type: "standard",
  template_type_formatted: "Standard",
  created_time: "2023-04-21T18:01:33+0530",
  created_by_id: "536460000001419001",
  last_modified_time: "2023-04-21T18:01:58+0530",
  html_string:
    '\n<!--The below style_start tag has to be present as it is used to substring the style content from the body html-->\n\n<!--style_start-->\n  <style type="text/css" media="all">\n \t\n\n  @font-face {\n    font-family: \'WebFont-Ubuntu\';\n    src: local(Ubuntu), url(https://fonts.gstatic.com/s/ubuntu/v10/4iCs6KVjbNBYlgoKcg72nU6AF7xm.woff2);\n  }\n\n  .pcs-template {\n  \tfont-family: Ubuntu, \'WebFont-Ubuntu\';\n    font-size: 9pt;\n    color: #333333;\n      background:  #ffffff ;\n  }\n\n  .pcs-header-content {\n    font-size: 9pt;\n\tcolor: #333333;\n\tbackground-color: #ffffff;\n  }\n  .pcs-template-body {\n  \tpadding: 0 0.400000in 0 0.550000in;\n  }\n  .pcs-template-footer {\n  \theight: 0.700000in;\n\tfont-size: 6pt;\n\tcolor: #aaaaaa;\n\tpadding: 0 0.400000in 0 0.550000in;\n\tbackground: url(https://inventory.zoho.in/Templates_FooterBG_536460000000000237.zbfs?organization_id=60008720898&1627909133127) no-repeat center center;\n\tbackground-size:  827px;\n  }\n  .pcs-footer-content {\n  word-wrap: break-word;\n  color: #aaaaaa;\n  }\n\n  .pcs-label {\n    color: #333333;\n  }\n  .pcs-entity-title {\n    font-size: 28pt;\n    color: #000000;\n  }\n  .pcs-orgname {\n    font-size: 10pt;\n    color: #333333;\n  }\n  .pcs-customer-name {\n    font-size: 9pt;\n    color: #333333;\n  }\n  .pcs-eori-number {\n    color: #333;\n    margin: 0;\n    padding-top: 10px;\n  }\n .pcs-itemtable-header {\n    font-size: 9pt;\n    color: #ffffff;\n    background-color: #3c3d3a;\n  }\n  .pcs-itemtable-breakword {\n    word-wrap: break-word;\n  }\n  .pcs-taxtable-header {\n    font-size: 9pt;\n    color: #ffffff;\n    background-color: #3c3d3a;\n  }\n  .breakrow-inside {\n    page-break-inside: avoid;\n  }\n  .breakrow-after {\n    page-break-after:auto;\n  }\n  .pcs-item-row {\n    font-size: 9pt;\n    border-bottom: 1px solid #adadad;\n    background-color: #ffffff;\n    color: #000000;\n  }\n  .pcs-img-fit-aspectratio {\n    object-fit: contain;\n    object-position: top;\n  }\n  .pcs-img-border {\n    border: 1px solid #f5f4f3;\n  }\n  .pcs-item-sku, .pcs-item-hsn, .pcs-item-coupon, .pcs-item-serialnumber, .pcs-item-unitcode {\n    margin-top: 2px;\n  \tfont-size: 10px;\n  \tcolor: #444444;\n  }\n  .pcs-item-desc {\n      color: #333333;\n      font-size: 8pt;\n   }\n  .pcs-balance {\n    background-color: #f5f4f3;\n    font-size: 9pt;\n    color: #000000;\n  }\n  .pcs-savings {\n  font-size: 0pt;\n  color: ;\n  background-color: ;\n  }\n  .pcs-totals {\n    font-size: 9pt;\n    color: #000000;\n    background-color: #ffffff;\n  }\n  .pcs-notes {\n    font-size: 8pt;\n  }\n  .pcs-terms {\n    font-size: 8pt;\n  }\n  .pcs-header-first {\n\tbackground-color: #ffffff;\n\tfont-size: 9pt;\n\tcolor: #333333;\n      height: 0.700000in;\n\t}\n\n .pcs-status {\n \tcolor: ;\n\tfont-size: 15pt;\n\tborder: 3px solid ;\n\tpadding: 3px 8px;\n }\n .billto-section {\n     padding-top: 0mm;\n     padding-left: 0mm;\n   }\n   .shipto-section {\n     padding-top: 0mm;\n     padding-left: 0mm;\n   }\n\n @page :first {\n \t@top-center {\n\t\tcontent: element(header);\n\t}\n    margin-top: 0.700000in;\n  }\n\n  .pcs-template-header {\n\tpadding: 0 0.400000in 0 0.550000in;\n    height: 0.700000in;\n  }\n\n  .pcs-template-fill-emptydiv {\n    display: table-cell;\n    content: " ";\n    width: 100%;\n  }\n\n\n/* Additional styles for RTL compat */\n\n/* Helper Classes */\n\n.inline {\n  display: inline-block;\n}\n.v-top {\n  vertical-align: top;\n}\n.text-align-right {\n  text-align: right;\n}\n.rtl .text-align-right {\n  text-align: left;\n}\n.text-align-left {\n  text-align: left;\n}\n.rtl .text-align-left {\n  text-align: right;\n}\n.float-section-right {\n  float: right;\n}\n.rtl .float-section-right{\n  float: left;\n}\n.float-section-left {\n  float: left;\n}\n.rtl .float-section-left{\n  float: right;\n}\n\n/* Helper Classes End */\n\n.item-details-inline {\n  display: inline-block;\n  margin: 0 10px;\n  vertical-align: top;\n  max-width: 70%;\n}\n\n.total-in-words-container {\n  width: 100%;\n  margin-top: 10px;\n}\n.total-in-words-label {\n  vertical-align: top;\n  padding: 0 10px;\n}\n.total-in-words-value {\n  width: 170px;\n}\n.total-section-label {\n  padding: 5px 10px 5px 0;\n  vertical-align: middle;\n}\n.total-section-value {\n  width: 120px;\n  vertical-align: middle;\n  padding: 10px 10px 10px 5px;\n}\n.rtl .total-section-value {\n  padding: 10px 5px 10px 10px;\n}\n\n.tax-summary-description {\n  color: #727272;\n  font-size: 8pt;\n}\n\n.bharatqr-bg {\n  background-color: #f4f3f8;\n}\n\n/* Overrides/Patches for RTL compat */\n  .rtl th {\n    text-align: inherit; /* Specifically setting th as inherit for supporting RTL */\n  }\n/* Overrides/Patches End */\n\n  /* Signature styles */\n  .sign-border {\n    width: 200px;\n    border-bottom: 1px solid #000;\n  }\n  .sign-label {\n    display: table-cell;\n    font-size: 10pt;\n    padding-right: 5px;\n  }\n  /* Signature styles End */\n\n/* Subject field styles */\n.subject-block {\n    margin-top: 20px;\n}\n.subject-block-value {\n    word-wrap: break-word;\n    white-space: pre-wrap;\n    line-height: 14pt;\n    margin-top:5px;\n}\n/* Subject field styles End*/\n\n.pcs-sub-label {\n  color: #666;\n  font-size: 10px;\n}\n.pcs-hsnsummary-compact {\n  padding: 0;\n  margin-top: 3px;\n}\n.pcs-hsnsummary-label-compact {\n  margin-bottom: 3px;\n  font-weight:600;\n  padding-left: 3px;\n  font-size: 9pt;\n}\n.pcs-hsnsummary-header-compact {\n  text-align:right;\n  padding: 5px 7px 2px 7px;\n  word-wrap: break-word;\n  width: 17%;\n  height: 32px;\n  border-right: 1px solid #9E9E9E;\n  font-size: 8pt;\n  font-weight: 600;\n}\n.pcs-hsnsummary-body-compact, .pcs-hsnsummary-total-compact {\n  text-align:right;\n  word-wrap: break-word;\n  font-size: 7pt;\n  padding: 4px 10px;\n}\n.pcs-hsnsummary-total-compact {\n  border-top: 1px solid #adadad;\n}\n.pcs-ukvat-summary {\n  margin-top:50px;\n  clear: both;\n  width: 100%;\n}\n.pcs-ukvat-summary-header {\n  padding:5px 10px 5px 5px;\n}\n.pcs-ukvat-summary-header:first-child {\n  padding-left: 10px;\n}\n.pcs-ukvat-summary-label {\n  font-size: 10pt;\n}\n.pcs-ukvat-summary-table {\n  margin-top: 10px;\n  width: 100%;\n  table-layout: fixed;\n}\n.pcs-ukvat-summary-body, .pcs-ukvat-summary-total {\n  padding: 10px 10px 5px 10px;\n}\n.pcs-ukvat-summary-body:first-child {\n  padding-bottom: 10px;\n  padding-right: 0;\n}\n.pcs-payment-block {\n  margin-top: 20px;\n}\n.pcs-payment-block-inner {\n  margin-top: 10px;\n}\n\n.pcs-entity-label-section {\n  padding:5px 10px 5px 0px;\n  font-size: 10pt;\n }\n\n.pcs-colon {\n  width: 3%;\n}\n\n\n   \n\n\n.pcs-w-100 {\n  width: 100%;\n}\n\n\n\n\n\n\n\n.pcs-d-table-cell {\n  display: table-cell;\n}\n\n\n\n\n\n.pcs-talign-center {\n  text-align: center;\n}\n.pcs-wordwrap-bw {\n  word-wrap: break-word;\n}\n.pcs-whitespace-pw {\n  white-space: pre-wrap;\n}\n.pcs-fw-600 {\n  font-weight: 600;\n}\n.pcs-text-uppercase {\n  text-transform: uppercase;\n}\n\n\n\n\n\n.pcs-table-fixed {\n  table-layout:fixed;\n}\n\n\n\n\n\n.pcs-valign-middle {\n  vertical-align: middle;\n}\n\n\n\n.pcs-clearfix {\n  clear: both;\n}\n  .lineitem-column{\n    padding: 10px 10px 5px 10px;\n    word-wrap: break-word;\n  }\n  .entity-details-padding{\n    padding: 5px 10px 5px 0px;\n  }\n  .rtl .entity-details-padding{\n    padding: 5px 0px 5px 10px;\n  }\n  .line-item-padding{\n    padding: 10px 10px 10px 5px;\n  }\n  .rtl .line-item-padding{\n    padding: 10px 5px 10px 10px;\n  }\n  </style>\n<!--style_end-->\n\n<div class="pcs-template ">\n      <div id="header" class="pcs-template-header pcs-header-content" >\n    \n\n    <h1 align="right" style="text-align:right"><span lang="EN-US" style="font-size:\n10.0pt;font-family:&quot;Arial&quot;,sans-serif;font-weight:normal">KVTEK/FRM/PR/03...Rev.01<o:p></o:p></span></h1>\n    \n\n  </div>\n\n   <div class="pcs-template-body ">\n     <table style="width:100%;table-layout: fixed;">\n       <tbody>\n         <tr>\n           <td style="vertical-align: top; width:50%;">\n             <div>\n                    <img id="logo_content" style="width:74px;height:72px;" src="https://inventory.zoho.in/ZFInvoiceLogo.zbfs?logo_id=85f9b86c9358f692665d4d07b8857d0d" />\n            </div>\n            <span class="pcs-orgname"><b>KVTEK Power Systems Pvt. Ltd.</b></span><br />\n<span class="pcs-label">\n              <span id="tmp_org_address" style="white-space: pre-wrap;word-wrap: break-word;">Company ID : U74220DL2005PTC135994&#10;284-286 &amp; 290&#10;Sector-8, IMT Manesar&#10;Gurgaon Haryana 122050&#10;India&#10;GSTIN 06AABCE4590P1Z7&#10;PAN AABCE4590P</span>\n            </span>           </td>\n           <td style="vertical-align: top; width:50%;" class="text-align-right">\n             <span class="pcs-entity-title">Purchase Order</span><br />\n             <span class="pcs-label" style="font-size: 10pt;" id="tmp_entity_number"><b># K2023-089</b></span>\n             <div style="clear:both;margin-top:20px;">\n             </div>\n          </td>\n         </tr>\n       </tbody>\n      </table>\n\n     <table style="width:100%;margin-top:30px;table-layout:fixed;">\n     \t<tr>\n     \t<td style="width:55%;vertical-align:bottom;word-wrap: break-word;" >\n<div><label class="pcs-label" id="tmp_billing_address_label" style="font-size: 10pt;">Vendor Address</label>\n            <br />\n\t\t\t<span id="tmp_billing_address" style="white-space: pre-wrap;"><strong><span id="zb-pdf-customer-detail" class="pcs-customer-name">Karam Techno Solutions</span></strong>\nPlot No. 28, Turkiyawas Road , Rewari HR 123401\nGSTIN 06AHQPY5442F1ZV</span>\n    \t\t</div>           <div style="clear:both;width:50%;margin-top: 20px;">\n             <label class="pcs-label" id="tmp_shipping_address_label" style="font-size: 10pt;">Deliver To</label>\n            <br />\n           <span id="tmp_shipping_address" style="white-space: pre-wrap;">Main Store\nCompany ID : U74220DL2005PTC135994\n284 - 286, Sector 8\nGurgaon Haryana 122050\nIndia\nGSTIN 06AABCE4590P1Z7\nPANAABCE4590P</span>\n         </div>\n\n     \t</td>\n     \t<td style="vertical-align:bottom;width: 45%;" class="text-align-right">\n     \t\t<table class="float-section-right" cellpadding="0" cellspacing="0" border="0" style="width: 100%;table-layout: fixed;word-wrap: break-word;">\n                 <tbody>\n                    <tr>\n                         <td style="font-size: 10pt;width:60%;" class="text-align-right entity-details-padding">\n                            <span class="pcs-label">Shipment preference :</span>\n                        </td>\n                        <td style="width:40%;" class="text-align-right">\n                            <span>Courier</span>\n                        </td>\n                    </tr>\n                     <tr>\n                         <td style="font-size:10pt;width:60%;" class="text-align-right entity-details-padding">\n                            <span  class="pcs-label">Date :</span>\n                        </td>\n                        <td style="width:40%;" class="text-align-right">\n                            <span id="tmp_entity_date">21/04/2023</span>\n                        </td>\n                    </tr>\n\n\n                    <tr>\n                         <td style="font-size: 10pt;width:60%;" class="text-align-right entity-details-padding">\n                            <span class="pcs-label">Delivery Date :</span>\n                        </td>\n                        <td style="width:40%;" class="text-align-right">\n                            <span id="tmp_due_date">26/04/2023</span>\n                        </td>\n                    </tr>\n                    <tr>\n                         <td style="font-size: 10pt;width:60%;" class="text-align-right entity-details-padding">\n                            <span  class="pcs-label">Ref# :</span>\n                      </td>\n                      <td style="width:40%;" class="text-align-right">\n                          <span id="tmp_ref_number">Tools for CNC Machine</span>\n                      </td>\n                    </tr>\n\n                 </tbody>\n              </table>\n     \t</td>\n     \t</tr>\n     </table>\n\n  <table cellpadding="0" cellspacing="0" border="0" class="pcs-itemtable" style="width:100%;margin-top:20px;table-layout:fixed;">\n    <thead>\n        <tr style="height:32px;">\n                <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 0px 5px 5px;width: 5%;text-align: center;">\n      #\n    </td>\n    <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 10px 5px 20px;width: ;text-align: left;">\n      Item &amp; Description\n    </td>\n    <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 10px 5px 5px;width: 11%;text-align: right;">\n      MPN\n    </td>\n    <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 10px 5px 5px;width: 11%;text-align: right;">\n      Qty\n    </td>\n    <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 10px 5px 5px;width: 11%;text-align: right;">\n      Rate\n    </td>\n    <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 10px 5px 5px;width: 15%;text-align: right;">\n      Amount\n    </td>\n\n        </tr>\n     </thead>\n     <tbody class="itemBody">\n            <tr class="breakrow-inside breakrow-after">\n            <td class="pcs-item-row" style="padding: 10px 0 10px 5px;text-align: center;word-wrap: break-word;" valign="top">\n              1\n            </td>\n            <td class="pcs-item-row" style="padding: 10px 0 10px 20px;" valign="top">\n\t\t\t\t\t\t\t<div >\n\t\t\t\t\t\t\t<div  >\n               <span id="tmp_item_name" style="word-wrap: break-word;">CNC Grooing Insert GCML4002-CG-05-AC530U</span><br />\n               \n               <span id="tmp_item_description" class="pcs-item-desc" style="white-space: pre-wrap;word-wrap: break-word;">OK</span>\n               \n\t\t\t\t\t\t\t </div>\n\t\t\t\t\t\t\t</div>\n            </td>\n\n\n\n                         <td class="pcs-item-row lineitem-column text-align-right" valign="top">\n                           <span>GCML4002-CG-05-AC530U </span>\n                         </td>\n\n\n\n\n\n\n                <td class="pcs-item-row text-align-right" style="padding: 10px 10px 5px 10px;word-wrap: break-word;" valign="top">\n                  <span id="tmp_item_qty">10.00</span>\n                  <div class="pcs-item-desc">Nos</div>\n                </td>\n\n            <td class="pcs-item-row text-align-right" style="padding: 10px 10px 5px 10px;word-wrap: break-word;" valign="top">\n                  <span id="tmp_item_rate">1,303.00</span>\n            </td>\n            <td class="pcs-item-row text-align-right line-item-padding" style="word-wrap: break-word;" valign="top">\n              <span id="tmp_item_amount">13,030.00</span>\n            </td>\n          </tr>\n    </tbody>\n    </table>\n   <div style="width: 100%;margin-top: 1px;">\n    <div style="width: 45%;padding: 3px 10px 3px 3px;font-size: 9pt;" class="float-section-left">\n      <div style="white-space: pre-wrap;"></div>\n    </div>\n    <div style="width: 50%;" class="float-section-right">\n      <table width="100%" border="0"  cellspacing="0" class="pcs-totals">\n        <tbody>\n          <tr class="text-align-right">\n                <td class="entity-details-padding" valign="middle">Sub Total</td>\n                <td style="width:120px;" class="line-item-padding" valign="middle" id="tmp_subtotal">13,030.00</td>\n          </tr>\n          <tr style="height:10px;">\n            <td class="text-align-right entity-details-padding" valign="middle">SGST9 (9%)  </td>\n            <td style="width:120px;" class="text-align-right line-item-padding" valign="middle">1,172.70</td>\n          </tr>\n          <tr style="height:10px;">\n            <td class="text-align-right entity-details-padding" valign="middle">CGST9 (9%)  </td>\n            <td style="width:120px;" class="text-align-right line-item-padding" valign="middle">1,172.70</td>\n          </tr>\n\n\n\n\n          <tr>\n            <td class="text-align-right entity-details-padding" valign="middle"><b>Total</b></td>\n            <td style="width:120px;" class="text-align-right line-item-padding" valign="middle" id="tmp_total"><b>₹15,375.40</b></td>\n          </tr>\n        </tbody>\n      </table>\n    </div>\n    <div style="clear: both;"></div>\n  </div>\n\n  <div style="clear:both;margin-top:30px;width:100%;">\n  <label  class="pcs-label" id="tmp_terms_label" style="font-size: 10pt;">Terms &amp; Conditions</label><br />\n  <p class="pcs-terms" style="margin-top:7px;white-space: pre-wrap;word-wrap: break-word;">1. Prices: Ex Work &#10;2. Freight. : Extra&#10;3. Payment Terms: 100% after acceptance of material &#10;4. Delivery Schedule: 26.04.2023&#10;5. Warranty: 12 months from the date of dispatch.&#10;6. LD: Liquidated Damages shall be applicable @ 0.5% per week delay in delivery &#10;    until actual delivery up to maximum of 5.0% of the total order value.&#10;7.  Inspection/Testing: a. Inspection of Raw material to be done at vendor site.&#10;b. Inspection Required prior to dispatch/ Sample to be tested &#10;    after receiving Material.&#9;&#10;8. Documentation:  Commercial Invoice, Packing List, Material Test Report.&#10;9. Jurisdiction:&#9; Any arbitration or settlement of conflict will be within the jurisdiction &#10;                                 of the court of New Delhi only.&#10;10. Insurance: Extra</p>\n  </div>\n           <div style="page-break-inside: avoid;">\n    <div class="" style="margin-top:30px;">\n        <label class="pcs-label sign-label">Authorized Signature</label>\n        <div style="display: table-cell;">\n            <div class="sign-border inline"></div>\n            <div></div>\n        </div>\n    </div>\n</div>\n\n    \n </div>\n   <div class="pcs-template-footer">\n    <div >\n      \n    </div>  \n  </div>\n\n</div>\n',
  can_mark_as_bill: false,
  can_mark_as_unbill: false,
  purchasereceives: [],
  salesorders: [],
  bills: [],
};
