invoice = {
  invoice_id: "536460000019357001",
  invoice_number: "KVTEKSER/2223/40",
  date: "2022-10-06",
  date_formatted: "06/10/2022",
  due_date: "2022-10-06",
  due_date_formatted: "06/10/2022",
  offline_created_date_with_time: "",
  customer_id: "536460000000032006",
  customer_name: "Shirdi Sai Electricals Ltd",
  customer_custom_fields: [],
  customer_custom_field_hash: {},
  email: "testing@ssel.in",
  currency_id: "536460000000000064",
  currency_code: "INR",
  currency_symbol: "₹",
  currency_name_formatted: "INR- Indian Rupee",
  status: "paid",
  status_formatted: "Paid",
  custom_fields: [],
  custom_field_hash: {},
  recurring_invoice_id: "",
  place_of_supply: "AN",
  place_of_supply_formatted: "Andaman and Nicobar Islands",
  payment_terms: 0,
  payment_terms_label: "100 % Advance ",
  payment_reminder_enabled: true,
  payment_made: 226200.0,
  payment_made_formatted: "₹2,26,200.00",
  crm_owner_id: "",
  crm_custom_reference_id: "",
  zcrm_potential_id: "",
  zcrm_potential_name: "",
  next_retry_date: "",
  next_retry_date_formatted: "",
  next_retry_number: 0,
  reference_number: "",
  lock_details: {},
  line_items: [
    {
      line_item_id: "536460000019357003",
      item_id: "",
      sku: "",
      item_order: 0,
      product_type: "service",
      has_product_type_mismatch: false,
      has_invalid_hsn: false,
      name: "",
      description:
        "Engineering Charges\nFor diagnosing and repair of chopping\ncapacitors of impulse voltage test system.\nchopping capacitor-65000*3\n",
      unit: "",
      quantity: 3.0,
      discount_amount: 0.0,
      discount_amount_formatted: "₹0.00",
      discount: 0.0,
      discounts: [],
      bcy_rate: 65000.0,
      bcy_rate_formatted: "₹65,000.00",
      rate: 65000.0,
      rate_formatted: "₹65,000.00",
      account_id: "536460000000000486",
      account_name: "Sales",
      header_id: "",
      header_name: "",
      pricebook_id: "",
      item_total_inclusive_of_tax: 230100.0,
      item_total_inclusive_of_tax_formatted: "₹2,30,100.00",
      tax_id: "536460000000021131",
      tax_name: "IGST18",
      tax_type: "tax",
      tax_percentage: 18,
      gst_treatment_code: "",
      item_total: 195000.0,
      item_total_formatted: "₹1,95,000.00",
      item_custom_fields: [],
      tags: [],
      documents: [],
      hsn_or_sac: "998393",
      image_document_id: "",
      reverse_charge_tax_id: "",
      line_item_taxes: [
        {
          tax_id: "536460000000021131",
          tax_name: "IGST18 (18%)",
          tax_amount: 35100.0,
          tax_amount_formatted: "₹35,100.00",
        },
      ],
      bill_id: "",
      bill_item_id: "",
      is_combo_product: false,
      track_serial_for_package: false,
      track_batch_for_package: false,
      serial_numbers: [],
      batches: [],
      project_id: "",
      time_entry_ids: [],
      expense_id: "",
      item_type: "",
      item_type_formatted: "",
      expense_receipt_name: "",
      purchase_rate: "",
      purchase_rate_formatted: "",
      salesorder_item_id: "",
      can_show_in_task_table: false,
      cost_amount: 0,
      cost_amount_formatted: "₹0.00",
    },
  ],
  credits: [],
  journal_credits: [],
  exchange_rate: 1.0,
  is_autobill_enabled: false,
  inprocess_transaction_present: false,
  allow_partial_payments: false,
  price_precision: 2,
  sub_total: 195000.0,
  sub_total_formatted: "₹1,95,000.00",
  tax_total: 35100.0,
  tax_total_formatted: "₹35,100.00",
  discount_total: 0.0,
  discount_total_formatted: "₹0.00",
  discount_percent: 0.0,
  discount: 0.0,
  discount_applied_on_amount: 0.0,
  discount_type: "item_level",
  is_discount_before_tax: true,
  adjustment: 0.0,
  adjustment_formatted: "₹0.00",
  adjustment_description: "Adjustment",
  shipping_charge_tax_id: "",
  shipping_charge_tax_name: "",
  shipping_charge_tax_type: "",
  shipping_charge_tax_percentage: "",
  shipping_charge_tax_exemption_id: "",
  shipping_charge_tax_exemption_code: "",
  shipping_charge_sac_code: "",
  shipping_charge_tax: "",
  bcy_shipping_charge_tax: "",
  shipping_charge_exclusive_of_tax: 0.0,
  shipping_charge_inclusive_of_tax: 0.0,
  shipping_charge_tax_formatted: "",
  shipping_charge_exclusive_of_tax_formatted: "₹0.00",
  shipping_charge_inclusive_of_tax_formatted: "₹0.00",
  shipping_charge: 0.0,
  shipping_charge_formatted: "₹0.00",
  bcy_shipping_charge: 0.0,
  bcy_adjustment: 0.0,
  bcy_sub_total: 195000.0,
  bcy_discount_total: 0.0,
  bcy_tax_total: 35100.0,
  bcy_total: 230100.0,
  is_reverse_charge_applied: false,
  total: 230100.0,
  total_formatted: "₹2,30,100.00",
  balance: 0.0,
  balance_formatted: "₹0.00",
  write_off_amount: 0.0,
  write_off_amount_formatted: "₹0.00",
  roundoff_value: 0.0,
  roundoff_value_formatted: "₹0.00",
  transaction_rounding_type: "nearest_whole_number_rounding",
  reference_invoice_type: "",
  is_inclusive_tax: false,
  sub_total_inclusive_of_tax: 230100.0,
  sub_total_inclusive_of_tax_formatted: "₹2,30,100.00",
  tax_specification: "inter",
  gst_no: "37AAOCS9992C1ZM",
  gst_treatment: "business_gst",
  gst_treatment_formatted: "Registered Business - Regular",
  tax_reg_no: "37AAOCS9992C1ZM",
  contact_category: "business_gst",
  tax_treatment: "business_gst",
  tax_treatment_formatted: "Registered Business - Regular",
  tax_rounding: "entity_level",
  taxes: [
    {
      tax_name: "IGST18 (18%)",
      tax_amount: 35100.0,
      tax_amount_formatted: "₹35,100.00",
    },
  ],
  filed_in_vat_return_id: "",
  filed_in_vat_return_name: "",
  filed_in_vat_return_type: "",
  gst_return_details: {
    status_formatted: "",
    return_period: "",
    status: "",
    return_period_formatted: "",
  },
  reverse_charge_tax_total: 0.0,
  reverse_charge_tax_total_formatted: "₹0.00",
  can_send_invoice_sms: true,
  payment_expected_date: "",
  payment_expected_date_formatted: "",
  payment_discount: 0.0,
  payment_discount_formatted: "₹0.00",
  stop_reminder_until_payment_expected_date: false,
  last_payment_date: "2022-11-22",
  last_payment_date_formatted: "22/11/2022",
  autobill_status: "in_progress",
  autobill_status_formatted: "In Progress",
  can_show_force_pay: false,
  ach_supported: false,
  ach_payment_initiated: false,
  payment_options: { payment_gateways: [] },
  payments: [
    {
      payment_id: "536460000019357029",
      online_transaction_id: "",
      payment_number: "121",
      payment_mode: "Bank Transfer",
      invoice_payment_id: "536460000019357031",
      filed_in_vat_return_id: "",
      filed_in_vat_return_name: "",
      filed_in_vat_return_type: "",
      description:
        "Being amount received ag bill no 40 by NEFT vide UTR no SBIN222326442486",
      date: "2022-11-22",
      date_formatted: "22/11/2022",
      reference_number: "",
      exchange_rate: 1.0,
      amount: 226200.0,
      amount_formatted: "₹2,26,200.00",
      amount_refunded: 0.0,
      amount_refunded_formatted: "₹0.00",
      account_id: "536460000016222659",
      account_name: "Bank of Baroda OCC A/c 25620500001781",
      is_single_invoice_payment: true,
      last_four_digits: "",
      card_type: "",
      card_type_formatted: "",
      bank_charges: 0.0,
      bank_charges_formatted: "₹0.00",
      retainerinvoice_id: "",
      apply_date: "",
      apply_date_formatted: "",
      settlement_status: "",
      settlement_status_formatted: "",
      payment_type: "Invoice Payments",
    },
  ],
  reader_offline_payment_initiated: false,
  is_square_transaction: false,
  contact_persons: ["536460000000206586"],
  contact_persons_associated: [
    {
      contact_person_id: "536460000000206586",
      contact_person_name: "S.Siva Kumar",
      contact_person_email: "testing@ssel.in",
      phone: "8939169590",
      mobile: "9160044405",
      zcrm_contact_id: "203249000000304012",
    },
  ],
  attachment_name: "",
  documents: [],
  computation_type: "basic",
  debit_notes: [],
  deliverychallans: [],
  bills: [],
  ewaybills: [],
  dispatch_from_address: {},
  is_eway_bill_required: false,
  can_generate_ewaybill_using_irn: true,
  mark_as_shipment_status: "",
  is_standalone_invoice: true,
  merchant_id: "",
  merchant_name: "",
  merchant_gst_no: "",
  ecomm_operator_id: "",
  ecomm_operator_name: "",
  ecomm_operator_gst_no: "",
  salesorder_id: "",
  salesorder_number: "",
  salesorders: [],
  shipping_bills: [],
  unbilled_expenses_count: 0,
  unbilled_bill_items_count: 0,
  warn_convert_to_open: true,
  warn_create_creditnotes: true,
  contact_persons_details: [
    {
      contact_person_id: "536460000000206586",
      first_name: "S.Siva Kumar",
      last_name: "Reddy",
      email: "testing@ssel.in",
      phone: "8939169590",
      mobile: "9160044405",
      is_primary_contact: true,
      photo_url:
        "https://secure.gravatar.com/avatar/1f110297a66c5441bfa7e6659f865ef2?&d=mm",
    },
    {
      contact_person_id: "536460000000206593",
      first_name: "SURYA",
      last_name: "KALUGURI",
      email: "surya@ssel.in",
      phone: "9866883999",
      mobile: "9866003999",
      is_primary_contact: false,
      photo_url:
        "https://secure.gravatar.com/avatar/f29094abc29a52c700cb0ea5b6528857?&d=mm",
    },
    {
      contact_person_id: "536460000007390055",
      first_name: "Vishal",
      last_name: "Boga",
      email: "vishal.boga@ssel.in",
      phone: "7702644322",
      mobile: "",
      is_primary_contact: false,
      photo_url:
        "https://secure.gravatar.com/avatar/c5d19010260e803769a5f98e5c114a98?&d=mm",
    },
  ],
  comments: [
    {
      comment_id: "536460000019357043",
      description: "Payment of ₹2,26,200.00 received",
      commented_by_id: "536460000000024001",
      commented_by: "Girish Kumar",
      comment_type: "system",
      date: "2023-01-05",
      date_formatted: "05/01/2023 05:39 PM",
      date_with_time: "2023-01-05T17:39:05+0530",
      date_description: "108 days ago",
      time: "5:39 PM",
      operation_type: "Added",
      transaction_id: "536460000019357031",
      transaction_type: "invoice_payment",
      sentiment: "none",
    },
    {
      comment_id: "536460000019357015",
      description: "Invoice marked as sent",
      commented_by_id: "536460000000024001",
      commented_by: "Girish Kumar",
      comment_type: "system",
      date: "2023-01-05",
      date_formatted: "05/01/2023 05:36 PM",
      date_with_time: "2023-01-05T17:36:51+0530",
      date_description: "108 days ago",
      time: "5:36 PM",
      operation_type: "Updated",
      transaction_id: "",
      transaction_type: "invoice",
      sentiment: "none",
    },
    {
      comment_id: "536460000019357005",
      description: "Invoice created for ₹2,30,100.00",
      commented_by_id: "536460000000024001",
      commented_by: "Girish Kumar",
      comment_type: "system",
      date: "2023-01-05",
      date_formatted: "05/01/2023 05:36 PM",
      date_with_time: "2023-01-05T17:36:41+0530",
      date_description: "108 days ago",
      time: "5:36 PM",
      operation_type: "Added",
      transaction_id: "",
      transaction_type: "invoice",
      sentiment: "none",
    },
  ],
  salesperson_id: "",
  salesperson_name: "",
  is_emailed: false,
  reminders_sent: 0,
  last_reminder_sent_date: "",
  last_reminder_sent_date_formatted: "",
  next_reminder_date_formatted: "",
  is_portal_enabled: false,
  is_viewed_by_client: false,
  client_viewed_time: "",
  client_viewed_time_formatted: "",
  submitter_id: "",
  approver_id: "",
  submitted_date: "",
  submitted_date_formatted: "",
  submitted_by: "",
  submitted_by_name: "",
  submitted_by_email: "",
  submitted_by_photo_url: "",
  template_id: "536460000000013128",
  template_name: "Spreadsheet Template",
  template_type: "excel",
  template_type_formatted: "Spreadsheet",
  notes: "Thanks for your business.",
  terms:
    "Tax is payable under reverse charge: No\nDeclaration: We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct.\nDefault Jurisdiction : Gurugram \n",
  billing_address: {
    street: "Plot No. 13/82, Industrial Development Park,",
    address: "Plot No. 13/82, Industrial Development Park,",
    street2: "",
    city: "Kadapa",
    state: "ANDHRA PRADESH",
    zip: "516004",
    country: "INDIA",
    fax: "",
    phone: "",
    attention: "",
  },
  shipping_address: {
    street:
      "SSEL Manufacturing- Kadapa, Plot: 53-55 & 58-60, Industrial Development Park,",
    address:
      "SSEL Manufacturing- Kadapa, Plot: 53-55 & 58-60, Industrial Development Park,",
    street2: "",
    city: "Kadapa",
    state: "ANDHRA PRADESH",
    zip: "516002",
    country: "INDIA",
    fax: "",
    phone: "",
    attention: "",
  },
  html_string:
    '<!--The below style_start tag has to be present as it is used to substring the style content from the body html-->\r\n\r\n<!--style_start-->\r\n\r\n<style type="text/css" media="all">\r\n  \n\n  @font-face {\n    font-family: \'WebFont-Ubuntu\';\n    src: local(Ubuntu), url(https://fonts.gstatic.com/s/ubuntu/v10/4iCs6KVjbNBYlgoKcg72nU6AF7xm.woff2);\n  }\n\n  .pcs-template {\n  \tfont-family: Ubuntu, \'WebFont-Ubuntu\';\n    font-size: 8pt;\n    color: #000000;\n      background:  #ffffff ;\n  }\n\n  .pcs-header-content {\n    font-size: 8pt;\n\tcolor: #000000;\n\tbackground-color: #ffffff;\n  }\n  .pcs-template-body {\n  \tpadding: 0 0.400000in 0 0.550000in;\n  }\n  .pcs-template-footer {\n  \theight: 0.700000in;\n\tfont-size: 6pt;\n\tcolor: #000000;\n\tpadding: 0 0.400000in 0 0.550000in;\n\tbackground-color: #ffffff;\n  }\n  .pcs-footer-content {\n  word-wrap: break-word;\n  color: #000000;\n      border-top: 1px solid #9e9e9e;\n  }\n\n  .pcs-label {\n    color: #333333;\n  }\n  .pcs-entity-title {\n    font-size: 22pt;\n    color: #000000;\n  }\n  .pcs-orgname {\n    font-size: 12pt;\n    color: #000000;\n  }\n  .pcs-customer-name {\n    font-size: 9pt;\n    color: #000000;\n  }\n  .pcs-eori-number {\n    color: #333;\n    margin: 0;\n    padding-top: 10px;\n  }\n .pcs-itemtable-header {\n    font-size: 8pt;\n    color: #000000;\n    background-color: #f2f3f4;\n  }\n  .pcs-itemtable-breakword {\n    word-wrap: break-word;\n  }\n  .pcs-taxtable-header {\n    font-size: 8pt;\n    color: #000000;\n    background-color: #f2f3f4;\n  }\n  .breakrow-inside {\n    page-break-inside: avoid;\n  }\n  .breakrow-after {\n    page-break-after:auto;\n  }\n  .pcs-item-row {\n    font-size: 8pt;\n    border-bottom: 1px solid #9e9e9e;\n    background-color: #ffffff;\n    color: #000000;\n  }\n  .pcs-img-fit-aspectratio {\n    object-fit: contain;\n    object-position: top;\n  }\n  .pcs-img-border {\n    border: 1px solid #f5f4f3;\n  }\n  .pcs-item-sku, .pcs-item-hsn, .pcs-item-coupon, .pcs-item-serialnumber, .pcs-item-unitcode {\n    margin-top: 2px;\n  \tfont-size: 10px;\n  \tcolor: #444444;\n  }\n  .pcs-item-desc {\n      color: #333333;\n      font-size: 8pt;\n   }\n  .pcs-balance {\n    background-color: #ffffff;\n    font-size: 9pt;\n    color: #000000;\n  }\n  .pcs-savings {\n  font-size: 0pt;\n  color: ;\n  background-color: ;\n  }\n  .pcs-totals {\n    font-size: 8pt;\n    color: #000000;\n    background-color: #ffffff;\n  }\n  .pcs-notes {\n    font-size: 8pt;\n  }\n  .pcs-terms {\n    font-size: 8pt;\n  }\n  .pcs-header-first {\n\tbackground-color: #ffffff;\n\tfont-size: 8pt;\n\tcolor: #000000;\n      height: auto;\n\t}\n\n .pcs-status {\n \tcolor: ;\n\tfont-size: 15pt;\n\tborder: 3px solid ;\n\tpadding: 3px 8px;\n }\n .billto-section {\n     padding-top: 0mm;\n     padding-left: 0mm;\n   }\n   .shipto-section {\n     padding-top: 0mm;\n     padding-left: 0mm;\n   }\n\n @page :first {\n \t@top-center {\n\t\tcontent: element(header);\n\t}\n    margin-top: 0.700000in;\n  }\n\n  .pcs-template-header {\n\tpadding: 0 0.400000in 0 0.550000in;\n    height: 0.700000in;\n  }\n\n  .pcs-template-fill-emptydiv {\n    display: table-cell;\n    content: " ";\n    width: 100%;\n  }\n\n\n/* Additional styles for RTL compat */\n\n/* Helper Classes */\n\n.inline {\n  display: inline-block;\n}\n.v-top {\n  vertical-align: top;\n}\n.text-align-right {\n  text-align: right;\n}\n.rtl .text-align-right {\n  text-align: left;\n}\n.text-align-left {\n  text-align: left;\n}\n.rtl .text-align-left {\n  text-align: right;\n}\n.float-section-right {\n  float: right;\n}\n.rtl .float-section-right{\n  float: left;\n}\n.float-section-left {\n  float: left;\n}\n.rtl .float-section-left{\n  float: right;\n}\n\n/* Helper Classes End */\n\n.item-details-inline {\n  display: inline-block;\n  margin: 0 10px;\n  vertical-align: top;\n  max-width: 70%;\n}\n\n.total-in-words-container {\n  width: 100%;\n  margin-top: 10px;\n}\n.total-in-words-label {\n  vertical-align: top;\n  padding: 0 10px;\n}\n.total-in-words-value {\n  width: 170px;\n}\n.total-section-label {\n  padding: 5px 10px 5px 0;\n  vertical-align: middle;\n}\n.total-section-value {\n  width: 120px;\n  vertical-align: middle;\n  padding: 10px 10px 10px 5px;\n}\n.rtl .total-section-value {\n  padding: 10px 5px 10px 10px;\n}\n\n.tax-summary-description {\n  color: #727272;\n  font-size: 8pt;\n}\n\n.bharatqr-bg {\n  background-color: #f4f3f8;\n}\n\n/* Overrides/Patches for RTL compat */\n  .rtl th {\n    text-align: inherit; /* Specifically setting th as inherit for supporting RTL */\n  }\n/* Overrides/Patches End */\n\n  /* Signature styles */\n  .sign-border {\n    width: 200px;\n    border-bottom: 1px solid #000;\n  }\n  .sign-label {\n    display: table-cell;\n    font-size: 10pt;\n    padding-right: 5px;\n  }\n  /* Signature styles End */\n\n/* Subject field styles */\n.subject-block {\n    margin-top: 20px;\n}\n.subject-block-value {\n    word-wrap: break-word;\n    white-space: pre-wrap;\n    line-height: 14pt;\n    margin-top:5px;\n}\n/* Subject field styles End*/\n\n.pcs-sub-label {\n  color: #666;\n  font-size: 10px;\n}\n.pcs-hsnsummary-compact {\n  padding: 0;\n  margin-top: 3px;\n}\n.pcs-hsnsummary-label-compact {\n  margin-bottom: 3px;\n  font-weight:600;\n  padding-left: 3px;\n  font-size: 9pt;\n}\n.pcs-hsnsummary-header-compact {\n  text-align:right;\n  padding: 5px 7px 2px 7px;\n  word-wrap: break-word;\n  width: 17%;\n  height: 32px;\n  border-right: 1px solid #9E9E9E;\n  font-size: 8pt;\n  font-weight: 600;\n}\n.pcs-hsnsummary-body-compact, .pcs-hsnsummary-total-compact {\n  text-align:right;\n  word-wrap: break-word;\n  font-size: 7pt;\n  padding: 4px 10px;\n}\n.pcs-hsnsummary-total-compact {\n  border-top: 1px solid #9e9e9e;\n}\n.pcs-ukvat-summary {\n  margin-top:50px;\n  clear: both;\n  width: 100%;\n}\n.pcs-ukvat-summary-header {\n  padding:5px 10px 5px 5px;\n}\n.pcs-ukvat-summary-header:first-child {\n  padding-left: 10px;\n}\n.pcs-ukvat-summary-label {\n  font-size: 10pt;\n}\n.pcs-ukvat-summary-table {\n  margin-top: 10px;\n  width: 100%;\n  table-layout: fixed;\n}\n.pcs-ukvat-summary-body, .pcs-ukvat-summary-total {\n  padding: 10px 10px 5px 10px;\n}\n.pcs-ukvat-summary-body:first-child {\n  padding-bottom: 10px;\n  padding-right: 0;\n}\n.pcs-payment-block {\n  margin-top: 20px;\n}\n.pcs-payment-block-inner {\n  margin-top: 10px;\n}\n\n.pcs-entity-label-section {\n  padding:5px 10px 5px 0px;\n  font-size: 10pt;\n }\n\n.pcs-colon {\n  width: 3%;\n}\n\n\r\n  \n\n\n.pcs-w-100 {\n  width: 100%;\n}\n\n\n\n\n\n\n\n.pcs-d-table-cell {\n  display: table-cell;\n}\n\n\n\n\n\n.pcs-talign-center {\n  text-align: center;\n}\n.pcs-wordwrap-bw {\n  word-wrap: break-word;\n}\n.pcs-whitespace-pw {\n  white-space: pre-wrap;\n}\n.pcs-fw-600 {\n  font-weight: 600;\n}\n.pcs-text-uppercase {\n  text-transform: uppercase;\n}\n\n\n\n\n\n.pcs-table-fixed {\n  table-layout:fixed;\n}\n\n\n\n\n\n.pcs-valign-middle {\n  vertical-align: middle;\n}\n\n\n\n.pcs-clearfix {\n  clear: both;\n}\r\n  .pcs-template-bodysection {\r\n       border: 1px solid #9e9e9e;\r\n  }\r\n  .pcs-itemtable {\r\n    border-top: 1px solid #9e9e9e;\r\n  }\r\n  .pcs-addresstable {\r\n    width: 100%;\r\n    table-layout:fixed;\r\n  }\r\n  .pcs-addresstable > thead > tr > th {\r\n    padding: 1px 5px;\r\n    background-color: #f2f3f4;\r\n    font-weight: normal;\r\n    border-bottom: 1px solid #9e9e9e;\r\n  }\r\n  .pcs-addresstable > tbody > tr > td {\r\n    line-height: 15px;\r\n    padding: 5px 5px 0px 5px;\r\n    vertical-align:top;\r\n    word-wrap: break-word;\r\n  }\r\n\r\n  .invoice-detailstable > tbody > tr > td {\r\n    width: 50%;\r\n    vertical-align: top;\r\n    border-top: 1px solid #9e9e9e;\r\n  }\r\n\r\n  .invoice-detailstable > tbody > tr > td > span{\r\n    width: 45%;\r\n    padding: 1px 5px;\r\n    display: inline-block;\r\n    vertical-align: top;\r\n  }\r\n\r\n  .pcs-itemtable-header {\r\n    font-weight: normal;\r\n    border-right: 1px solid #9e9e9e;\r\n    border-bottom: 1px solid #9e9e9e;\r\n  }\r\n  .pcs-itemtable-subheader {\r\n    padding: 1px 5px;\r\n    text-align: right;\r\n  }\r\n  .pcs-item-row {\r\n    border-right: 1px solid #9e9e9e;\r\n    border-bottom: 1px solid #9e9e9e;\r\n  }\r\n  .pcs-itemtable tr td.pcs-itemtable-subheader:last-child {\r\n    border-right: 1px solid #9e9e9e;\r\n  }\r\n  .pcs-itemtable tr td.pcs-itemtable-subrow:last-child {\r\n    border-right: 1px solid #9e9e9e;\r\n  }\r\n  .pcs-itemtable tr td:last-child, .pcs-itemtable tr th:last-child {\r\n    border-right: 0px;\r\n  }\r\n  .pcs-itemtable tr td:first-child, .pcs-itemtable tr th:first-child {\r\n    border-left: 0px;\r\n  }\r\n  .pcs-itemtable tbody > tr > td {\r\n    padding: 1px 5px;\r\n    word-wrap: break-word;\r\n  }\r\n  .pcs-totaltable tbody > tr > td {\r\n    padding: 4px 7px 0px;\r\n    text-align: right;\r\n  }\r\n  .pcs-footer-content {\r\n    border-top: 0px;\r\n  }\r\n  #tmp_vat_summary_label {\r\n    padding: 4px 4px 3px 7px;\r\n  }\r\n  .subject-block {\r\n    margin-top: 0px;\r\n    padding: 10px;\r\n    border-top: 1px solid #9e9e9e;\r\n  }\r\n  .pcs-taxtable-header {\r\n    border-bottom: 1px solid #9e9e9e;\r\n    border-right: 1px solid #9e9e9e;\r\n  }\r\n</style>\r\n\r\n<!--style_end-->\r\n\r\n<div class="pcs-template">\r\n\t  <div id="header" class="pcs-template-header pcs-header-content" >\n    \n\n    \n    <div class="pcs-template-fill-emptydiv"></div>\n\n  </div>\n\r\n\r\n\r\n\t<div class="pcs-template-body">\r\n    <div class="pcs-template-bodysection">\r\n\t\t<table style="width: 100%;">\r\n        <tbody>\r\n          <tr>\r\n            <td style="width:10%;padding: 2px 10px;vertical-align: middle;">\r\n              <img id="logo_content" style="width:74px;height:72px;" src="https://inventory.zoho.in/ZFInvoiceLogo.zbfs?logo_id=85f9b86c9358f692665d4d07b8857d0d" />\r\n            </td>\r\n            <td style="width:50%;padding: 2px 10px;vertical-align: middle;">\r\n              <div>\r\n                <span class="pcs-orgname" style="font-weight: bold;">KVTEK Power Systems Pvt. Ltd.<br /></span>\r\n                <span id="tmp_org_address" style="white-space: pre-wrap;">Company ID : U74220DL2005PTC135994&#10;284-286 &amp; 290&#10;Sector-8, IMT Manesar&#10;Gurgaon Haryana 122050&#10;India&#10;GSTIN 06AABCE4590P1Z7&#10;PAN AABCE4590P</span>\r\n              </div>\r\n            </td>\r\n          <td align="right" style="width:40%;padding: 5px;vertical-align: bottom;">\r\n            \r\n            <div class="pcs-entity-title">TAX INVOICE</div>\r\n          </td>\r\n    </tr>\r\n  </tbody>\r\n</table>\r\n\r\n  <div style="width: 100%;">\r\n  <table class="invoice-detailstable" style="width: 100%;table-layout: fixed;word-wrap: break-word;" border="0" cellpadding="0" cellspacing="0">\r\n    <thead>\r\n      <th style="width: 50%"></th>\r\n      <th style="width: 50%"></th>\r\n    </thead>\r\n    <tbody>\r\n      <tr>\r\n        <td style="border-right: 1px solid #9e9e9e;padding-bottom: 10px;">\r\n          <span class="pcs-label">#</span>\r\n          <span id="tmp_entity_number" style="font-weight: 600;">: KVTEKSER/2223/40</span>\r\n\r\n          <span class="pcs-label">Invoice Date</span>\r\n          <span id="tmp_entity_date" style="font-weight: 600;">: 06/10/2022</span>\r\n\r\n          <span class="pcs-label">Terms</span>\r\n          <span id="tmp_payment_terms" style="font-weight: 600;">: 100 % Advance </span>\r\n\r\n          <span class="pcs-label">Due Date</span>\r\n          <span id="tmp_due_date" style="font-weight: 600;">: 06/10/2022</span>\r\n\r\n\r\n\r\n        </td>\r\n        <td style="padding-bottom: 10px;">\r\n            <span class="pcs-label">Place Of Supply</span>\r\n            <span style="font-weight: 600;">: Andaman and Nicobar Islands (35)</span>\r\n\r\n\r\n\r\n        </td>\r\n      </tr>\r\n    </tbody>\r\n  </table>\r\n  </div>\r\n\r\n  <div style="clear:both;"></div>\r\n\r\n  <table cellpadding="0" cellspacing="0" border="0" class="pcs-addresstable" style="">\r\n    <thead>\r\n      <tr>\r\n        <th style="border-right: 1px solid #9e9e9e;border-top: 1px solid #9e9e9e;"><label class="pcs-label" id="tmp_billing_address_label" style="margin-bottom: 0px;display: block;"><b>Bill To</b></label></th>\r\n        <th style="border-top: 1px solid #9e9e9e;"><label class="pcs-label" id="tmp_shipping_address_label" style="margin-bottom: 0px;display: block;"><b>Ship To</b></label></th>\r\n      </tr>\r\n    </thead>\r\n      <tbody>\r\n        <tr>\r\n        <td valign="top" style="border-right: 1px solid #9e9e9e;padding-bottom: 10px;">\r\n  \t\t\t    <span id="tmp_billing_address" style="white-space: pre-wrap;line-height: 15px;"><strong><span id="zb-pdf-customer-detail" class="pcs-customer-name">Shirdi Sai Electricals Ltd</span></strong>\nPlot No. 13/82, Industrial Development Park,\nKadapa\n516004 ANDHRA PRADESH\nINDIA\nGSTIN 37AAOCS9992C1ZM</span>\r\n        </td>\r\n        <td style="padding-bottom: 10px;">\r\n         <div>\r\n             <span id="tmp_shipping_address" style="white-space: pre-wrap;line-height: 15px;">SSEL Manufacturing- Kadapa, Plot: 53-55 &amp; 58-60, Industrial Development Park,\nKadapa\n516002 ANDHRA PRADESH\nINDIA</span>\r\n         </div>\r\n        </td>\r\n        </tr>\r\n      </tbody>\r\n    </table>\r\n\r\n\r\n  <div style="clear:both;"></div>\r\n\r\n  \r\n\r\n  <table border="0" cellpadding="0" cellspacing="0" id="itemTable" class="pcs-itemtable" style="width: 100%;table-layout:fixed;clear: both;">\r\n    <thead>\r\n      <tr style="height:17px;">\n      <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" rowspan="2" valign="bottom" style="padding: 5px 5px 2px 5px;width: 5%;text-align: center;">\n        <b>#</b>\n      </td>\n      <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" rowspan="2" valign="bottom" style="padding: 5px 7px 2px 7px;width: ;text-align: left;">\n        <b>Item &amp; Description</b>\n      </td>\n      <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" rowspan="2" valign="bottom" style="padding: 5px 7px 2px 7px;width: 10%;text-align: left;">\n        <b>HSN/SAC</b>\n      </td>\n      <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" rowspan="2" valign="bottom" style="padding: 5px 7px 2px 7px;width: 11%;text-align: right;">\n        <b>Qty</b>\n      </td>\n      <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" rowspan="2" valign="bottom" style="padding: 5px 7px 2px 7px;width: 11%;text-align: right;">\n        <b>Rate</b>\n      </td>\n      <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" colspan="2" valign="bottom" style="padding: 5px 7px 2px 7px;width: 11%;text-align: center;">\n          <b>IGST</b>\n       </td>\n      <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" rowspan="2" valign="bottom" style="padding: 5px 7px 2px 7px;width: 13%;text-align: right;">\n        <b>Amount</b>\n      </td>\n</tr>\n<tr>\n      <td class="pcs-itemtable-header pcs-itemtable-breakword pcs-itemtable-subheader">\n        <b>%</b>\n      </td>\n      <td class="pcs-itemtable-header pcs-itemtable-breakword pcs-itemtable-subheader">\n        <b>Amt</b>\n      </td>\n</tr>\n\r\n    </thead>\r\n    <tbody class="itemBody">\r\n      <tr style="height:20px;" class="breakrow-inside breakrow-after">\r\n          <td class="pcs-item-row" style="text-align: center;" valign="top" rowspan="1">\r\n            1\r\n          </td>\r\n        <td id="tmp_item_name" class="pcs-item-row" valign="top" rowspan="1">\r\n          <div >\r\n          <div >\r\n              \r\n           \r\n           \r\n           <span id="tmp_item_description" class="pcs-item-desc" style="white-space: pre-wrap;word-wrap: break-word;">Engineering Charges&#10;For diagnosing and repair of chopping&#10;capacitors of impulse voltage test system.&#10;chopping capacitor-65000*3&#10;</span><br />\r\n           \r\n           \r\n           \r\n           </div>\r\n          </div>\r\n        </td>\r\n\r\n\r\n        <td id="tmp_item_qty" class="pcs-item-row" valign="top" rowspan="1">\r\n          998393\r\n        </td>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n        <td id="tmp_item_qty" class="pcs-item-row" style="text-align: right;" valign="top" rowspan="1">\r\n          3.00\r\n        </td>\r\n\r\n        <td id="tmp_item_rate" class="pcs-item-row" style="text-align: right;" valign="top" rowspan="1">\r\n          65,000.00\r\n        </td>\r\n\r\n\r\n\r\n\r\n\r\n\r\n          <td class="pcs-item-row" style="text-align:right;" valign="top" rowspan="1">\r\n            <div>18% </div>\r\n          </td>\r\n          <td class="pcs-item-row" style="text-align:right;" valign="top" rowspan="1">\r\n            <div id="tmp_item_tax_amount">35,100.00</div>\r\n          </td>\r\n        <td id="tmp_item_amount" class="pcs-item-row" style="text-align: right;" valign="top" rowspan="1">\r\n          1,95,000.00\r\n        </td>\r\n      </tr>\r\n    </tbody>\r\n    </table>\r\n\r\n\r\n<div style="width: 100%;margin-top: 1px;">\r\n    <div style="width: 50%;padding: 4px 4px 3px 7px;float: left;">\r\n        <div style="margin:10px 0 5px">\r\n          <div style="padding-right: 10px;">Total In Words</div>\r\n          <span><b><i>Indian Rupee Two Lakh Thirty Thousand One Hundred  Only</i></b></span>\r\n        </div>\r\n          <div style="padding-top: 10px;">\r\n            <p class="pcs-notes" style="white-space: pre-wrap;word-wrap: break-word;">Thanks for your business.</p>\r\n          </div>\r\n\r\n\r\n\r\n        \r\n\r\n          <div style="clear:both;margin-top: 20px;width:100%;">\r\n            <div  class="pcs-label" id="tmp_terms_label">Terms &amp; Conditions</div>\r\n            <div class="pcs-terms" style="white-space: pre-wrap;word-wrap: break-word;">Tax is payable under reverse charge: No&#10;Declaration: We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct.&#10;Default Jurisdiction : Gurugram &#10;</div>\r\n          </div>\r\n    </div>\r\n    <div class="pcs-totals" style="width: 43.6%;float:right;">\r\n      <table width="100%" border="0"  cellspacing="0" id="itemTable" class="pcs-totaltable" style="border-left: 1px solid #9e9e9e;">\r\n        <tbody>\r\n          <tr>\r\n                <td valign="middle">Sub Total</td>\r\n                <td style="width:110px;" valign="middle" id="tmp_subtotal">1,95,000.00</td>\r\n          </tr>\r\n\r\n          \r\n\r\n\r\n\r\n          <tr style="height:10px;">\r\n            <td  align="right" valign="middle">IGST18 (18%)  </td>\r\n            <td style="width:110px;" valign="middle">35,100.00</td>\r\n          </tr>\r\n\r\n\r\n        <!-- TDS or CIS Label -->\r\n\r\n\r\n          <tr >\r\n            <td valign="middle"><b>Total</b></td>\r\n            <td style="width:110px;" valign="middle" id="tmp_total"><b>₹2,30,100.00</b></td>\r\n          </tr>\r\n\r\n\r\n          <tr style="height:10px;">\r\n            <td valign="middle">Payment Made</td>\r\n\r\n            <td style="width:110px;color: red;" valign="middle">(-) 2,26,200.00</td>\r\n          </tr>\r\n          <tr style="height:10px;">\r\n            <td valign="middle">Amount Withheld</td>\r\n\r\n            <td style="width:110px;color: red;" valign="middle">(-) 3,900.00</td>\r\n          </tr>\r\n\r\n          <tr class="pcs-balance" style="height:10px;">\r\n            <td valign="middle"><b>Balance Due</b></td>\r\n            <td style="width:110px;;" valign="middle" id="tmp_balance_due"><strong>₹0.00</strong></td>\r\n          </tr>\r\n      <tr>\r\n        <td colspan="2" style="border-bottom: 1px solid #9e9e9e;"></td>\r\n      </tr>\r\n        </tbody>\r\n        <tbody>\r\n          <tr>\r\n            <td colspan="2" style="text-align: center;padding-top: 5px;">\r\n                <div style="min-height: 75px;">\r\n                  \r\n                </div>\r\n            </td>\r\n          </tr>\r\n          <tr>\r\n            <td colspan="2" style="text-align: center;border-bottom: 1px solid #9e9e9e;">\r\n              <label class="pcs-totals" style="margin-bottom: 0px;">Authorized Signature</label>\r\n            </td>\r\n          </tr>\r\n        </tbody>\r\n      </table>\r\n    </div>\r\n    <div style="clear: both;"></div>\r\n\r\n    \r\n\r\n        \r\n        \r\n        \r\n    <div style="clear: both;"></div>\r\n  </div>\r\n    \r\n    \r\n  </div>\r\n </div>\r\n   <div class="pcs-template-footer">\n    <div >\n      \n    </div>  \n  </div>\n\r\n\r\n</div>\r\n',
  invoice_url:
    "https://zohosecurepay.in/inventory/kvtekpower/secure?CInvoiceID=2-dcdb4c9a0d6f97db48c7dd38b74a9c07442666a3ec66e190da8299095282d3a625a28b345d8b67fcfb832963483445d1044d0ab32e51b5989eec3174ae2542bc97fb8ed61cc43f4f ",
  subject_content: "",
  can_send_in_mail: false,
  created_time: "2023-01-05T17:36:41+0530",
  last_modified_time: "2023-01-05T17:39:05+0530",
  created_date: "2023-01-05",
  created_date_formatted: "05/01/2023",
  created_by_id: "536460000000024001",
  last_modified_by_id: "536460000000024001",
  page_width: "8.27in",
  page_height: "11.69in",
  orientation: "portrait",
  is_backorder: "",
  sales_channel: "direct_sales",
  is_pre_gst: false,
  type_formatted: "Tax Invoice",
  type: "invoice",
  color_code: "",
  current_sub_status_id: "",
  current_sub_status: "paid",
  current_sub_status_formatted: "Paid",
  sub_statuses: [],
  reason_for_debit_note: "others",
  reason_for_debit_note_formatted: "Others",
  estimate_id: "",
  is_client_review_settings_enabled: false,
  is_taxable: true,
  unused_credits_receivable_amount: 0.0,
  unused_credits_receivable_amount_formatted: "₹0.00",
  unused_retainer_payments: 0.0,
  unused_retainer_payments_formatted: "₹0.00",
  credits_applied: 0.0,
  credits_applied_formatted: "₹0.00",
  tax_amount_withheld: 3900.0,
  tax_amount_withheld_formatted: "₹3,900.00",
  is_cloneable: true,
  can_send_in_mail_state: false,
  schedule_time: "",
  schedule_time_formatted: "",
  no_of_copies: 1,
  show_no_of_copies: true,
  auto_reminders_configured: false,
  customer_default_billing_address: {
    zip: "516004",
    country: "INDIA",
    address: "Plot No. 13/82, Industrial Development Park,",
    city: "Kadapa",
    phone: "",
    street2: "",
    state: "ANDHRA PRADESH",
    fax: "",
    state_code: "",
  },
  can_send_comment_notification: true,
  reference_invoice: { reference_invoice_id: "" },
  includes_package_tracking_info: false,
  approvers_list: [],
};
