data = {
  code: 0,
  message: "success",
  transfer_order: {
    transfer_order_id: "536460000016005330",
    from_warehouse_id: "536460000000014524",
    from_warehouse_name: "Main Store",
    to_warehouse_id: "536460000001457059",
    to_warehouse_name: "IHV",
    date: "2021-11-01",
    date_formatted: "01/11/2021",
    transferred_date: "2021-11-01",
    transferred_date_formatted: "01/11/2021",
    description: "",
    transfer_order_number: "TO-00001",
    created_by_id: "536460000000087007",
    last_modified_by_id: "536460000016028574",
    created_by_name: "Store",
    status: "transferred",
    status_formatted: "Transferred",
    submitter_id: "",
    approver_id: "",
    submitted_date: "",
    submitted_date_formatted: "",
    submitted_by: "",
    line_items: [
      {
        line_item_id: "536460000016005338",
        item_id: "536460000009120412",
        item_order: 1,
        name: "Ferrite Core, 47 mm x 24 mm x 18 mm, Yellow/White",
        description: "",
        quantity_transfer: 5.0,
        quantity_transfer_formatted: "5.00",
        price: 82.0,
        price_formatted: "₹82.00",
        asset_price: 82.0,
        asset_price_formatted: "₹82.00",
        unit: "Nos",
        quantity_decimal_place: "",
        sku: "FFCEPE4724COF4",
        image_name: "",
        image_type: "",
        image_document_id: "",
        serial_numbers: [],
        batches: [],
      },
      {
        line_item_id: "536460000016005340",
        item_id: "536460000007620849",
        item_order: 2,
        name: "Bare Wire(Copper Rope)-2.5mm",
        description: "Bare Wire(Copper Rope)-2.5mm",
        quantity_transfer: 0.2,
        quantity_transfer_formatted: "0.20",
        price: 730.0,
        price_formatted: "₹730.00",
        asset_price: 730.0,
        asset_price_formatted: "₹730.00",
        unit: "Kg",
        quantity_decimal_place: "",
        sku: "B2WCUROPE2d5RH",
        image_name: "",
        image_type: "",
        image_document_id: "",
        serial_numbers: [],
        batches: [],
      },
      {
        line_item_id: "536460000016005342",
        item_id: "536460000007423638",
        item_order: 3,
        name: "Rittal Box 200 x 300 x 155mm(AE-1035500)",
        description: "",
        quantity_transfer: 1.0,
        quantity_transfer_formatted: "1.00",
        price: 2443.85,
        price_formatted: "₹2,443.85",
        asset_price: 2443.85,
        asset_price_formatted: "₹2,443.85",
        unit: "Nos",
        quantity_decimal_place: "",
        sku: "ER200300155MW2",
        image_name: "",
        image_type: "",
        image_document_id: "",
        serial_numbers: [],
        batches: [],
      },
      {
        line_item_id: "536460000016005344",
        item_id: "536460000009694111",
        item_order: 4,
        name: "Thimble Pipe Type 1.5 mm Black",
        description: "",
        quantity_transfer: 200.0,
        quantity_transfer_formatted: "200.00",
        price: 1.25,
        price_formatted: "₹1.25",
        asset_price: 1.25,
        asset_price_formatted: "₹1.25",
        unit: "Nos",
        quantity_decimal_place: "",
        sku: "LIFJA001m5PIH1",
        image_name: "",
        image_type: "",
        image_document_id: "",
        serial_numbers: [],
        batches: [],
      },
      {
        line_item_id: "536460000016005346",
        item_id: "536460000009700333",
        item_order: 5,
        name: "Thimble Pin type 16 mm Sleeve",
        description: "",
        quantity_transfer: 10.0,
        quantity_transfer_formatted: "10.00",
        price: 6.43,
        price_formatted: "₹6.43",
        asset_price: 6.43,
        asset_price_formatted: "₹6.43",
        unit: "Nos",
        quantity_decimal_place: "",
        sku: "LPTJA00016PTH1",
        image_name: "",
        image_type: "",
        image_document_id: "",
        serial_numbers: [],
        batches: [],
      },
    ],
    documents: [],
    delivery_challans: [],
    comments: [
      {
        comment_id: "536460000016250389",
        description: "Transfer Order has been received.",
        commented_by_id: "536460000016028574",
        commented_by: "IHV Department",
        comment_type: "system",
        date: "2021-12-27",
        date_formatted: "27/12/2021 02:52 PM",
        date_description: "about a year ago",
        time: "2:52 PM",
        operation_type: "Updated",
      },
      {
        comment_id: "536460000016005364",
        description: "Transfer Order added.",
        commented_by_id: "536460000000087007",
        commented_by: "Store",
        comment_type: "system",
        date: "2021-11-09",
        date_formatted: "09/11/2021 04:28 PM",
        date_description: "about a year ago",
        time: "4:28 PM",
        operation_type: "Added",
      },
    ],
    custom_fields: [],
    custom_field_hash: {},
    tracking_number: "",
    tracking_link: "",
    carrier: "",
    delivery_method: "",
    delivery_method_id: "",
    is_tracking_enabled: false,
    tracking_statuses: [],
    created_time: "2021-11-09T16:28:13+0530",
    created_time_formatted: "09/11/2021 04:28 PM",
    last_modified_time: "2021-12-27T14:52:11+0530",
    last_modified_time_formatted: "27/12/2021 02:52 PM",
    html_string:
      '<!--The below style_start tag has to be present as it is used to substring the style content from the body html-->\n\n<!--style_start-->\n<style type="text/css" media="all">\n    \n\n  @font-face {\n    font-family: \'WebFont-Ubuntu\';\n    src: local(Ubuntu), url(https://fonts.gstatic.com/s/ubuntu/v10/4iCs6KVjbNBYlgoKcg72nU6AF7xm.woff2);\n  }\n\n  .pcs-template {\n  \tfont-family: Ubuntu, \'WebFont-Ubuntu\';\n    font-size: 9pt;\n    color: #333333;\n      background:  #ffffff ;\n  }\n\n  .pcs-header-content {\n    font-size: 9pt;\n\tcolor: #333333;\n\tbackground-color: #ffffff;\n  }\n  .pcs-template-body {\n  \tpadding: 0 0.400000in 0 0.550000in;\n  }\n  .pcs-template-footer {\n  \theight: 0.700000in;\n\tfont-size: 6pt;\n\tcolor: #aaaaaa;\n\tpadding: 0 0.400000in 0 0.550000in;\n\tbackground-color: #ffffff;\n  }\n  .pcs-footer-content {\n  word-wrap: break-word;\n  color: #aaaaaa;\n      border-top: 1px solid #adadad;\n  }\n\n  .pcs-label {\n    color: #333333;\n  }\n  .pcs-entity-title {\n    font-size: 28pt;\n    color: #000000;\n  }\n  .pcs-orgname {\n    font-size: 10pt;\n    color: #333333;\n  }\n  .pcs-customer-name {\n    font-size: 9pt;\n    color: #333333;\n  }\n  .pcs-eori-number {\n    color: #333;\n    margin: 0;\n    padding-top: 10px;\n  }\n .pcs-itemtable-header {\n    font-size: 9pt;\n    color: #ffffff;\n    background-color: #3c3d3a;\n  }\n  .pcs-itemtable-breakword {\n    word-wrap: break-word;\n  }\n  .pcs-taxtable-header {\n    font-size: 9pt;\n    color: #ffffff;\n    background-color: #3c3d3a;\n  }\n  .breakrow-inside {\n    page-break-inside: avoid;\n  }\n  .breakrow-after {\n    page-break-after:auto;\n  }\n  .pcs-item-row {\n    font-size: 9pt;\n    border-bottom: 1px solid #adadad;\n    background-color: #ffffff;\n    color: #000000;\n  }\n  .pcs-img-fit-aspectratio {\n    object-fit: contain;\n    object-position: top;\n  }\n  .pcs-img-border {\n    border: 1px solid #f5f4f3;\n  }\n  .pcs-item-sku, .pcs-item-hsn, .pcs-item-coupon, .pcs-item-serialnumber, .pcs-item-unitcode {\n    margin-top: 2px;\n  \tfont-size: 10px;\n  \tcolor: #444444;\n  }\n  .pcs-item-desc {\n      color: #727272;\n      font-size: 9pt;\n   }\n  .pcs-balance {\n    background-color: #f5f4f3;\n    font-size: 9pt;\n    color: #000000;\n  }\n  .pcs-savings {\n  font-size: 0pt;\n  color: ;\n  background-color: ;\n  }\n  .pcs-totals {\n    font-size: 9pt;\n    color: #000000;\n    background-color: #ffffff;\n  }\n  .pcs-notes {\n    font-size: 8pt;\n  }\n  .pcs-terms {\n    font-size: 8pt;\n  }\n  .pcs-header-first {\n\tbackground-color: #ffffff;\n\tfont-size: 9pt;\n\tcolor: #333333;\n      height: auto;\n\t}\n\n .pcs-status {\n \tcolor: ;\n\tfont-size: 15pt;\n\tborder: 3px solid ;\n\tpadding: 3px 8px;\n }\n .billto-section {\n     padding-top: mm;\n     padding-left: mm;\n   }\n   .shipto-section {\n     padding-top: mm;\n     padding-left: mm;\n   }\n\n @page :first {\n \t@top-center {\n\t\tcontent: element(header);\n\t}\n    margin-top: 0.700000in;\n  }\n\n  .pcs-template-header {\n\tpadding: 0 0.400000in 0 0.550000in;\n    height: 0.700000in;\n  }\n\n  .pcs-template-fill-emptydiv {\n    display: table-cell;\n    content: " ";\n    width: 100%;\n  }\n\n\n/* Additional styles for RTL compat */\n\n/* Helper Classes */\n\n.inline {\n  display: inline-block;\n}\n.v-top {\n  vertical-align: top;\n}\n.text-align-right {\n  text-align: right;\n}\n.rtl .text-align-right {\n  text-align: left;\n}\n.text-align-left {\n  text-align: left;\n}\n.rtl .text-align-left {\n  text-align: right;\n}\n.float-section-right {\n  float: right;\n}\n.rtl .float-section-right{\n  float: left;\n}\n.float-section-left {\n  float: left;\n}\n.rtl .float-section-left{\n  float: right;\n}\n\n/* Helper Classes End */\n\n.item-details-inline {\n  display: inline-block;\n  margin: 0 10px;\n  vertical-align: top;\n  max-width: 70%;\n}\n\n.total-in-words-container {\n  width: 100%;\n  margin-top: 10px;\n}\n.total-in-words-label {\n  vertical-align: top;\n  padding: 0 10px;\n}\n.total-in-words-value {\n  width: 170px;\n}\n.total-section-label {\n  padding: 5px 10px 5px 0;\n  vertical-align: middle;\n}\n.total-section-value {\n  width: 120px;\n  vertical-align: middle;\n  padding: 10px 10px 10px 5px;\n}\n.rtl .total-section-value {\n  padding: 10px 5px 10px 10px;\n}\n\n.tax-summary-description {\n  color: #727272;\n  font-size: 8pt;\n}\n\n.bharatqr-bg {\n  background-color: #f4f3f8;\n}\n\n/* Overrides/Patches for RTL compat */\n  .rtl th {\n    text-align: inherit; /* Specifically setting th as inherit for supporting RTL */\n  }\n/* Overrides/Patches End */\n\n  /* Signature styles */\n  .sign-border {\n    width: 200px;\n    border-bottom: 1px solid #000;\n  }\n  .sign-label {\n    display: table-cell;\n    font-size: 10pt;\n    padding-right: 5px;\n  }\n  /* Signature styles End */\n\n/* Subject field styles */\n.subject-block {\n    margin-top: 20px;\n}\n.subject-block-value {\n    word-wrap: break-word;\n    white-space: pre-wrap;\n    line-height: 14pt;\n    margin-top:5px;\n}\n/* Subject field styles End*/\n\n.pcs-sub-label {\n  color: #666;\n  font-size: 10px;\n}\n.pcs-hsnsummary-compact {\n  padding: 0;\n  margin-top: 3px;\n}\n.pcs-hsnsummary-label-compact {\n  margin-bottom: 3px;\n  font-weight:600;\n  padding-left: 3px;\n  font-size: 9pt;\n}\n.pcs-hsnsummary-header-compact {\n  text-align:right;\n  padding: 5px 7px 2px 7px;\n  word-wrap: break-word;\n  width: 17%;\n  height: 32px;\n  border-right: 1px solid #9E9E9E;\n  font-size: 8pt;\n  font-weight: 600;\n}\n.pcs-hsnsummary-body-compact, .pcs-hsnsummary-total-compact {\n  text-align:right;\n  word-wrap: break-word;\n  font-size: 7pt;\n  padding: 4px 10px;\n}\n.pcs-hsnsummary-total-compact {\n  border-top: 1px solid #adadad;\n}\n.pcs-ukvat-summary {\n  margin-top:50px;\n  clear: both;\n  width: 100%;\n}\n.pcs-ukvat-summary-header {\n  padding:5px 10px 5px 5px;\n}\n.pcs-ukvat-summary-header:first-child {\n  padding-left: 10px;\n}\n.pcs-ukvat-summary-label {\n  font-size: 10pt;\n}\n.pcs-ukvat-summary-table {\n  margin-top: 10px;\n  width: 100%;\n  table-layout: fixed;\n}\n.pcs-ukvat-summary-body, .pcs-ukvat-summary-total {\n  padding: 10px 10px 5px 10px;\n}\n.pcs-ukvat-summary-body:first-child {\n  padding-bottom: 10px;\n  padding-right: 0;\n}\n.pcs-payment-block {\n  margin-top: 20px;\n}\n.pcs-payment-block-inner {\n  margin-top: 10px;\n}\n\n.pcs-entity-label-section {\n  padding:5px 10px 5px 0px;\n  font-size: 10pt;\n }\n\n.pcs-colon {\n  width: 3%;\n}\n\n\n    \n\n\n.pcs-w-100 {\n  width: 100%;\n}\n\n\n\n\n\n\n\n.pcs-d-table-cell {\n  display: table-cell;\n}\n\n\n\n\n\n.pcs-talign-center {\n  text-align: center;\n}\n.pcs-wordwrap-bw {\n  word-wrap: break-word;\n}\n.pcs-whitespace-pw {\n  white-space: pre-wrap;\n}\n.pcs-fw-600 {\n  font-weight: 600;\n}\n.pcs-text-uppercase {\n  text-transform: uppercase;\n}\n\n\n\n\n\n.pcs-table-fixed {\n  table-layout:fixed;\n}\n\n\n\n\n\n.pcs-valign-middle {\n  vertical-align: middle;\n}\n\n\n\n.pcs-clearfix {\n  clear: both;\n}\n    .pcs-details-label {\n        text-align: right;\n        padding: 3px 10px 3px 0px;\n    }\n\n    .pcs-lineitem-column {\n        padding: 10px 10px 5px 10px;\n        word-wrap: break-word;\n    }\n\n    .pcs-notes {\n        margin-top: 7px;\n        white-space: pre-wrap;\n        word-wrap: break-word;\n    }\n</style>\n\n<!--style_end-->\n\n<div class="pcs-template">\n      <div id="header" class="pcs-template-header pcs-header-content" >\n    \n\n    \n    <div class="pcs-template-fill-emptydiv"></div>\n\n  </div>\n\n    <div class="pcs-template-body ">\n        <table style="width:100%;table-layout:fixed;">\n            <tbody>\n                <tr>\n                    <td style="vertical-align: top; width:50%;">\n                        <div>\n                            <img id="logo_content" style="width:74.00px;height:72.00px;" src="https://inventory.zoho.in/ZFInvoiceLogo.zbfs?logo_id=85f9b86c9358f692665d4d07b8857d0d" />\n                        </div>\n                    </td>\n                    <td style="vertical-align: top; width:50%;" class="text-align-right">\n                        <span class="pcs-entity-title">TRANSFER ORDER</span><br />\n                        <span class="pcs-label" style="font-size: 10pt;" id="tmp_entity_number">TransferOrder# TO-00001</span>\n                    </td>\n                </tr>\n            </tbody>\n        </table>\n        <table style="width:100%;table-layout:fixed;">\n            <tbody>\n                <tr>\n                    <td style="width:65%;vertical-align:top;word-wrap: break-word;">\n                        <div style="margin-bottom: 20px;">\n                            <b>KVTEK Power Systems Pvt. Ltd.</b><br/>\n<span class="pcs-label">\n                                <span id="tmp_org_address" style="white-space: pre-wrap;">Company ID : U74220DL2005PTC135994&#10;284-286 &amp; 290&#10;Sector-8, IMT Manesar&#10;Gurgaon Haryana 122050&#10;India&#10;GSTIN 06AABCE4590P1Z7&#10;PAN AABCE4590P</span>\n                            </span>                        </div>\n                    </td>\n                    <td style="vertical-align:top;width: 35%;">\n                        <table cellpadding="0" cellspacing="0" border="0" style="width: 100%;text-align: right;table-layout: fixed;word-wrap: break-word;">\n                            <tbody>\n                                <tr>\n                                    <td class="pcs-details-label pcs-label">\n                                        Date\n                                    </td>\n                                    <td style="font-weight:600;">\n                                        01/11/2021\n                                    </td>\n                                </tr>\n                                <tr>\n                                    <td class="pcs-details-label pcs-label">\n                                        Date of Transfer\n                                    </td>\n                                    <td style="font-weight:600;">\n                                        01/11/2021\n                                    </td>\n                                </tr>\n                                <tr>\n                                    <td class="pcs-details-label pcs-label">\n                                        Created By\n                                    </td>\n                                    <td style="font-weight:600;">\n                                        Store\n                                    </td>\n                                </tr>\n                            </tbody>\n                        </table>\n                    </td>\n                </tr>\n            </tbody>\n        </table>\n        <table style="width:100%;margin-top:40px;table-layout:fixed;">\n            <tr>\n                <td style="width:40%;vertical-align:top;word-wrap: break-word;">\n                    <label class="pcs-label" id="tmp_billing_address_label"><b>Source Warehouse</b></label><br/>\n                    <span id="tmp_billing_address" style="white-space: pre-wrap;padding-top:6px;">Main Store\nCompany ID : U74220DL2005PTC135994\n284 - 286, Sector 8\nGurgaon Haryana 122050\nIndia\nGSTIN 06AABCE4590P1Z7\nPAN AABCE4590P</span>\n                </td>\n                <td style="width:60%;vertical-align:top;word-wrap: break-word;  border-left: 1px solid #CCC;padding-left: 30px;">\n                    <label class="pcs-label" id="tmp_shipping_address"><b>Destination Warehouse</b></label><br/>\n                    <span id="tmp_shipping_address" style="white-space: pre-wrap;font_size:9pt;padding-top:6px;">IHV\nCompany ID : U74220DL2005PTC135994\n284-286\nSector 8, IMT Manesar\nGurgaon Haryana 122050\nIndia\nGSTIN 06AABCE4590P1Z7\nPAN AABCE4590P</span>\n                </td>\n\n            </tr>\n\n        </table>\n\n        <table cellpadding="0" cellspacing="0" border="0" class="pcs-itemtable" style="width:100%;margin-top:20px;table-layout:fixed;">\n            <thead>\n                <tr style="height:32px;">\n                        <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 0px 5px 5px;width: 5%;text-align: center;">\n      #\n    </td>\n    <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 10px 5px 20px;width: ;text-align: left;">\n      Item &amp; Description\n    </td>\n    <td class="pcs-itemtable-header pcs-itemtable-breakword" id="" style="padding: 5px 10px 5px 5px;width: 11%;text-align: right;">\n      Qty\n    </td>\n\n                </tr>\n            </thead>\n            <tbody class="itemBody">\n                <tr class="breakrow-inside breakrow-after">\n                    <td class="pcs-item-row" style="padding: 10px 0 10px 5px;text-align: center;word-wrap: break-word;" valign="top" rowspan="1">\n                        1\n                    </td>\n                    <td class="pcs-item-row" style="padding: 10px 0px 10px 20px;" valign="top" rowspan="1">\n                        <div >\n                            <div >\n                                <span id="tmp_item_name" style="word-wrap: break-word;">Ferrite Core, 47 mm x 24 mm x 18 mm, Yellow/White</span><br />\n                                \n                                <span id="tmp_item_description" class="pcs-item-desc" style="white-space: pre-wrap;word-wrap: break-word;"></span>\n                            </div>\n                        </div>\n                    </td>\n                    <td class="pcs-item-row pcs-lineitem-column text-align-right" valign="top" rowspan="1">\n                        <span id="tmp_item_qty">5.00</span>\n                        <div class="pcs-item-desc">Nos</div>\n                    </td>\n                </tr>\n                <tr class="breakrow-inside breakrow-after">\n                    <td class="pcs-item-row" style="padding: 10px 0 10px 5px;text-align: center;word-wrap: break-word;" valign="top" rowspan="1">\n                        2\n                    </td>\n                    <td class="pcs-item-row" style="padding: 10px 0px 10px 20px;" valign="top" rowspan="1">\n                        <div >\n                            <div >\n                                <span id="tmp_item_name" style="word-wrap: break-word;">Bare Wire(Copper Rope)-2.5mm</span><br />\n                                \n                                <span id="tmp_item_description" class="pcs-item-desc" style="white-space: pre-wrap;word-wrap: break-word;">Bare Wire(Copper Rope)-2.5mm</span>\n                            </div>\n                        </div>\n                    </td>\n                    <td class="pcs-item-row pcs-lineitem-column text-align-right" valign="top" rowspan="1">\n                        <span id="tmp_item_qty">0.20</span>\n                        <div class="pcs-item-desc">Kg</div>\n                    </td>\n                </tr>\n                <tr class="breakrow-inside breakrow-after">\n                    <td class="pcs-item-row" style="padding: 10px 0 10px 5px;text-align: center;word-wrap: break-word;" valign="top" rowspan="1">\n                        3\n                    </td>\n                    <td class="pcs-item-row" style="padding: 10px 0px 10px 20px;" valign="top" rowspan="1">\n                        <div >\n                            <div >\n                                <span id="tmp_item_name" style="word-wrap: break-word;">Rittal Box 200 x 300 x 155mm(AE-1035500)</span><br />\n                                \n                                <span id="tmp_item_description" class="pcs-item-desc" style="white-space: pre-wrap;word-wrap: break-word;"></span>\n                            </div>\n                        </div>\n                    </td>\n                    <td class="pcs-item-row pcs-lineitem-column text-align-right" valign="top" rowspan="1">\n                        <span id="tmp_item_qty">1.00</span>\n                        <div class="pcs-item-desc">Nos</div>\n                    </td>\n                </tr>\n                <tr class="breakrow-inside breakrow-after">\n                    <td class="pcs-item-row" style="padding: 10px 0 10px 5px;text-align: center;word-wrap: break-word;" valign="top" rowspan="1">\n                        4\n                    </td>\n                    <td class="pcs-item-row" style="padding: 10px 0px 10px 20px;" valign="top" rowspan="1">\n                        <div >\n                            <div >\n                                <span id="tmp_item_name" style="word-wrap: break-word;">Thimble Pipe Type 1.5 mm Black</span><br />\n                                \n                                <span id="tmp_item_description" class="pcs-item-desc" style="white-space: pre-wrap;word-wrap: break-word;"></span>\n                            </div>\n                        </div>\n                    </td>\n                    <td class="pcs-item-row pcs-lineitem-column text-align-right" valign="top" rowspan="1">\n                        <span id="tmp_item_qty">200.00</span>\n                        <div class="pcs-item-desc">Nos</div>\n                    </td>\n                </tr>\n                <tr class="breakrow-inside breakrow-after">\n                    <td class="pcs-item-row" style="padding: 10px 0 10px 5px;text-align: center;word-wrap: break-word;" valign="top" rowspan="1">\n                        5\n                    </td>\n                    <td class="pcs-item-row" style="padding: 10px 0px 10px 20px;" valign="top" rowspan="1">\n                        <div >\n                            <div >\n                                <span id="tmp_item_name" style="word-wrap: break-word;">Thimble Pin type 16 mm Sleeve</span><br />\n                                \n                                <span id="tmp_item_description" class="pcs-item-desc" style="white-space: pre-wrap;word-wrap: break-word;"></span>\n                            </div>\n                        </div>\n                    </td>\n                    <td class="pcs-item-row pcs-lineitem-column text-align-right" valign="top" rowspan="1">\n                        <span id="tmp_item_qty">10.00</span>\n                        <div class="pcs-item-desc">Nos</div>\n                    </td>\n                </tr>\n            </tbody>\n        </table>\n        <div style="page-break-inside: avoid;">\n    <div class="" style="margin-top:30px;">\n        <label class="pcs-label sign-label">Authorized Signature</label>\n        <div style="display: table-cell;">\n            <div class="sign-border inline"></div>\n            <div></div>\n        </div>\n    </div>\n</div>\n\n    </div>\n      <div class="pcs-template-footer">\n    <div >\n      \n    </div>  \n  </div>\n\n</div>',
  },
  warehouses: [
    {
      warehouse_id: "536460000001457059",
      warehouse_name: "IHV",
      attention: "",
      address: "284-286",
      address1: "284-286",
      address2: "Sector 8, IMT Manesar",
      city: "Gurgaon",
      state: "Haryana",
      state_code: "HR",
      country: "India",
      zip: "122050",
      phone: "1244971300",
      email: "s.maurya@kvtek.in",
      is_primary: false,
      status: "active",
      status_formatted: "Active",
      is_fba_warehouse: false,
      sales_channels: [],
    },
    {
      warehouse_id: "536460000000014524",
      warehouse_name: "Main Store",
      attention: "",
      address: "284 - 286, Sector 8",
      address1: "284 - 286, Sector 8",
      address2: "",
      city: "Gurgaon",
      state: "Haryana",
      state_code: "HR",
      country: "India",
      zip: "122050",
      phone: "",
      email: "it.kvtek@outlook.com",
      is_primary: false,
      status: "active",
      status_formatted: "Active",
      is_fba_warehouse: false,
      sales_channels: [],
    },
  ],
};
