vendor_credit = {
  vendor_credit_id: "536460000019881095",
  vendor_credit_number: "1145",
  date: "2022-12-21",
  date_formatted: "21/12/2022",
  status: "closed",
  status_formatted: "Closed",
  color_code: "",
  current_sub_status_id: "",
  current_sub_status: "closed",
  current_sub_status_formatted: "Closed",
  sub_statuses: [],
  reference_number: "",
  vendor_id: "536460000016036161",
  vendor_name: "Enerdrive GmbH",
  currency_id: "536460000000000064",
  currency_code: "INR",
  currency_symbol: "₹",
  exchange_rate: 1.0,
  price_precision: 2,
  source_of_supply: "",
  source_of_supply_formatted: "",
  destination_of_supply: "HR",
  destination_of_supply_formatted: "Haryana",
  is_inclusive_tax: false,
  tax_rounding: "entity_level",
  is_pre_gst: false,
  gst_no: "",
  reference_invoice_type: "export_with_payment",
  reason_for_debit_note: "others",
  reason_for_debit_note_formatted: "Others",
  bill_id: "536460000019002407",
  bill_number: "2210-4-000",
  contact_category: "overseas",
  tax_treatment: "overseas",
  tax_treatment_formatted: "Overseas",
  gst_treatment: "overseas",
  gst_treatment_formatted: "Overseas",
  gst_return_details: {
    status_formatted: "",
    return_period: "",
    status: "",
    return_period_formatted: "",
  },
  filed_in_vat_return_id: "",
  filed_in_vat_return_name: "",
  filed_in_vat_return_type: "",
  is_reverse_charge_applied: false,
  line_items: [
    {
      item_id: "",
      line_item_id: "536460000019881097",
      sku: "",
      account_id: "536460000017702641",
      account_name: "Loss /profit on Exchange Rate",
      name: "",
      description: "Exchange Difference",
      item_order: 1,
      itc_eligibility: "eligible",
      gst_treatment_code: "",
      quantity: 1.0,
      image_document_id: "",
      unit: "",
      bcy_rate: 1145.75,
      bcy_rate_formatted: "₹1,145.75",
      rate: 1145.75,
      rate_formatted: "₹1,145.75",
      pricebook_id: "",
      tax_id: "",
      tax_exemption_id: "",
      tax_exemption_code: "",
      tax_name: "",
      tax_type: "tax",
      tax_percentage: 0,
      line_item_taxes: [],
      item_total: 1145.75,
      item_total_formatted: "₹1,145.75",
      item_total_inclusive_of_tax: 1145.75,
      item_total_inclusive_of_tax_formatted: "₹1,145.75",
      product_type: "service",
      item_type: "",
      item_type_formatted: "",
      has_product_type_mismatch: false,
      hsn_or_sac: "",
      reverse_charge_tax_id: "",
      tags: [],
      item_custom_fields: [],
      serial_numbers: [],
      batches: [],
      project_id: "",
      is_combo_product: false,
    },
  ],
  submitted_date: "2023-03-13",
  submitted_date_formatted: "13/03/2023",
  submitter_id: "536460000000024001",
  submitted_by: "Girish Kumar (girish@kvtek.in)",
  submitted_by_name: "Girish Kumar",
  submitted_by_email: "girish@kvtek.in",
  submitted_by_photo_url:
    "https://contacts.zoho.in/file?t=user&ID=60008794037&fs=thumb",
  approver_id: "536460000000024001",
  documents: [],
  custom_fields: [],
  custom_field_hash: {},
  adjustment: 0.0,
  adjustment_formatted: "₹0.00",
  adjustment_description: "Adjustment",
  discount_setting: "flat",
  discount_amount_formatted: "₹0.00",
  discount_amount: 0.0,
  discount: 0.0,
  discount_applied_on_amount_formatted: "₹0.00",
  discount_applied_on_amount: 0.0,
  is_discount_before_tax: true,
  discount_account_id: "",
  sub_total: 1145.75,
  sub_total_formatted: "₹1,145.75",
  sub_total_inclusive_of_tax: 1145.75,
  sub_total_inclusive_of_tax_formatted: "₹1,145.75",
  total: 1145.75,
  total_formatted: "₹1,145.75",
  total_credits_used: 1145.75,
  total_refunded_amount: 0.0,
  balance: 0.0,
  balance_formatted: "₹0.00",
  taxes: [],
  tax_override: false,
  notes: "being exchange rate difference on import of EURO 695",
  comments: [
    {
      comment_id: "536460000019881137",
      vendor_credit_id: "536460000019881095",
      description: "Credits applied to bill 2210-4-000",
      commented_by_id: "536460000000024001",
      commented_by: "Girish Kumar",
      comment_type: "system",
      date: "2023-03-13",
      date_formatted: "13/03/2023 04:16 PM",
      date_description: "41 days ago",
      time: "4:16 PM",
      operation_type: "Added",
      transaction_id: "536460000019881133",
      transaction_type: "vendor_credit_bill",
    },
    {
      comment_id: "536460000019881129",
      vendor_credit_id: "536460000019881095",
      description: "Vendor credit approved.",
      commented_by_id: "536460000000024001",
      commented_by: "Girish Kumar",
      comment_type: "system",
      date: "2023-03-13",
      date_formatted: "13/03/2023 04:16 PM",
      date_description: "41 days ago",
      time: "4:16 PM",
      operation_type: "Updated",
      transaction_id: "",
      transaction_type: "vendor_credit",
    },
    {
      comment_id: "536460000019881111",
      vendor_credit_id: "536460000019881095",
      description: "Vendor credit submitted for approval.",
      commented_by_id: "536460000000024001",
      commented_by: "Girish Kumar",
      comment_type: "system",
      date: "2023-03-13",
      date_formatted: "13/03/2023 04:16 PM",
      date_description: "41 days ago",
      time: "4:16 PM",
      operation_type: "Updated",
      transaction_id: "",
      transaction_type: "vendor_credit",
    },
    {
      comment_id: "536460000019881103",
      vendor_credit_id: "536460000019881095",
      description: "Vendor credits created for ₹1,145.75 from Bill 2210-4-000",
      commented_by_id: "536460000000024001",
      commented_by: "Girish Kumar",
      comment_type: "system",
      date: "2023-03-13",
      date_formatted: "13/03/2023 04:16 PM",
      date_description: "41 days ago",
      time: "4:16 PM",
      operation_type: "Added",
      transaction_id: "",
      transaction_type: "vendor_credit",
    },
  ],
  vendor_credit_refunds: [],
  bills_credited: [
    {
      bill_id: "536460000019002407",
      vendor_credit_bill_id: "536460000019881133",
      is_opening_balance: false,
      date: "2022-12-21",
      date_formatted: "21/12/2022",
      bill_number: "2210-4-000",
      amount: 1145.75,
      amount_formatted: "₹1,145.75",
    },
  ],
  created_time: "2023-03-13T16:16:29+0530",
  last_modified_time: "2023-03-13T16:16:30+0530",
  template_id: "536460000000000243",
  template_name: "Standard Template",
  page_width: "8.27in",
  page_height: "11.69in",
  orientation: "portrait",
  template_type: "standard",
  template_type_formatted: "Standard",
  html_string:
    '\n<!--The below style_start tag has to be present as it is used to substring the style content from the body html-->\n\n<!--style_start-->\n<style type="text/css" media="all">\n \t\n\n  @font-face {\n    font-family: \'WebFont-Ubuntu\';\n    src: local(Ubuntu), url(https://fonts.gstatic.com/s/ubuntu/v10/4iCs6KVjbNBYlgoKcg72nU6AF7xm.woff2);\n  }\n\n  .pcs-template {\n  \tfont-family: Ubuntu, \'WebFont-Ubuntu\';\n    font-size: 9pt;\n    color: #333333;\n      background:  #ffffff ;\n  }\n\n  .pcs-header-content {\n    font-size: 9pt;\n\tcolor: #333333;\n\tbackground-color: #ffffff;\n  }\n  .pcs-template-body {\n  \tpadding: 0 0.400000in 0 0.550000in;\n  }\n  .pcs-template-footer {\n  \theight: 0.700000in;\n\tfont-size: 6pt;\n\tcolor: #aaaaaa;\n\tpadding: 0 0.400000in 0 0.550000in;\n\tbackground-color: #ffffff;\n  }\n  .pcs-footer-content {\n  word-wrap: break-word;\n  color: #aaaaaa;\n      border-top: 1px solid #adadad;\n  }\n\n  .pcs-label {\n    color: #333333;\n  }\n  .pcs-entity-title {\n    font-size: 28pt;\n    color: #000000;\n  }\n  .pcs-orgname {\n    font-size: 10pt;\n    color: #333333;\n  }\n  .pcs-customer-name {\n    font-size: 9pt;\n    color: #333333;\n  }\n  .pcs-eori-number {\n    color: #333;\n    margin: 0;\n    padding-top: 10px;\n  }\n .pcs-itemtable-header {\n    font-size: 9pt;\n    color: #ffffff;\n    background-color: #3c3d3a;\n  }\n  .pcs-itemtable-breakword {\n    word-wrap: break-word;\n  }\n  .pcs-taxtable-header {\n    font-size: 9pt;\n    color: #ffffff;\n    background-color: #3c3d3a;\n  }\n  .breakrow-inside {\n    page-break-inside: avoid;\n  }\n  .breakrow-after {\n    page-break-after:auto;\n  }\n  .pcs-item-row {\n    font-size: 9pt;\n    border-bottom: 1px solid #adadad;\n    background-color: #ffffff;\n    color: #000000;\n  }\n  .pcs-img-fit-aspectratio {\n    object-fit: contain;\n    object-position: top;\n  }\n  .pcs-img-border {\n    border: 1px solid #f5f4f3;\n  }\n  .pcs-item-sku, .pcs-item-hsn, .pcs-item-coupon, .pcs-item-serialnumber, .pcs-item-unitcode {\n    margin-top: 2px;\n  \tfont-size: 10px;\n  \tcolor: #444444;\n  }\n  .pcs-item-desc {\n      color: #727272;\n      font-size: 9pt;\n   }\n  .pcs-balance {\n    background-color: #f5f4f3;\n    font-size: 9pt;\n    color: #000000;\n  }\n  .pcs-savings {\n  font-size: 0pt;\n  color: ;\n  background-color: ;\n  }\n  .pcs-totals {\n    font-size: 9pt;\n    color: #000000;\n    background-color: #ffffff;\n  }\n  .pcs-notes {\n    font-size: 8pt;\n  }\n  .pcs-terms {\n    font-size: 8pt;\n  }\n  .pcs-header-first {\n\tbackground-color: #ffffff;\n\tfont-size: 9pt;\n\tcolor: #333333;\n      height: auto;\n\t}\n\n .pcs-status {\n \tcolor: ;\n\tfont-size: 15pt;\n\tborder: 3px solid ;\n\tpadding: 3px 8px;\n }\n .billto-section {\n     padding-top: 0mm;\n     padding-left: 0mm;\n   }\n   .shipto-section {\n     padding-top: 0mm;\n     padding-left: 0mm;\n   }\n\n @page :first {\n \t@top-center {\n\t\tcontent: element(header);\n\t}\n    margin-top: 0.700000in;\n  }\n\n  .pcs-template-header {\n\tpadding: 0 0.400000in 0 0.550000in;\n    height: 0.700000in;\n  }\n\n  .pcs-template-fill-emptydiv {\n    display: table-cell;\n    content: " ";\n    width: 100%;\n  }\n\n\n/* Additional styles for RTL compat */\n\n/* Helper Classes */\n\n.inline {\n  display: inline-block;\n}\n.v-top {\n  vertical-align: top;\n}\n.text-align-right {\n  text-align: right;\n}\n.rtl .text-align-right {\n  text-align: left;\n}\n.text-align-left {\n  text-align: left;\n}\n.rtl .text-align-left {\n  text-align: right;\n}\n.float-section-right {\n  float: right;\n}\n.rtl .float-section-right{\n  float: left;\n}\n.float-section-left {\n  float: left;\n}\n.rtl .float-section-left{\n  float: right;\n}\n\n/* Helper Classes End */\n\n.item-details-inline {\n  display: inline-block;\n  margin: 0 10px;\n  vertical-align: top;\n  max-width: 70%;\n}\n\n.total-in-words-container {\n  width: 100%;\n  margin-top: 10px;\n}\n.total-in-words-label {\n  vertical-align: top;\n  padding: 0 10px;\n}\n.total-in-words-value {\n  width: 170px;\n}\n.total-section-label {\n  padding: 5px 10px 5px 0;\n  vertical-align: middle;\n}\n.total-section-value {\n  width: 120px;\n  vertical-align: middle;\n  padding: 10px 10px 10px 5px;\n}\n.rtl .total-section-value {\n  padding: 10px 5px 10px 10px;\n}\n\n.tax-summary-description {\n  color: #727272;\n  font-size: 8pt;\n}\n\n.bharatqr-bg {\n  background-color: #f4f3f8;\n}\n\n/* Overrides/Patches for RTL compat */\n  .rtl th {\n    text-align: inherit; /* Specifically setting th as inherit for supporting RTL */\n  }\n/* Overrides/Patches End */\n\n  /* Signature styles */\n  .sign-border {\n    width: 200px;\n    border-bottom: 1px solid #000;\n  }\n  .sign-label {\n    display: table-cell;\n    font-size: 10pt;\n    padding-right: 5px;\n  }\n  /* Signature styles End */\n\n/* Subject field styles */\n.subject-block {\n    margin-top: 20px;\n}\n.subject-block-value {\n    word-wrap: break-word;\n    white-space: pre-wrap;\n    line-height: 14pt;\n    margin-top:5px;\n}\n/* Subject field styles End*/\n\n.pcs-sub-label {\n  color: #666;\n  font-size: 10px;\n}\n.pcs-hsnsummary-compact {\n  padding: 0;\n  margin-top: 3px;\n}\n.pcs-hsnsummary-label-compact {\n  margin-bottom: 3px;\n  font-weight:600;\n  padding-left: 3px;\n  font-size: 9pt;\n}\n.pcs-hsnsummary-header-compact {\n  text-align:right;\n  padding: 5px 7px 2px 7px;\n  word-wrap: break-word;\n  width: 17%;\n  height: 32px;\n  border-right: 1px solid #9E9E9E;\n  font-size: 8pt;\n  font-weight: 600;\n}\n.pcs-hsnsummary-body-compact, .pcs-hsnsummary-total-compact {\n  text-align:right;\n  word-wrap: break-word;\n  font-size: 7pt;\n  padding: 4px 10px;\n}\n.pcs-hsnsummary-total-compact {\n  border-top: 1px solid #adadad;\n}\n.pcs-ukvat-summary {\n  margin-top:50px;\n  clear: both;\n  width: 100%;\n}\n.pcs-ukvat-summary-header {\n  padding:5px 10px 5px 5px;\n}\n.pcs-ukvat-summary-header:first-child {\n  padding-left: 10px;\n}\n.pcs-ukvat-summary-label {\n  font-size: 10pt;\n}\n.pcs-ukvat-summary-table {\n  margin-top: 10px;\n  width: 100%;\n  table-layout: fixed;\n}\n.pcs-ukvat-summary-body, .pcs-ukvat-summary-total {\n  padding: 10px 10px 5px 10px;\n}\n.pcs-ukvat-summary-body:first-child {\n  padding-bottom: 10px;\n  padding-right: 0;\n}\n.pcs-payment-block {\n  margin-top: 20px;\n}\n.pcs-payment-block-inner {\n  margin-top: 10px;\n}\n\n.pcs-entity-label-section {\n  padding:5px 10px 5px 0px;\n  font-size: 10pt;\n }\n\n.pcs-colon {\n  width: 3%;\n}\n\n\n  \n\n\n.pcs-w-100 {\n  width: 100%;\n}\n\n\n\n\n\n\n\n.pcs-d-table-cell {\n  display: table-cell;\n}\n\n\n\n\n\n.pcs-talign-center {\n  text-align: center;\n}\n.pcs-wordwrap-bw {\n  word-wrap: break-word;\n}\n.pcs-whitespace-pw {\n  white-space: pre-wrap;\n}\n.pcs-fw-600 {\n  font-weight: 600;\n}\n.pcs-text-uppercase {\n  text-transform: uppercase;\n}\n\n\n\n\n\n.pcs-table-fixed {\n  table-layout:fixed;\n}\n\n\n\n\n\n.pcs-valign-middle {\n  vertical-align: middle;\n}\n\n\n\n.pcs-clearfix {\n  clear: both;\n}\n  .lineitem-column{\n    padding: 10px 10px 5px 10px;\n    word-wrap: break-word;\n  }\n  .entity-details-padding{\n     padding: 5px 10px 5px 0px;\n   }\n  .rtl .entity-details-padding{\n    padding: 5px 0px 5px 10px;\n  }\n  .line-item-padding{\n    padding: 10px 10px 10px 5px;\n  }\n  .rtl .line-item-padding{\n    padding: 10px 5px 10px 10px;\n  }\n  .item-block-padding{\n    padding: 5px 10px 5px 5px;\n  }\n  .rtl .item-block-padding{\n    padding: 5px 5px 5px 10px;\n  }\n\n</style>\n\n<!--style_end-->\n\n<div class="pcs-template ">\n\t  <div id="header" class="pcs-template-header pcs-header-content" >\n    \n\n    \n    <div class="pcs-template-fill-emptydiv"></div>\n\n  </div>\n\n\t<div class="pcs-template-body ">\n\t\t<div style="display:table;width:100%;">\n         <div style="width:50%;" class="float-section-left">\n             <div>\n                    <img id="logo_content" style="width:74.00px;height:72.00px;" src="https://inventory.zoho.in/ZFInvoiceLogo.zbfs?logo_id=85f9b86c9358f692665d4d07b8857d0d" />\n            </div>\n            <span class="pcs-orgname"><b>KVTEK Power Systems Pvt. Ltd.</b></span><br />\n            <span class="pcs-label">\n\t\t\t<span id="tmp_org_address" style="white-space: pre-wrap;">Company ID : U74220DL2005PTC135994&#10;284-286 &amp; 290&#10;Sector-8, IMT Manesar&#10;Gurgaon Haryana 122050&#10;India&#10;GSTIN 06AABCE4590P1Z7&#10;PAN AABCE4590P</span>\n\t\t\t</span>\n         </div>\n         <div style="width:50%;" class="float-section-right text-align-right">\n            <span class="pcs-entity-title">VENDOR CREDITS</span><br />\n            <span class="pcs-label" style="font-size: 10pt;" id="tmp_entity_number"><b>CreditNote# 1145</b></span>\n\n            <div style="clear:both;margin-top:20px;">\n                <span style="font-size:8pt;"><b>Credits Remaining</b></span><br />\n                <span style="font-size:12pt;"><b>₹0.00</b></span>\n            </div>\n         </div>\n     </div>\n\n     <table style="width:100%;margin-top:30px;table-layout:fixed;">\n     \t<tr>\n     \t<td style="width:60%;vertical-align:bottom;word-wrap: break-word;">\n<div><label class="pcs-label"  style="font-size: 10pt;">Vendor Address</label>\n            <br />\n\t\t\t<span id="tmp_billing_address" style="white-space: pre-wrap;"><strong><span id="zb-pdf-customer-detail" class="pcs-customer-name">Enerdrive GmbH</span></strong>\nTechnoparkstr. 1&#10;CH - 8005 Zürich\nSwaziland</span>\n    \t\t</div>     \t</td>\n     \t<td style="vertical-align:bottom;width: 40%;" class="text-align-right">\n     \t\t<table cellpadding="0" cellspacing="0" border="0" style="width: 100%;table-layout: fixed;word-wrap: break-word;" class="float-section-right">\n                 <tbody>\n                     <tr>\n                         <td style="font-size:10pt;" class="text-align-right entity-details-padding">\n                            <span  class="pcs-label">Date :</span>\n                        </td>\n                        <td class="text-align-right">\n                            <span id="tmp_entity_date">21/12/2022</span>\n                        </td>\n                    </tr>\n\n\n\n                 </tbody>\n              </table>\n     \t</td>\n     \t</tr>\n     </table>\n\n\n  <table cellpadding="0" cellspacing="0" border="0" class="pcs-itemtable" style="width:100%;margin-top:20px;table-layout:fixed;">\n    <thead>\n        <tr style="height:32px;">\n            <td class="pcs-itemtable-header item-block-padding" style="word-wrap: break-word;width: 5%;" align="center">\n                 #\n            </td>\n            <td class="pcs-itemtable-header pcs-itemtable-description" style="padding: 5px 10px 5px 30px;word-wrap: break-word;">\n                 Item &amp; Description\n            </td>\n\n\n\n\n\n\n\n\n\n            <td class="pcs-itemtable-header text-align-right item-block-padding" style="word-wrap: break-word;width: 11%;">\n              Qty\n            </td>\n\n\n            <td  class="pcs-itemtable-header text-align-right item-block-padding" style="word-wrap: break-word;width: 11%;">\n                 Rate\n            </td>\n            <td class="pcs-itemtable-header text-align-right item-block-padding" style="word-wrap: break-word;width:120px;">\n                  Amount\n            </td>\n        </tr>\n     </thead>\n     <tbody class="itemBody">\n            <tr class="breakrow-inside breakrow-after">\n                <td class="pcs-item-row item-block-padding" style="word-wrap: break-word;width: 5%;" align="center" rowspan="1">\n                    1\n                </td>\n            <td class="pcs-item-row" style="padding: 10px 0px 10px 30px;" valign="top">\n\t\t\t\t\t\t\t<div >\n\t\t\t\t\t\t\t<div >\n               \n               \n               <span id="tmp_item_description" class="pcs-item-desc" style="white-space: pre-wrap;word-wrap: break-word;">Exchange Difference</span>\n               \n\t\t\t\t\t\t\t \t </div>\n\t\t\t\t\t\t\t </div>\n            </td>\n\n\n\n\n\n\n\n\n\n                <td class="pcs-item-row text-align-right" style="padding: 10px 10px 5px 10px;word-wrap: break-word;" valign="top">\n                  <span id="tmp_item_qty">1.00</span>\n                </td>\n\n            <td class="pcs-item-row text-align-right" style="padding: 10px 10px 5px 10px;word-wrap: break-word;" valign="top">\n                  <span id="tmp_item_rate">1,145.75</span>\n            </td>\n            <td class="pcs-item-row text-align-right line-item-padding" style="word-wrap: break-word;" valign="top">\n              <span id="tmp_item_amount">1,145.75</span>\n            </td>\n          </tr>\n    </tbody>\n    </table>\n   <div style="width: 100%;margin-top: 1px;">\n    <div class="float-section-left" style="width: 45%;padding: 3px 10px 3px 3px;font-size: 9pt;">\n      <div style="white-space: pre-wrap;">\n      </div>\n    </div>\n    <div class="float-section-right" style="width: 50%;">\n      <table width="100%" border="0"  cellspacing="0" class="pcs-totals">\n        <tbody>\n          <tr>\n                <td class="text-align-right entity-details-padding" valign="middle">Sub Total</td>\n                <td style="width:120px;" class="text-align-right line-item-padding" valign="middle" id="tmp_subtotal">1,145.75</td>\n          </tr>\n\n        <!-- TDS or CIS Label -->\n\n          <tr >\n            <td class="text-align-right entity-details-padding" valign="middle"><b>Total</b></td>\n            <td style="width:120px;" class="text-align-right line-item-padding" valign="middle" id="tmp_total"><b>₹1,145.75</b></td>\n          </tr>\n\n          <tr style="height:10px;">\n            <td class="text-align-right entity-details-padding" valign="middle">Credits Used</td>\n            <td style="color: red;width:120px;" class="text-align-right line-item-padding" valign="middle">(-) 1,145.75</td>\n          </tr>\n\n          <tr class="pcs-balance" style="height:40px;">\n            <td valign="middle" class="text-align-right entity-details-padding"><b>Credits Remaining</b></td>\n            <td style="width:120px;" valign="middle" class="text-align-right line-item-padding" id="tmp_balance_due"><b>₹0.00</b></td>\n          </tr>\n        </tbody>\n      </table>\n    </div>\n    <div style="clear: both;"></div>\n  </div>\n<div style="clear:both;margin-top:50px;width:100%;">\n  <label  class="pcs-label" style="font-size: 10pt;">Notes</label><br />\n  <p class="pcs-notes" style="margin-top:7px;white-space: pre-wrap;word-wrap: break-word;">being exchange rate difference on import of EURO 695</p>\n</div>\n\n      <div style="margin-top:30px;">\n        <label class="pcs-label" style="display: table-cell;font-size: 10pt;padding-right: 5px;">Authorized Signature</label>\n          <div style="display: table-cell;">\n              <div style="display: inline-block;width: 200px;border-bottom: 1px solid #000;"></div>\n              <div></div>\n          </div>\n      </div>\n\n\n    \n\t</div>\n\t  <div class="pcs-template-footer">\n    <div >\n      \n    </div>  \n  </div>\n\n</div>\n',
  approvers_list: [
    {
      order: 1,
      approver_user_id: "536460000000024001",
      approver_name: "Girish Kumar",
      email: "girish@kvtek.in",
      has_approved: true,
      approval_status: "approved",
      approval_status_formatted: "approved",
      is_next_approver: false,
      submitted_date: "",
      submitted_date_formatted: "",
      approved_date: "2023-03-13",
      approved_date_formatted: "13/03/2023",
      photo_url: "https://contacts.zoho.in/file?t=user&ID=60008794037&fs=thumb",
      user_status: "active",
      user_status_formatted: "Active",
      is_final_approver: false,
      available_apps: ["Zoho Books", "Zoho Inventory"],
      zuid: "60008794037",
    },
  ],
};
