warehouses = {
  warehouse_id: "536460000000014524",
  warehouse_name: "Main Store",
  attention: "",
  address: "284 - 286, Sector 8",
  address1: "284 - 286, Sector 8",
  address2: "",
  city: "Gurgaon",
  state: "Haryana",
  state_code: "HR",
  country: "India",
  zip: "122050",
  phone: "",
  email: "it.kvtek@outlook.com",
  is_primary: true,
  status: "active",
  status_formatted: "Active",
  is_fba_warehouse: false,
  sales_channels: [],
};
